/*
 Highcharts JS v8.2.0 (2020-10-07)

 (c) 2009-2019 Sebastian Bochan, Rafal Sebestjanski

 License: www.highcharts.com/license
*/
(function(c){"object"===typeof module&&module.exports?(c["default"]=c,module.exports=c):"function"===typeof define&&define.amd?define("highcharts/modules/dumbbell",["highcharts"],function(r){c(r);c.Highcharts=r;return c}):c("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(c){function r(c,t,q,h){c.hasOwnProperty(t)||(c[t]=h.apply(null,q))}c=c?c._modules:{};r(c,"Series/AreaRangeSeries.js",[c["Core/Series/Series.js"],c["Core/Globals.js"],c["Core/Series/Point.js"],c["Core/Utilities.js"]],
function(c,t,q,h){var x=h.defined,n=h.extend,r=h.isArray,d=h.isNumber,w=h.pick,v=c.seriesTypes.area.prototype,b=c.seriesTypes.column.prototype,m=q.prototype,u=t.Series.prototype;c.seriesType("arearange","area",{lineWidth:1,threshold:null,tooltip:{pointFormat:'<span style="color:{series.color}">\u25cf</span> {series.name}: <b>{point.low}</b> - <b>{point.high}</b><br/>'},trackByArea:!0,dataLabels:{align:void 0,verticalAlign:void 0,xLow:0,xHigh:0,yLow:0,yHigh:0}},{pointArrayMap:["low","high"],pointValKey:"low",
deferTranslatePolar:!0,toYData:function(f){return[f.low,f.high]},highToXY:function(f){var b=this.chart,a=this.xAxis.postTranslate(f.rectPlotX,this.yAxis.len-f.plotHigh);f.plotHighX=a.x-b.plotLeft;f.plotHigh=a.y-b.plotTop;f.plotLowX=f.plotX},translate:function(){var f=this,b=f.yAxis,a=!!f.modifyValue;v.translate.apply(f);f.points.forEach(function(e){var l=e.high,g=e.plotY;e.isNull?e.plotY=null:(e.plotLow=g,e.plotHigh=b.translate(a?f.modifyValue(l,e):l,0,1,0,1),a&&(e.yBottom=e.plotHigh))});this.chart.polar&&
this.points.forEach(function(a){f.highToXY(a);a.tooltipPos=[(a.plotHighX+a.plotLowX)/2,(a.plotHigh+a.plotLow)/2]})},getGraphPath:function(f){var b=[],a=[],c,l=v.getGraphPath;var g=this.options;var u=this.chart.polar,p=u&&!1!==g.connectEnds,k=g.connectNulls,m=g.step;f=f||this.points;for(c=f.length;c--;){var d=f[c];var h=u?{plotX:d.rectPlotX,plotY:d.yBottom,doCurve:!1}:{plotX:d.plotX,plotY:d.plotY,doCurve:!1};d.isNull||p||k||f[c+1]&&!f[c+1].isNull||a.push(h);var n={polarPlotY:d.polarPlotY,rectPlotX:d.rectPlotX,
yBottom:d.yBottom,plotX:w(d.plotHighX,d.plotX),plotY:d.plotHigh,isNull:d.isNull};a.push(n);b.push(n);d.isNull||p||k||f[c-1]&&!f[c-1].isNull||a.push(h)}f=l.call(this,f);m&&(!0===m&&(m="left"),g.step={left:"right",center:"center",right:"left"}[m]);b=l.call(this,b);a=l.call(this,a);g.step=m;g=[].concat(f,b);!this.chart.polar&&a[0]&&"M"===a[0][0]&&(a[0]=["L",a[0][1],a[0][2]]);this.graphPath=g;this.areaPath=f.concat(a);g.isArea=!0;g.xMap=f.xMap;this.areaPath.xMap=f.xMap;return g},drawDataLabels:function(){var b=
this.points,e=b.length,a,c=[],l=this.options.dataLabels,g,d=this.chart.inverted;if(r(l))if(1<l.length){var m=l[0];var k=l[1]}else m=l[0],k={enabled:!1};else m=n({},l),m.x=l.xHigh,m.y=l.yHigh,k=n({},l),k.x=l.xLow,k.y=l.yLow;if(m.enabled||this._hasPointLabels){for(a=e;a--;)if(g=b[a]){var h=m.inside?g.plotHigh<g.plotLow:g.plotHigh>g.plotLow;g.y=g.high;g._plotY=g.plotY;g.plotY=g.plotHigh;c[a]=g.dataLabel;g.dataLabel=g.dataLabelUpper;g.below=h;d?m.align||(m.align=h?"right":"left"):m.verticalAlign||(m.verticalAlign=
h?"top":"bottom")}this.options.dataLabels=m;u.drawDataLabels&&u.drawDataLabels.apply(this,arguments);for(a=e;a--;)if(g=b[a])g.dataLabelUpper=g.dataLabel,g.dataLabel=c[a],delete g.dataLabels,g.y=g.low,g.plotY=g._plotY}if(k.enabled||this._hasPointLabels){for(a=e;a--;)if(g=b[a])h=k.inside?g.plotHigh<g.plotLow:g.plotHigh>g.plotLow,g.below=!h,d?k.align||(k.align=h?"left":"right"):k.verticalAlign||(k.verticalAlign=h?"bottom":"top");this.options.dataLabels=k;u.drawDataLabels&&u.drawDataLabels.apply(this,
arguments)}if(m.enabled)for(a=e;a--;)if(g=b[a])g.dataLabels=[g.dataLabelUpper,g.dataLabel].filter(function(a){return!!a});this.options.dataLabels=l},alignDataLabel:function(){b.alignDataLabel.apply(this,arguments)},drawPoints:function(){var b=this.points.length,e;u.drawPoints.apply(this,arguments);for(e=0;e<b;){var a=this.points[e];a.origProps={plotY:a.plotY,plotX:a.plotX,isInside:a.isInside,negative:a.negative,zone:a.zone,y:a.y};a.lowerGraphic=a.graphic;a.graphic=a.upperGraphic;a.plotY=a.plotHigh;
x(a.plotHighX)&&(a.plotX=a.plotHighX);a.y=a.high;a.negative=a.high<(this.options.threshold||0);a.zone=this.zones.length&&a.getZone();this.chart.polar||(a.isInside=a.isTopInside="undefined"!==typeof a.plotY&&0<=a.plotY&&a.plotY<=this.yAxis.len&&0<=a.plotX&&a.plotX<=this.xAxis.len);e++}u.drawPoints.apply(this,arguments);for(e=0;e<b;)a=this.points[e],a.upperGraphic=a.graphic,a.graphic=a.lowerGraphic,n(a,a.origProps),delete a.origProps,e++},setStackedPoints:t.noop},{setState:function(){var b=this.state,
e=this.series,a=e.chart.polar;x(this.plotHigh)||(this.plotHigh=e.yAxis.toPixels(this.high,!0));x(this.plotLow)||(this.plotLow=this.plotY=e.yAxis.toPixels(this.low,!0));e.stateMarkerGraphic&&(e.lowerStateMarkerGraphic=e.stateMarkerGraphic,e.stateMarkerGraphic=e.upperStateMarkerGraphic);this.graphic=this.upperGraphic;this.plotY=this.plotHigh;a&&(this.plotX=this.plotHighX);m.setState.apply(this,arguments);this.state=b;this.plotY=this.plotLow;this.graphic=this.lowerGraphic;a&&(this.plotX=this.plotLowX);
e.stateMarkerGraphic&&(e.upperStateMarkerGraphic=e.stateMarkerGraphic,e.stateMarkerGraphic=e.lowerStateMarkerGraphic,e.lowerStateMarkerGraphic=void 0);m.setState.apply(this,arguments)},haloPath:function(){var b=this.series.chart.polar,e=[];this.plotY=this.plotLow;b&&(this.plotX=this.plotLowX);this.isInside&&(e=m.haloPath.apply(this,arguments));this.plotY=this.plotHigh;b&&(this.plotX=this.plotHighX);this.isTopInside&&(e=e.concat(m.haloPath.apply(this,arguments)));return e},destroyElements:function(){["lowerGraphic",
"upperGraphic"].forEach(function(b){this[b]&&(this[b]=this[b].destroy())},this);this.graphic=null;return m.destroyElements.apply(this,arguments)},isValid:function(){return d(this.low)&&d(this.high)}});""});r(c,"Series/ColumnRangeSeries.js",[c["Core/Series/Series.js"],c["Core/Globals.js"],c["Core/Options.js"],c["Core/Utilities.js"]],function(c,t,q,h){t=t.noop;q=q.defaultOptions;var r=h.clamp,n=h.merge,y=h.pick,d=c.seriesTypes.column.prototype;c.seriesType("columnrange","arearange",n(q.plotOptions.column,
q.plotOptions.arearange,{pointRange:null,marker:null,states:{hover:{halo:!1}}}),{translate:function(){var c=this,h=c.yAxis,b=c.xAxis,m=b.startAngleRad,u,f=c.chart,e=c.xAxis.isRadial,a=Math.max(f.chartWidth,f.chartHeight)+999,n;d.translate.apply(c);c.points.forEach(function(d){var g=d.shapeArgs,l=c.options.minPointLength;d.plotHigh=n=r(h.translate(d.high,0,1,0,1),-a,a);d.plotLow=r(d.plotY,-a,a);var p=n;var k=y(d.rectPlotY,d.plotY)-n;Math.abs(k)<l?(l-=k,k+=l,p-=l/2):0>k&&(k*=-1,p-=k);e?(u=d.barX+m,
d.shapeType="arc",d.shapeArgs=c.polarArc(p+k,p,u,u+d.pointWidth)):(g.height=k,g.y=p,d.tooltipPos=f.inverted?[h.len+h.pos-f.plotLeft-p-k/2,b.len+b.pos-f.plotTop-g.x-g.width/2,k]:[b.left-f.plotLeft+g.x+g.width/2,h.pos-f.plotTop+p+k/2,k])})},directTouch:!0,trackerGroups:["group","dataLabelsGroup"],drawGraph:t,getSymbol:t,crispCol:function(){return d.crispCol.apply(this,arguments)},drawPoints:function(){return d.drawPoints.apply(this,arguments)},drawTracker:function(){return d.drawTracker.apply(this,
arguments)},getColumnMetrics:function(){return d.getColumnMetrics.apply(this,arguments)},pointAttribs:function(){return d.pointAttribs.apply(this,arguments)},animate:function(){return d.animate.apply(this,arguments)},polarArc:function(){return d.polarArc.apply(this,arguments)},translate3dPoints:function(){return d.translate3dPoints.apply(this,arguments)},translate3dShapes:function(){return d.translate3dShapes.apply(this,arguments)}},{setState:d.pointClass.prototype.setState});""});r(c,"Series/DumbbellSeries.js",
[c["Core/Series/Series.js"],c["Core/Renderer/SVG/SVGRenderer.js"],c["Core/Globals.js"],c["Core/Utilities.js"]],function(c,r,q,h){var t=h.extend,n=h.pick,y=q.Series.prototype;h=c.seriesTypes;var d=h.arearange.prototype,w=h.column.prototype,v=d.pointClass.prototype;c.seriesType("dumbbell","arearange",{trackByArea:!1,fillColor:"none",lineWidth:0,pointRange:1,connectorWidth:1,stickyTracking:!1,groupPadding:.2,crisp:!1,pointPadding:.1,lowColor:"#333333",states:{hover:{lineWidthPlus:0,connectorWidthPlus:1,
halo:!1}}},{trackerGroups:["group","markerGroup","dataLabelsGroup"],drawTracker:q.TrackerMixin.drawTrackerPoint,drawGraph:q.noop,crispCol:w.crispCol,getConnectorAttribs:function(b){var c=this.chart,d=b.options,f=this.options,e=this.xAxis,a=this.yAxis,h=n(d.connectorWidth,f.connectorWidth),l=n(d.connectorColor,f.connectorColor,d.color,b.zone?b.zone.color:void 0,b.color),g=n(f.states&&f.states.hover&&f.states.hover.connectorWidthPlus,1),q=n(d.dashStyle,f.dashStyle),p=n(b.plotLow,b.plotY),k=a.toPixels(f.threshold||
0,!0);k=n(b.plotHigh,c.inverted?a.len-k:k);b.state&&(h+=g);0>p?p=0:p>=a.len&&(p=a.len);0>k?k=0:k>=a.len&&(k=a.len);if(0>b.plotX||b.plotX>e.len)h=0;b.upperGraphic&&(e={y:b.y,zone:b.zone},b.y=b.high,b.zone=b.zone?b.getZone():void 0,l=n(d.connectorColor,f.connectorColor,d.color,b.zone?b.zone.color:void 0,b.color),t(b,e));b={d:r.prototype.crispLine([["M",b.plotX,p],["L",b.plotX,k]],h,"ceil")};c.styledMode||(b.stroke=l,b["stroke-width"]=h,q&&(b.dashstyle=q));return b},drawConnector:function(b){var c=n(this.options.animationLimit,
250);c=b.connector&&this.chart.pointCount<c?"animate":"attr";b.connector||(b.connector=this.chart.renderer.path().addClass("highcharts-lollipop-stem").attr({zIndex:-1}).add(this.markerGroup));b.connector[c](this.getConnectorAttribs(b))},getColumnMetrics:function(){var b=w.getColumnMetrics.apply(this,arguments);b.offset+=b.width/2;return b},translatePoint:d.translate,setShapeArgs:h.columnrange.prototype.translate,translate:function(){this.setShapeArgs.apply(this);this.translatePoint.apply(this,arguments);
this.points.forEach(function(b){var c=b.shapeArgs,d=b.pointWidth;b.plotX=c.x;c.x=b.plotX-d/2;b.tooltipPos=null});this.columnMetrics.offset-=this.columnMetrics.width/2},seriesDrawPoints:d.drawPoints,drawPoints:function(){var b=this.chart,c=this.points.length,d=this.lowColor=this.options.lowColor,f=0;for(this.seriesDrawPoints.apply(this,arguments);f<c;){var e=this.points[f];this.drawConnector(e);e.upperGraphic&&(e.upperGraphic.element.point=e,e.upperGraphic.addClass("highcharts-lollipop-high"));e.connector.element.point=
e;if(e.lowerGraphic){var a=e.zone&&e.zone.color;a=n(e.options.lowColor,d,e.options.color,a,e.color,this.color);b.styledMode||e.lowerGraphic.attr({fill:a});e.lowerGraphic.addClass("highcharts-lollipop-low")}f++}},markerAttribs:function(){var b=d.markerAttribs.apply(this,arguments);b.x=Math.floor(b.x);b.y=Math.floor(b.y);return b},pointAttribs:function(b,c){var d=y.pointAttribs.apply(this,arguments);"hover"===c&&delete d.fill;return d}},{destroyElements:v.destroyElements,isValid:v.isValid,pointSetState:v.setState,
setState:function(){var b=this.series,c=b.chart,d=b.options.marker,f=this.options,e=n(f.lowColor,b.options.lowColor,f.color,this.zone&&this.zone.color,this.color,b.color),a="attr";this.pointSetState.apply(this,arguments);this.state||(a="animate",this.lowerGraphic&&!c.styledMode&&(this.lowerGraphic.attr({fill:e}),this.upperGraphic&&(c={y:this.y,zone:this.zone},this.y=this.high,this.zone=this.zone?this.getZone():void 0,d=n(this.marker?this.marker.fillColor:void 0,d?d.fillColor:void 0,f.color,this.zone?
this.zone.color:void 0,this.color),this.upperGraphic.attr({fill:d}),t(this,c))));this.connector[a](b.getConnectorAttribs(this))}});""});r(c,"masters/modules/dumbbell.src.js",[],function(){})});
//# sourceMappingURL=dumbbell.js.map