/*
 Highcharts Gantt JS v8.2.0 (2020-10-07)

 Gantt series

 (c) 2016-2019 Lars A. V. Cabrera

 License: www.highcharts.com/license
*/
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/gantt",["highcharts"],function(H){b(H);b.Highcharts=H;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function H(b,w,x,y){b.hasOwnProperty(w)||(b[w]=y.apply(null,x))}b=b?b._modules:{};H(b,"Gantt/Tree.js",[b["Core/Utilities.js"]],function(b){var w=b.extend,x=b.isNumber,y=b.pick,v=function(b,B){var c=b.reduce(function(c,
u){var z=y(u.parent,"");"undefined"===typeof c[z]&&(c[z]=[]);c[z].push(u);return c},{});Object.keys(c).forEach(function(l,u){var z=c[l];""!==l&&-1===B.indexOf(l)&&(z.forEach(function(c){u[""].push(c)}),delete u[l])});return c},q=function(b,B,c,l,u,z){var p=0,t=0,C=z&&z.after,e=z&&z.before;B={data:l,depth:c-1,id:b,level:c,parent:B};var n,h;"function"===typeof e&&e(B,z);e=(u[b]||[]).map(function(a){var g=q(a.id,b,c+1,a,u,z),d=a.start;a=!0===a.milestone?d:a.end;n=!x(n)||d<n?d:n;h=!x(h)||a>h?a:h;p=p+
1+g.descendants;t=Math.max(g.height+1,t);return g});l&&(l.start=y(l.start,n),l.end=y(l.end,h));w(B,{children:e,descendants:p,height:t});"function"===typeof C&&C(B,z);return B};return{getListOfParents:v,getNode:q,getTree:function(b,B){var c=b.map(function(c){return c.id});b=v(b,c);return q("",null,1,null,b,B)}}});H(b,"Core/Axis/TreeGridTick.js",[b["Core/Utilities.js"]],function(b){var w=b.addEvent,x=b.defined,y=b.isObject,v=b.isNumber,q=b.pick,D=b.wrap,B;(function(c){function l(){this.treeGrid||(this.treeGrid=
new C(this))}function u(e,n){e=e.treeGrid;var h=!e.labelIcon,a=n.renderer,g=n.xy,d=n.options,r=d.width,m=d.height,f=g.x-r/2-d.padding;g=g.y-m/2;var G=n.collapsed?90:180,I=n.show&&v(g),A=e.labelIcon;A||(e.labelIcon=A=a.path(a.symbols[d.type](d.x,d.y,r,m)).addClass("highcharts-label-icon").add(n.group));I||A.attr({y:-9999});a.styledMode||A.attr({"stroke-width":1,fill:q(n.color,"#666666")}).css({cursor:"pointer",stroke:d.lineColor,strokeWidth:d.lineWidth});A[h?"attr":"animate"]({translateX:f,translateY:g,
rotation:G})}function z(e,n,h,a,g,d,r,m,f){var G=q(this.options&&this.options.labels,d);d=this.pos;var I=this.axis,A="treegrid"===I.options.type;e=e.apply(this,[n,h,a,g,G,r,m,f]);A&&(n=G&&y(G.symbol,!0)?G.symbol:{},G=G&&v(G.indentation)?G.indentation:0,d=(d=(I=I.treeGrid.mapOfPosToGridNode)&&I[d])&&d.depth||1,e.x+=n.width+2*n.padding+(d-1)*G);return e}function p(e){var n=this,h=n.pos,a=n.axis,g=n.label,d=a.treeGrid.mapOfPosToGridNode,r=a.options,m=q(n.options&&n.options.labels,r&&r.labels),f=m&&y(m.symbol,
!0)?m.symbol:{},G=(d=d&&d[h])&&d.depth;r="treegrid"===r.type;var I=-1<a.tickPositions.indexOf(h);h=a.chart.styledMode;r&&d&&g&&g.element&&g.addClass("highcharts-treegrid-node-level-"+G);e.apply(n,Array.prototype.slice.call(arguments,1));r&&g&&g.element&&d&&d.descendants&&0<d.descendants&&(a=a.treeGrid.isCollapsed(d),u(n,{color:!h&&g.styles&&g.styles.color||"",collapsed:a,group:g.parentGroup,options:f,renderer:g.renderer,show:I,xy:g.xy}),f="highcharts-treegrid-node-"+(a?"expanded":"collapsed"),g.addClass("highcharts-treegrid-node-"+
(a?"collapsed":"expanded")).removeClass(f),h||g.css({cursor:"pointer"}),[g,n.treeGrid.labelIcon].forEach(function(a){a&&!a.attachedTreeGridEvents&&(w(a.element,"mouseover",function(){g.addClass("highcharts-treegrid-node-active");g.renderer.styledMode||g.css({textDecoration:"underline"})}),w(a.element,"mouseout",function(){var a=x(m.style)?m.style:{};g.removeClass("highcharts-treegrid-node-active");g.renderer.styledMode||g.css({textDecoration:a.textDecoration})}),w(a.element,"click",function(){n.treeGrid.toggleCollapse()}),
a.attachedTreeGridEvents=!0)}))}var t=!1;c.compose=function(e){t||(w(e,"init",l),D(e.prototype,"getLabelPosition",z),D(e.prototype,"renderLabel",p),e.prototype.collapse=function(e){this.treeGrid.collapse(e)},e.prototype.expand=function(e){this.treeGrid.expand(e)},e.prototype.toggleCollapse=function(e){this.treeGrid.toggleCollapse(e)},t=!0)};var C=function(){function e(e){this.tick=e}e.prototype.collapse=function(e){var h=this.tick,a=h.axis,g=a.brokenAxis;g&&a.treeGrid.mapOfPosToGridNode&&(h=a.treeGrid.collapse(a.treeGrid.mapOfPosToGridNode[h.pos]),
g.setBreaks(h,q(e,!0)))};e.prototype.expand=function(e){var h=this.tick,a=h.axis,g=a.brokenAxis;g&&a.treeGrid.mapOfPosToGridNode&&(h=a.treeGrid.expand(a.treeGrid.mapOfPosToGridNode[h.pos]),g.setBreaks(h,q(e,!0)))};e.prototype.toggleCollapse=function(e){var h=this.tick,a=h.axis,g=a.brokenAxis;g&&a.treeGrid.mapOfPosToGridNode&&(h=a.treeGrid.toggleCollapse(a.treeGrid.mapOfPosToGridNode[h.pos]),g.setBreaks(h,q(e,!0)))};return e}();c.Additions=C})(B||(B={}));return B});H(b,"Mixins/TreeSeries.js",[b["Core/Color/Color.js"],
b["Core/Utilities.js"]],function(b,w){var x=w.extend,y=w.isArray,v=w.isNumber,q=w.isObject,D=w.merge,B=w.pick;return{getColor:function(c,l){var u=l.index,z=l.mapOptionsToLevel,p=l.parentColor,t=l.parentColorIndex,C=l.series,e=l.colors,n=l.siblings,h=C.points,a=C.chart.options.chart,g;if(c){h=h[c.i];c=z[c.level]||{};if(z=h&&c.colorByPoint){var d=h.index%(e?e.length:a.colorCount);var r=e&&e[d]}if(!C.chart.styledMode){e=h&&h.options.color;a=c&&c.color;if(g=p)g=(g=c&&c.colorVariation)&&"brightness"===
g.key?b.parse(p).brighten(u/n*g.to).get():p;g=B(e,a,r,g,C.color)}var m=B(h&&h.options.colorIndex,c&&c.colorIndex,d,t,l.colorIndex)}return{color:g,colorIndex:m}},getLevelOptions:function(c){var l=null;if(q(c)){l={};var u=v(c.from)?c.from:1;var z=c.levels;var p={};var t=q(c.defaults)?c.defaults:{};y(z)&&(p=z.reduce(function(c,e){if(q(e)&&v(e.level)){var n=D({},e);var h="boolean"===typeof n.levelIsConstant?n.levelIsConstant:t.levelIsConstant;delete n.levelIsConstant;delete n.level;e=e.level+(h?0:u-1);
q(c[e])?x(c[e],n):c[e]=n}return c},{}));z=v(c.to)?c.to:1;for(c=0;c<=z;c++)l[c]=D({},t,q(p[c])?p[c]:{})}return l},setTreeValues:function z(l,u){var p=u.before,t=u.idRoot,C=u.mapIdToNode[t],e=u.points[l.i],n=e&&e.options||{},h=0,a=[];x(l,{levelDynamic:l.level-(("boolean"===typeof u.levelIsConstant?u.levelIsConstant:1)?0:C.level),name:B(e&&e.name,""),visible:t===l.id||("boolean"===typeof u.visible?u.visible:!1)});"function"===typeof p&&(l=p(l,u));l.children.forEach(function(g,d){var r=x({},u);x(r,{index:d,
siblings:l.children.length,visible:l.visible});g=z(g,r);a.push(g);g.visible&&(h+=g.val)});l.visible=0<h||l.visible;p=B(n.value,h);x(l,{children:a,childrenTotal:h,isLeaf:l.visible&&!h,val:p});return l},updateRootId:function(l){if(q(l)){var u=q(l.options)?l.options:{};u=B(l.rootNode,u.rootId,"");q(l.userOptions)&&(l.userOptions.rootId=u);l.rootNode=u}return u}}});H(b,"Core/Axis/GridAxis.js",[b["Core/Axis/Axis.js"],b["Core/Globals.js"],b["Core/Options.js"],b["Core/Axis/Tick.js"],b["Core/Utilities.js"]],
function(b,w,x,y,v){var q=v.addEvent,D=v.defined,B=v.erase,c=v.find,l=v.isArray,u=v.isNumber,z=v.merge,p=v.pick,t=v.timeUnits,C=v.wrap;x=w.Chart;var e=function(a){var g=a.options;g.labels||(g.labels={});g.labels.align=p(g.labels.align,"center");a.categories||(g.showLastLabel=!1);a.labelRotation=0;g.labels.rotation=0};"";b.prototype.getMaxLabelDimensions=function(a,g){var d={width:0,height:0};g.forEach(function(g){g=a[g];if(v.isObject(g,!0)){var m=v.isObject(g.label,!0)?g.label:{};g=m.getBBox?m.getBBox().height:
0;m.textStr&&!u(m.textPxLength)&&(m.textPxLength=m.getBBox().width);var f=u(m.textPxLength)?Math.round(m.textPxLength):0;m.textStr&&(f=Math.round(m.getBBox().width));d.height=Math.max(g,d.height);d.width=Math.max(f,d.width)}});return d};w.dateFormats.W=function(a){a=new this.Date(a);var g=(this.get("Day",a)+6)%7,d=new this.Date(a.valueOf());this.set("Date",d,this.get("Date",a)-g+3);g=new this.Date(this.get("FullYear",d),0,1);4!==this.get("Day",g)&&(this.set("Month",a,0),this.set("Date",a,1+(11-this.get("Day",
g))%7));return(1+Math.floor((d.valueOf()-g.valueOf())/6048E5)).toString()};w.dateFormats.E=function(a){return this.dateFormat("%a",a,!0).charAt(0)};q(x,"afterSetChartSize",function(){this.axes.forEach(function(a){(a.grid&&a.grid.columns||[]).forEach(function(a){a.setAxisSize();a.setAxisTranslation()})})});q(y,"afterGetLabelPosition",function(a){var g=this.label,d=this.axis,r=d.reversed,m=d.chart,f=d.options.grid||{},e=d.options.labels,I=e.align,A=h.Side[d.side],c=a.tickmarkOffset,n=d.tickPositions,
J=this.pos-c;n=u(n[a.index+1])?n[a.index+1]-c:d.max+c;var k=d.tickSize("tick");c=k?k[0]:0;k=k?k[1]/2:0;if(!0===f.enabled){if("top"===A){f=d.top+d.offset;var E=f-c}else"bottom"===A?(E=m.chartHeight-d.bottom+d.offset,f=E+c):(f=d.top+d.len-d.translate(r?n:J),E=d.top+d.len-d.translate(r?J:n));"right"===A?(A=m.chartWidth-d.right+d.offset,r=A+c):"left"===A?(r=d.left+d.offset,A=r-c):(A=Math.round(d.left+d.translate(r?n:J))-k,r=Math.round(d.left+d.translate(r?J:n))-k);this.slotWidth=r-A;a.pos.x="left"===
I?A:"right"===I?r:A+(r-A)/2;a.pos.y=E+(f-E)/2;m=m.renderer.fontMetrics(e.style.fontSize,g.element);g=g.getBBox().height;e.useHTML?a.pos.y+=m.b+-(g/2):(g=Math.round(g/m.h),a.pos.y+=(m.b-(m.h-m.f))/2+-((g-1)*m.h/2));a.pos.x+=d.horiz&&e.x||0}});var n=function(){function a(a){this.axis=a}a.prototype.isOuterAxis=function(){var a=this.axis,d=a.grid.columnIndex,r=a.linkedParent&&a.linkedParent.grid.columns||a.grid.columns,m=d?a.linkedParent:a,f=-1,e=0;a.chart[a.coll].forEach(function(g,d){g.side!==a.side||
g.options.isInternal||(e=d,g===m&&(f=d))});return e===f&&(u(d)?r.length===d:!0)};a.prototype.renderBorder=function(a){var d=this.axis,g=d.chart.renderer,m=d.options;a=g.path(a).addClass("highcharts-axis-line").add(d.axisBorder);g.styledMode||a.attr({stroke:m.lineColor,"stroke-width":m.lineWidth,zIndex:7});return a};return a}(),h=function(){function a(){}a.compose=function(g){b.keepProps.push("grid");C(g.prototype,"unsquish",a.wrapUnsquish);q(g,"init",a.onInit);q(g,"afterGetOffset",a.onAfterGetOffset);
q(g,"afterGetTitlePosition",a.onAfterGetTitlePosition);q(g,"afterInit",a.onAfterInit);q(g,"afterRender",a.onAfterRender);q(g,"afterSetAxisTranslation",a.onAfterSetAxisTranslation);q(g,"afterSetOptions",a.onAfterSetOptions);q(g,"afterSetOptions",a.onAfterSetOptions2);q(g,"afterSetScale",a.onAfterSetScale);q(g,"afterTickSize",a.onAfterTickSize);q(g,"trimTicks",a.onTrimTicks);q(g,"destroy",a.onDestroy)};a.onAfterGetOffset=function(){var a=this.grid;(a&&a.columns||[]).forEach(function(a){a.getOffset()})};
a.onAfterGetTitlePosition=function(g){if(!0===(this.options.grid||{}).enabled){var d=this.axisTitle,r=this.height,m=this.horiz,f=this.left,e=this.offset,c=this.opposite,A=this.options.title,h=void 0===A?{}:A;A=this.top;var n=this.width,J=this.tickSize(),k=d&&d.getBBox().width,E=h.x||0,F=h.y||0,P=p(h.margin,m?5:10);d=this.chart.renderer.fontMetrics(h.style&&h.style.fontSize,d).f;J=(m?A+r:f)+(m?1:-1)*(c?-1:1)*(J?J[0]/2:0)+(this.side===a.Side.bottom?d:0);g.titlePosition.x=m?f-k/2-P+E:J+(c?n:0)+e+E;g.titlePosition.y=
m?J-(c?r:0)+(c?d:-d)/2+e+F:A-P+F}};a.onAfterInit=function(){var a=this.chart,d=this.options.grid;d=void 0===d?{}:d;var r=this.userOptions;d.enabled&&(e(this),C(this,"labelFormatter",function(a){var d=this.axis,g=this.value,m=d.tickPositions,f=(d.isLinked?d.linkedParent:d).series[0],k=g===m[0];m=g===m[m.length-1];var E=f&&c(f.options.data,function(k){return k[d.isXAxis?"x":"y"]===g});if(E&&f.is("gantt")){var F=z(E);w.seriesTypes.gantt.prototype.setGanttPointAliases(F)}this.isFirst=k;this.isLast=m;
this.point=F;return a.call(this)}));if(d.columns)for(var m=this.grid.columns=[],f=this.grid.columnIndex=0;++f<d.columns.length;){var h=z(r,d.columns[d.columns.length-f-1],{linkedTo:0,type:"category",scrollbar:{enabled:!1}});delete h.grid.columns;h=new b(this.chart,h);h.grid.isColumn=!0;h.grid.columnIndex=f;B(a.axes,h);B(a[this.coll],h);m.push(h)}};a.onAfterRender=function(){var g,d=this.grid,r=this.options;if(!0===(r.grid||{}).enabled){this.maxLabelDimensions=this.getMaxLabelDimensions(this.ticks,
this.tickPositions);this.rightWall&&this.rightWall.destroy();if(this.grid&&this.grid.isOuterAxis()&&this.axisLine&&(r=r.lineWidth)){r=this.getLinePath(r);var m=r[0],f=r[1],e=((this.tickSize("tick")||[1])[0]-1)*(this.side===a.Side.top||this.side===a.Side.left?-1:1);"M"===m[0]&&"L"===f[0]&&(this.horiz?(m[2]+=e,f[2]+=e):(m[1]+=e,f[1]+=e));!this.horiz&&this.chart.marginRight&&(m=[m,["L",this.left,m[2]]],e=["L",this.chart.chartWidth-this.chart.marginRight,this.toPixels(this.max+this.tickmarkOffset)],f=
[["M",f[1],this.toPixels(this.max+this.tickmarkOffset)],e],this.grid.upperBorder||0===this.min%1||(this.grid.upperBorder=this.grid.renderBorder(m)),this.grid.upperBorder&&this.grid.upperBorder.animate({d:m}),this.grid.lowerBorder||0===this.max%1||(this.grid.lowerBorder=this.grid.renderBorder(f)),this.grid.lowerBorder&&this.grid.lowerBorder.animate({d:f}));this.grid.axisLineExtra?this.grid.axisLineExtra.animate({d:r}):this.grid.axisLineExtra=this.grid.renderBorder(r);this.axisLine[this.showAxis?"show":
"hide"](!0)}(d&&d.columns||[]).forEach(function(a){a.render()});!this.horiz&&this.chart.hasRendered&&(this.scrollbar||(null===(g=this.linkedParent)||void 0===g?0:g.scrollbar))&&(g=this.max,d=this.tickmarkOffset,r=this.tickPositions[this.tickPositions.length-1],f=this.tickPositions[0],this.min-f>d?this.ticks[f].label.hide():this.ticks[f].label.show(),r-g>d?this.ticks[r].label.hide():this.ticks[r].label.show(),r-g<d&&0<r-g&&this.ticks[r].isLast?this.ticks[r].mark.hide():this.ticks[r-1].mark.show())}};
a.onAfterSetAxisTranslation=function(){var a,d=this.tickPositions&&this.tickPositions.info,e=this.options,m=e.grid||{},f=this.userOptions.labels||{};this.horiz?(!0===m.enabled&&this.series.forEach(function(a){a.options.pointRange=0}),d&&e.dateTimeLabelFormats&&e.labels&&!D(f.align)&&(!1===e.dateTimeLabelFormats[d.unitName].range||1<d.count)&&(e.labels.align="left",D(f.x)||(e.labels.x=3))):"treegrid"!==this.options.type&&(null===(a=this.grid)||void 0===a?0:a.columns)&&(this.minPointOffset=this.tickInterval)};
a.onAfterSetOptions=function(a){var d=this.options;a=a.userOptions;var g=d&&v.isObject(d.grid,!0)?d.grid:{};if(!0===g.enabled){var m=z(!0,{className:"highcharts-grid-axis "+(a.className||""),dateTimeLabelFormats:{hour:{list:["%H:%M","%H"]},day:{list:["%A, %e. %B","%a, %e. %b","%E"]},week:{list:["Week %W","W%W"]},month:{list:["%B","%b","%o"]}},grid:{borderWidth:1},labels:{padding:2,style:{fontSize:"13px"}},margin:0,title:{text:null,reserveSpace:!1,rotation:0},units:[["millisecond",[1,10,100]],["second",
[1,10]],["minute",[1,5,15]],["hour",[1,6]],["day",[1]],["week",[1]],["month",[1]],["year",null]]},a);"xAxis"===this.coll&&(D(a.linkedTo)&&!D(a.tickPixelInterval)&&(m.tickPixelInterval=350),D(a.tickPixelInterval)||!D(a.linkedTo)||D(a.tickPositioner)||D(a.tickInterval)||(m.tickPositioner=function(a,d){var g=this.linkedParent&&this.linkedParent.tickPositions&&this.linkedParent.tickPositions.info;if(g){var f,e=m.units;for(f=0;f<e.length;f++)if(e[f][0]===g.unitName){var r=f;break}if(e[r+1]){var J=e[r+
1][0];var k=(e[r+1][1]||[1])[0]}else"year"===g.unitName&&(J="year",k=10*g.count);g=t[J];this.tickInterval=g*k;return this.getTimeTicks({unitRange:g,count:k,unitName:J},a,d,this.options.startOfWeek)}}));z(!0,this.options,m);this.horiz&&(d.minPadding=p(a.minPadding,0),d.maxPadding=p(a.maxPadding,0));u(d.grid.borderWidth)&&(d.tickWidth=d.lineWidth=g.borderWidth)}};a.onAfterSetOptions2=function(a){a=(a=a.userOptions)&&a.grid||{};var d=a.columns;a.enabled&&d&&z(!0,this.options,d[d.length-1])};a.onAfterSetScale=
function(){(this.grid.columns||[]).forEach(function(a){a.setScale()})};a.onAfterTickSize=function(a){var d=b.defaultLeftAxisOptions,g=this.horiz,m=this.maxLabelDimensions,f=this.options.grid;f=void 0===f?{}:f;f.enabled&&m&&(d=2*Math.abs(d.labels.x),g=g?f.cellHeight||d+m.height:d+m.width,l(a.tickSize)?a.tickSize[0]=g:a.tickSize=[g,0])};a.onDestroy=function(a){var d=this.grid;(d.columns||[]).forEach(function(d){d.destroy(a.keepEvents)});d.columns=void 0};a.onInit=function(a){a=a.userOptions||{};var d=
a.grid||{};d.enabled&&D(d.borderColor)&&(a.tickColor=a.lineColor=d.borderColor);this.grid||(this.grid=new n(this))};a.onTrimTicks=function(){var a=this.options,d=this.categories,e=this.tickPositions,m=e[0],f=e[e.length-1],h=this.linkedParent&&this.linkedParent.min||this.min,c=this.linkedParent&&this.linkedParent.max||this.max,A=this.tickInterval;!0!==(a.grid||{}).enabled||d||!this.horiz&&!this.isLinked||(m<h&&m+A>h&&!a.startOnTick&&(e[0]=h),f>c&&f-A<c&&!a.endOnTick&&(e[e.length-1]=c))};a.wrapUnsquish=
function(a){var d=this.options.grid;return!0===(void 0===d?{}:d).enabled&&this.categories?this.tickInterval:a.apply(this,Array.prototype.slice.call(arguments,1))};return a}();(function(a){a=a.Side||(a.Side={});a[a.top=0]="top";a[a.right=1]="right";a[a.bottom=2]="bottom";a[a.left=3]="left"})(h||(h={}));h.compose(b);return h});H(b,"Core/Axis/BrokenAxis.js",[b["Core/Axis/Axis.js"],b["Series/LineSeries.js"],b["Extensions/Stacking.js"],b["Core/Utilities.js"]],function(b,w,x,y){var v=y.addEvent,q=y.find,
D=y.fireEvent,B=y.isArray,c=y.isNumber,l=y.pick,u=function(){function c(c){this.hasBreaks=!1;this.axis=c}c.isInBreak=function(c,t){var C=c.repeat||Infinity,e=c.from,n=c.to-c.from;t=t>=e?(t-e)%C:C-(e-t)%C;return c.inclusive?t<=n:t<n&&0!==t};c.lin2Val=function(p){var t=this.brokenAxis;t=t&&t.breakArray;if(!t)return p;var C;for(C=0;C<t.length;C++){var e=t[C];if(e.from>=p)break;else e.to<p?p+=e.len:c.isInBreak(e,p)&&(p+=e.len)}return p};c.val2Lin=function(p){var t=this.brokenAxis;t=t&&t.breakArray;if(!t)return p;
var C=p,e;for(e=0;e<t.length;e++){var n=t[e];if(n.to<=p)C-=n.len;else if(n.from>=p)break;else if(c.isInBreak(n,p)){C-=p-n.from;break}}return C};c.prototype.findBreakAt=function(c,t){return q(t,function(t){return t.from<c&&c<t.to})};c.prototype.isInAnyBreak=function(p,t){var C=this.axis,e=C.options.breaks,n=e&&e.length,h;if(n){for(;n--;)if(c.isInBreak(e[n],p)){var a=!0;h||(h=l(e[n].showPoints,!C.isXAxis))}var g=a&&t?a&&!h:a}return g};c.prototype.setBreaks=function(p,t){var C=this,e=C.axis,n=B(p)&&
!!p.length;e.isDirty=C.hasBreaks!==n;C.hasBreaks=n;e.options.breaks=e.userOptions.breaks=p;e.forceRedraw=!0;e.series.forEach(function(e){e.isDirty=!0});n||e.val2lin!==c.val2Lin||(delete e.val2lin,delete e.lin2val);n&&(e.userOptions.ordinal=!1,e.lin2val=c.lin2Val,e.val2lin=c.val2Lin,e.setExtremes=function(e,a,g,d,c){if(C.hasBreaks){for(var m,f=this.options.breaks;m=C.findBreakAt(e,f);)e=m.to;for(;m=C.findBreakAt(a,f);)a=m.from;a<e&&(a=e)}b.prototype.setExtremes.call(this,e,a,g,d,c)},e.setAxisTranslation=
function(h){b.prototype.setAxisTranslation.call(this,h);C.unitLength=null;if(C.hasBreaks){h=e.options.breaks||[];var a=[],g=[],d=0,r,m=e.userMin||e.min,f=e.userMax||e.max,n=l(e.pointRangePadding,0),I;h.forEach(function(a){r=a.repeat||Infinity;c.isInBreak(a,m)&&(m+=a.to%r-m%r);c.isInBreak(a,f)&&(f-=f%r-a.from%r)});h.forEach(function(d){t=d.from;for(r=d.repeat||Infinity;t-r>m;)t-=r;for(;t<m;)t+=r;for(I=t;I<f;I+=r)a.push({value:I,move:"in"}),a.push({value:I+(d.to-d.from),move:"out",size:d.breakSize})});
a.sort(function(a,d){return a.value===d.value?("in"===a.move?0:1)-("in"===d.move?0:1):a.value-d.value});var A=0;var t=m;a.forEach(function(a){A+="in"===a.move?1:-1;1===A&&"in"===a.move&&(t=a.value);0===A&&(g.push({from:t,to:a.value,len:a.value-t-(a.size||0)}),d+=a.value-t-(a.size||0))});e.breakArray=C.breakArray=g;C.unitLength=f-m-d+n;D(e,"afterBreaks");e.staticScale?e.transA=e.staticScale:C.unitLength&&(e.transA*=(f-e.min+n)/C.unitLength);n&&(e.minPixelPadding=e.transA*e.minPointOffset);e.min=m;
e.max=f}});l(t,!0)&&e.chart.redraw()};return c}();y=function(){function z(){}z.compose=function(p,t){p.keepProps.push("brokenAxis");var C=w.prototype;C.drawBreaks=function(e,n){var h=this,a=h.points,g,d,r,m;if(e&&e.brokenAxis&&e.brokenAxis.hasBreaks){var f=e.brokenAxis;n.forEach(function(n){g=f&&f.breakArray||[];d=e.isXAxis?e.min:l(h.options.threshold,e.min);a.forEach(function(a){m=l(a["stack"+n.toUpperCase()],a[n]);g.forEach(function(f){if(c(d)&&c(m)){r=!1;if(d<f.from&&m>f.to||d>f.from&&m<f.from)r=
"pointBreak";else if(d<f.from&&m>f.from&&m<f.to||d>f.from&&m>f.to&&m<f.from)r="pointInBreak";r&&D(e,r,{point:a,brk:f})}})})})}};C.gappedPath=function(){var e=this.currentDataGrouping,c=e&&e.gapSize;e=this.options.gapSize;var h=this.points.slice(),a=h.length-1,g=this.yAxis,d;if(e&&0<a)for("value"!==this.options.gapUnit&&(e*=this.basePointRange),c&&c>e&&c>=this.basePointRange&&(e=c),d=void 0;a--;)d&&!1!==d.visible||(d=h[a+1]),c=h[a],!1!==d.visible&&!1!==c.visible&&(d.x-c.x>e&&(d=(c.x+d.x)/2,h.splice(a+
1,0,{isNull:!0,x:d}),g.stacking&&this.options.stacking&&(d=g.stacking.stacks[this.stackKey][d]=new x(g,g.options.stackLabels,!1,d,this.stack),d.total=0)),d=c);return this.getGraphPath(h)};v(p,"init",function(){this.brokenAxis||(this.brokenAxis=new u(this))});v(p,"afterInit",function(){"undefined"!==typeof this.brokenAxis&&this.brokenAxis.setBreaks(this.options.breaks,!1)});v(p,"afterSetTickPositions",function(){var e=this.brokenAxis;if(e&&e.hasBreaks){var c=this.tickPositions,h=this.tickPositions.info,
a=[],g;for(g=0;g<c.length;g++)e.isInAnyBreak(c[g])||a.push(c[g]);this.tickPositions=a;this.tickPositions.info=h}});v(p,"afterSetOptions",function(){this.brokenAxis&&this.brokenAxis.hasBreaks&&(this.options.ordinal=!1)});v(t,"afterGeneratePoints",function(){var e=this.options.connectNulls,c=this.points,h=this.xAxis,a=this.yAxis;if(this.isDirty)for(var g=c.length;g--;){var d=c[g],r=!(null===d.y&&!1===e)&&(h&&h.brokenAxis&&h.brokenAxis.isInAnyBreak(d.x,!0)||a&&a.brokenAxis&&a.brokenAxis.isInAnyBreak(d.y,
!0));d.visible=r?!1:!1!==d.options.visible}});v(t,"afterRender",function(){this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,l(this.pointArrayMap,["y"]))})};return z}();y.compose(b,w);return y});H(b,"Core/Axis/TreeGridAxis.js",[b["Core/Globals.js"],b["Core/Axis/Axis.js"],b["Core/Axis/Tick.js"],b["Gantt/Tree.js"],b["Core/Axis/TreeGridTick.js"],b["Mixins/TreeSeries.js"],b["Core/Utilities.js"]],function(b,w,x,y,v,q,D){var B=q.getLevelOptions,c=D.addEvent,l=D.find,u=D.fireEvent,z=D.isArray,
p=D.isNumber,t=D.isObject,C=D.isString,e=D.merge,n=D.pick,h=D.wrap,a;(function(a){function d(a,k){var d=a.collapseStart||0;a=a.collapseEnd||0;a>=k&&(d-=.5);return{from:d,to:a,showPoints:!1}}function g(a,k,d){var f=[],m=[],E={},e={},g=-1,c="boolean"===typeof k?k:!1;a=y.getTree(a,{after:function(a){a=e[a.pos];var k=0,d=0;a.children.forEach(function(a){d+=(a.descendants||0)+1;k=Math.max((a.height||0)+1,k)});a.descendants=d;a.height=k;a.collapsed&&m.push(a)},before:function(a){var k=t(a.data,!0)?a.data:
{},d=C(k.name)?k.name:"",m=E[a.parent];m=t(m,!0)?e[m.pos]:null;var F=function(a){return a.name===d},r;c&&t(m,!0)&&(r=l(m.children,F))?(F=r.pos,r.nodes.push(a)):F=g++;e[F]||(e[F]=r={depth:m?m.depth+1:0,name:d,id:k.id,nodes:[a],children:[],pos:F},-1!==F&&f.push(d),t(m,!0)&&m.children.push(r));C(a.id)&&(E[a.id]=a);r&&!0===k.collapsed&&(r.collapsed=!0);a.pos=F}});e=function(a,k){var d=function(a,m,f){var E=m+(-1===m?0:k-1),e=(E-m)/2,g=m+e;a.nodes.forEach(function(a){var k=a.data;t(k,!0)&&(k.y=m+(k.seriesIndex||
0),delete k.seriesIndex);a.pos=g});f[g]=a;a.pos=g;a.tickmarkOffset=e+.5;a.collapseStart=E+.5;a.children.forEach(function(a){d(a,E+1,f);E=(a.collapseEnd||0)-.5});a.collapseEnd=E+.5;return f};return d(a["-1"],-1,{})}(e,d);return{categories:f,mapOfIdToNode:E,mapOfPosToGridNode:e,collapsedNodes:m,tree:a}}function m(a){a.target.axes.filter(function(a){return"treegrid"===a.options.type}).forEach(function(k){var d=k.options||{},m=d.labels,f=d.uniqueNames,c=0;d=d.max;if(!k.treeGrid.mapOfPosToGridNode||k.series.some(function(a){return!a.hasRendered||
a.isDirtyData||a.isDirty})){var r=k.series.reduce(function(a,k){k.visible&&((k.options.data||[]).forEach(function(d){k.options.keys&&k.options.keys.length&&(d=k.pointClass.prototype.optionsToObject.call({series:k},d),b.seriesTypes.gantt.prototype.setGanttPointAliases(d));t(d,!0)&&(d.seriesIndex=c,a.push(d))}),!0===f&&c++);return a},[]);if(d&&r.length<d)for(var h=r.length;h<=d;h++)r.push({name:h+"\u200b"});d=g(r,f||!1,!0===f?c:1);k.categories=d.categories;k.treeGrid.mapOfPosToGridNode=d.mapOfPosToGridNode;
k.hasNames=!0;k.treeGrid.tree=d.tree;k.series.forEach(function(a){var k=(a.options.data||[]).map(function(k){z(k)&&a.options.keys&&a.options.keys.length&&r.forEach(function(a){0<=k.indexOf(a.x)&&0<=k.indexOf(a.x2)&&(k=a)});return t(k,!0)?e(k):k});a.visible&&a.setData(k,!1)});k.treeGrid.mapOptionsToLevel=B({defaults:m,from:1,levels:m&&m.levels,to:k.treeGrid.tree&&k.treeGrid.tree.height});"beforeRender"===a.type&&(k.treeGrid.collapsedNodes=d.collapsedNodes)}})}function f(a,k){var d=this.treeGrid.mapOptionsToLevel||
{},m=this.ticks,f=m[k],e;if("treegrid"===this.options.type&&this.treeGrid.mapOfPosToGridNode){var g=this.treeGrid.mapOfPosToGridNode[k];(d=d[g.depth])&&(e={labels:d});f?(f.parameters.category=g.name,f.options=e,f.addLabel()):m[k]=new x(this,k,void 0,void 0,{category:g.name,tickmarkOffset:g.tickmarkOffset,options:e})}else a.apply(this,Array.prototype.slice.call(arguments,1))}function G(a){var k=this.options;k=(k=k&&k.labels)&&p(k.indentation)?k.indentation:0;var d=a.apply(this,Array.prototype.slice.call(arguments,
1));if("treegrid"===this.options.type&&this.treeGrid.mapOfPosToGridNode){var m=this.treeGrid.mapOfPosToGridNode[-1].height||0;d.width+=k*(m-1)}return d}function I(a,k,d){var f=this,E="treegrid"===d.type;f.treeGrid||(f.treeGrid=new q(f));E&&(c(k,"beforeRender",m),c(k,"beforeRedraw",m),c(k,"addSeries",function(a){a.options.data&&(a=g(a.options.data,d.uniqueNames||!1,1),f.treeGrid.collapsedNodes=(f.treeGrid.collapsedNodes||[]).concat(a.collapsedNodes))}),c(f,"foundExtremes",function(){f.treeGrid.collapsedNodes&&
f.treeGrid.collapsedNodes.forEach(function(a){var k=f.treeGrid.collapse(a);f.brokenAxis&&(f.brokenAxis.setBreaks(k,!1),f.treeGrid.collapsedNodes&&(f.treeGrid.collapsedNodes=f.treeGrid.collapsedNodes.filter(function(k){return a.collapseStart!==k.collapseStart||a.collapseEnd!==k.collapseEnd})))})}),c(f,"afterBreaks",function(){var a;"yAxis"===f.coll&&!f.staticScale&&(null===(a=f.chart.options.chart)||void 0===a?0:a.height)&&(f.isDirty=!0)}),d=e({grid:{enabled:!0},labels:{align:"left",levels:[{level:void 0},
{level:1,style:{fontWeight:"bold"}}],symbol:{type:"triangle",x:-5,y:-5,height:10,width:10,padding:5}},uniqueNames:!1},d,{reversed:!0,grid:{columns:void 0}}));a.apply(f,[k,d]);E&&(f.hasNames=!0,f.options.showLastLabel=!0)}function A(a){var k=this.options;"treegrid"===k.type?(this.min=n(this.userMin,k.min,this.dataMin),this.max=n(this.userMax,k.max,this.dataMax),u(this,"foundExtremes"),this.setAxisTranslation(!0),this.tickmarkOffset=.5,this.tickInterval=1,this.tickPositions=this.treeGrid.mapOfPosToGridNode?
this.treeGrid.getTickPositions():[]):a.apply(this,Array.prototype.slice.call(arguments,1))}var M=!1;a.compose=function(a){M||(h(a.prototype,"generateTick",f),h(a.prototype,"getMaxLabelDimensions",G),h(a.prototype,"init",I),h(a.prototype,"setTickInterval",A),v.compose(x),M=!0)};var q=function(){function a(a){this.axis=a}a.prototype.setCollapsedStatus=function(a){var k=this.axis,d=k.chart;k.series.forEach(function(k){var f=k.options.data;if(a.id&&f){var m=d.get(a.id);k=f[k.data.indexOf(m)];m&&k&&(m.collapsed=
a.collapsed,k.collapsed=a.collapsed)}})};a.prototype.collapse=function(a){var k=this.axis,f=k.options.breaks||[],m=d(a,k.max);f.push(m);a.collapsed=!0;k.treeGrid.setCollapsedStatus(a);return f};a.prototype.expand=function(a){var k=this.axis,f=k.options.breaks||[],m=d(a,k.max);a.collapsed=!1;k.treeGrid.setCollapsedStatus(a);return f.reduce(function(a,k){k.to===m.to&&k.from===m.from||a.push(k);return a},[])};a.prototype.getTickPositions=function(){var a=this.axis,d=Math.floor(a.min/a.tickInterval)*
a.tickInterval,f=Math.ceil(a.max/a.tickInterval)*a.tickInterval;return Object.keys(a.treeGrid.mapOfPosToGridNode||{}).reduce(function(k,m){m=+m;!(m>=d&&m<=f)||a.brokenAxis&&a.brokenAxis.isInAnyBreak(m)||k.push(m);return k},[])};a.prototype.isCollapsed=function(a){var k=this.axis,f=k.options.breaks||[],m=d(a,k.max);return f.some(function(a){return a.from===m.from&&a.to===m.to})};a.prototype.toggleCollapse=function(a){return this.isCollapsed(a)?this.expand(a):this.collapse(a)};return a}();a.Additions=
q})(a||(a={}));w.prototype.utils={getNode:y.getNode};a.compose(w);return a});H(b,"Extensions/CurrentDateIndication.js",[b["Core/Axis/Axis.js"],b["Core/Options.js"],b["Core/Utilities.js"],b["Core/Axis/PlotLineOrBand.js"]],function(b,w,x,y){var v=w.dateFormat;w=x.addEvent;var q=x.merge;x=x.wrap;var D={currentDateIndicator:!0,color:"#ccd6eb",width:2,label:{format:"%a, %b %d %Y, %H:%M",formatter:function(b,c){return v(c,b)},rotation:0,style:{fontSize:"10px"}}};w(b,"afterSetOptions",function(){var b=this.options,
c=b.currentDateIndicator;c&&(c="object"===typeof c?q(D,c):q(D),c.value=new Date,b.plotLines||(b.plotLines=[]),b.plotLines.push(c))});w(y,"render",function(){this.label&&this.label.attr({text:this.getLabelText(this.options.label)})});x(y.prototype,"getLabelText",function(b,c){var l=this.options;return l.currentDateIndicator&&l.label&&"function"===typeof l.label.formatter?(l.value=new Date,l.label.formatter.call(this,l.value,l.label.format)):b.call(this,c)})});H(b,"Extensions/StaticScale.js",[b["Core/Axis/Axis.js"],
b["Core/Chart/Chart.js"],b["Core/Utilities.js"]],function(b,w,x){var y=x.addEvent,v=x.defined,q=x.isNumber,D=x.pick;y(b,"afterSetOptions",function(){var b=this.chart.options&&this.chart.options.chart;!this.horiz&&q(this.options.staticScale)&&(!b.height||b.scrollablePlotArea&&b.scrollablePlotArea.minHeight)&&(this.staticScale=this.options.staticScale)});w.prototype.adjustHeight=function(){"adjustHeight"!==this.redrawTrigger&&((this.axes||[]).forEach(function(b){var c=b.chart,l=!!c.initiatedScale&&
c.options.animation,u=b.options.staticScale;if(b.staticScale&&v(b.min)){var z=D(b.brokenAxis&&b.brokenAxis.unitLength,b.max+b.tickInterval-b.min)*u;z=Math.max(z,u);u=z-c.plotHeight;1<=Math.abs(u)&&(c.plotHeight=z,c.redrawTrigger="adjustHeight",c.setSize(void 0,c.chartHeight+u,l));b.series.forEach(function(b){(b=b.sharedClipKey&&c[b.sharedClipKey])&&b.attr({height:c.plotHeight})})}}),this.initiatedScale=!0);this.redrawTrigger=null};y(w,"render",w.prototype.adjustHeight)});H(b,"Extensions/ArrowSymbols.js",
[b["Core/Renderer/SVG/SVGRenderer.js"]],function(b){b.prototype.symbols.arrow=function(b,x,y,v){return[["M",b,x+v/2],["L",b+y,x],["L",b,x+v/2],["L",b+y,x+v]]};b.prototype.symbols["arrow-half"]=function(w,x,y,v){return b.prototype.symbols.arrow(w,x,y/2,v)};b.prototype.symbols["triangle-left"]=function(b,x,y,v){return[["M",b+y,x],["L",b,x+v/2],["L",b+y,x+v],["Z"]]};b.prototype.symbols["arrow-filled"]=b.prototype.symbols["triangle-left"];b.prototype.symbols["triangle-left-half"]=function(w,x,y,v){return b.prototype.symbols["triangle-left"](w,
x,y/2,v)};b.prototype.symbols["arrow-filled-half"]=b.prototype.symbols["triangle-left-half"]});H(b,"Gantt/Connection.js",[b["Core/Globals.js"],b["Core/Options.js"],b["Core/Series/Point.js"],b["Core/Utilities.js"]],function(b,w,x,y){function v(c){var b=c.shapeArgs;return b?{xMin:b.x,xMax:b.x+b.width,yMin:b.y,yMax:b.y+b.height}:(b=c.graphic&&c.graphic.getBBox())?{xMin:c.plotX-b.width/2,xMax:c.plotX+b.width/2,yMin:c.plotY-b.height/2,yMax:c.plotY+b.height/2}:null}"";var q=y.defined,D=y.error,B=y.extend,
c=y.merge,l=y.objectEach,u=b.deg2rad,z=Math.max,p=Math.min;B(w.defaultOptions,{connectors:{type:"straight",lineWidth:1,marker:{enabled:!1,align:"center",verticalAlign:"middle",inside:!1,lineWidth:1},startMarker:{symbol:"diamond"},endMarker:{symbol:"arrow-filled"}}});w=function(){function b(c,e,b){this.toPoint=this.pathfinder=this.graphics=this.fromPoint=this.chart=void 0;this.init(c,e,b)}b.prototype.init=function(c,e,b){this.fromPoint=c;this.toPoint=e;this.options=b;this.chart=c.series.chart;this.pathfinder=
this.chart.pathfinder};b.prototype.renderPath=function(c,e,b){var h=this.chart,a=h.styledMode,g=h.pathfinder,d=!h.options.chart.forExport&&!1!==b,r=this.graphics&&this.graphics.path;g.group||(g.group=h.renderer.g().addClass("highcharts-pathfinder-group").attr({zIndex:-1}).add(h.seriesGroup));g.group.translate(h.plotLeft,h.plotTop);r&&r.renderer||(r=h.renderer.path().add(g.group),a||r.attr({opacity:0}));r.attr(e);c={d:c};a||(c.opacity=1);r[d?"animate":"attr"](c,b);this.graphics=this.graphics||{};this.graphics.path=
r};b.prototype.addMarker=function(c,e,b){var h=this.fromPoint.series.chart,a=h.pathfinder;h=h.renderer;var g="start"===c?this.fromPoint:this.toPoint,d=g.getPathfinderAnchorPoint(e);if(e.enabled&&((b="start"===c?b[1]:b[b.length-2])&&"M"===b[0]||"L"===b[0])){b={x:b[1],y:b[2]};b=g.getRadiansToVector(b,d);d=g.getMarkerVector(b,e.radius,d);b=-b/u;if(e.width&&e.height){var r=e.width;var m=e.height}else r=m=2*e.radius;this.graphics=this.graphics||{};d={x:d.x-r/2,y:d.y-m/2,width:r,height:m,rotation:b,rotationOriginX:d.x,
rotationOriginY:d.y};this.graphics[c]?this.graphics[c].animate(d):(this.graphics[c]=h.symbol(e.symbol).addClass("highcharts-point-connecting-path-"+c+"-marker").attr(d).add(a.group),h.styledMode||this.graphics[c].attr({fill:e.color||this.fromPoint.color,stroke:e.lineColor,"stroke-width":e.lineWidth,opacity:0}).animate({opacity:1},g.series.options.animation))}};b.prototype.getPath=function(b){var e=this.pathfinder,n=this.chart,h=e.algorithms[b.type],a=e.chartObstacles;if("function"!==typeof h)return D('"'+
b.type+'" is not a Pathfinder algorithm.'),{path:[],obstacles:[]};h.requiresObstacles&&!a&&(a=e.chartObstacles=e.getChartObstacles(b),n.options.connectors.algorithmMargin=b.algorithmMargin,e.chartObstacleMetrics=e.getObstacleMetrics(a));return h(this.fromPoint.getPathfinderAnchorPoint(b.startMarker),this.toPoint.getPathfinderAnchorPoint(b.endMarker),c({chartObstacles:a,lineObstacles:e.lineObstacles||[],obstacleMetrics:e.chartObstacleMetrics,hardBounds:{xMin:0,xMax:n.plotWidth,yMin:0,yMax:n.plotHeight},
obstacleOptions:{margin:b.algorithmMargin},startDirectionX:e.getAlgorithmStartDirection(b.startMarker)},b))};b.prototype.render=function(){var b=this.fromPoint,e=b.series,n=e.chart,h=n.pathfinder,a=c(n.options.connectors,e.options.connectors,b.options.connectors,this.options),g={};n.styledMode||(g.stroke=a.lineColor||b.color,g["stroke-width"]=a.lineWidth,a.dashStyle&&(g.dashstyle=a.dashStyle));g["class"]="highcharts-point-connecting-path highcharts-color-"+b.colorIndex;a=c(g,a);q(a.marker.radius)||
(a.marker.radius=p(z(Math.ceil((a.algorithmMargin||8)/2)-1,1),5));b=this.getPath(a);n=b.path;b.obstacles&&(h.lineObstacles=h.lineObstacles||[],h.lineObstacles=h.lineObstacles.concat(b.obstacles));this.renderPath(n,g,e.options.animation);this.addMarker("start",c(a.marker,a.startMarker),n);this.addMarker("end",c(a.marker,a.endMarker),n)};b.prototype.destroy=function(){this.graphics&&(l(this.graphics,function(c){c.destroy()}),delete this.graphics)};return b}();b.Connection=w;B(x.prototype,{getPathfinderAnchorPoint:function(c){var b=
v(this);switch(c.align){case "right":var e="xMax";break;case "left":e="xMin"}switch(c.verticalAlign){case "top":var n="yMin";break;case "bottom":n="yMax"}return{x:e?b[e]:(b.xMin+b.xMax)/2,y:n?b[n]:(b.yMin+b.yMax)/2}},getRadiansToVector:function(c,b){var e;q(b)||(e=v(this))&&(b={x:(e.xMin+e.xMax)/2,y:(e.yMin+e.yMax)/2});return Math.atan2(b.y-c.y,c.x-b.x)},getMarkerVector:function(c,b,e){var n=2*Math.PI,h=v(this),a=h.xMax-h.xMin,g=h.yMax-h.yMin,d=Math.atan2(g,a),r=!1;a/=2;var m=g/2,f=h.xMin+a;h=h.yMin+
m;for(var G=f,I=h,A={},u=1,p=1;c<-Math.PI;)c+=n;for(;c>Math.PI;)c-=n;n=Math.tan(c);c>-d&&c<=d?(p=-1,r=!0):c>d&&c<=Math.PI-d?p=-1:c>Math.PI-d||c<=-(Math.PI-d)?(u=-1,r=!0):u=-1;r?(G+=u*a,I+=p*a*n):(G+=g/(2*n)*u,I+=p*m);e.x!==f&&(G=e.x);e.y!==h&&(I=e.y);A.x=G+b*Math.cos(c);A.y=I-b*Math.sin(c);return A}});return w});H(b,"Gantt/PathfinderAlgorithms.js",[b["Core/Utilities.js"]],function(b){function w(c,b,p){p=p||0;var u=c.length-1;b-=1e-7;for(var l,e;p<=u;)if(l=u+p>>1,e=b-c[l].xMin,0<e)p=l+1;else if(0>
e)u=l-1;else return l;return 0<p?p-1:0}function x(c,b){for(var u=w(c,b.x+1)+1;u--;){var l;if(l=c[u].xMax>=b.x)l=c[u],l=b.x<=l.xMax&&b.x>=l.xMin&&b.y<=l.yMax&&b.y>=l.yMin;if(l)return u}return-1}function y(c){var b=[];if(c.length){b.push(["M",c[0].start.x,c[0].start.y]);for(var u=0;u<c.length;++u)b.push(["L",c[u].end.x,c[u].end.y])}return b}function v(b,l){b.yMin=c(b.yMin,l.yMin);b.yMax=B(b.yMax,l.yMax);b.xMin=c(b.xMin,l.xMin);b.xMax=B(b.xMax,l.xMax)}var q=b.extend,D=b.pick,B=Math.min,c=Math.max,l=
Math.abs;b=q(function(c,b,p){function u(a,d,f,c,b){a={x:a.x,y:a.y};a[d]=f[c||d]+(b||0);return a}function z(a,d,f){var c=l(d[f]-a[f+"Min"])>l(d[f]-a[f+"Max"]);return u(d,f,a,f+(c?"Max":"Min"),c?1:-1)}var e=[],n=D(p.startDirectionX,l(b.x-c.x)>l(b.y-c.y))?"x":"y",h=p.chartObstacles,a=x(h,c);p=x(h,b);if(-1<p){var g=h[p];p=z(g,b,n);g={start:p,end:b};var d=p}else d=b;-1<a&&(h=h[a],p=z(h,c,n),e.push({start:c,end:p}),p[n]>=c[n]===p[n]>=d[n]&&(n="y"===n?"x":"y",b=c[n]<b[n],e.push({start:p,end:u(p,n,h,n+(b?
"Max":"Min"),b?1:-1)}),n="y"===n?"x":"y"));c=e.length?e[e.length-1].end:c;p=u(c,n,d);e.push({start:c,end:p});n=u(p,"y"===n?"x":"y",d);e.push({start:p,end:n});e.push(g);return{path:y(e),obstacles:e}},{requiresObstacles:!0});return{fastAvoid:q(function(b,z,p){function u(a,k,d){var f,c=a.x<k.x?1:-1;if(a.x<k.x){var m=a;var b=k}else m=k,b=a;if(a.y<k.y){var e=a;var g=k}else e=k,g=a;for(f=0>c?B(w(A,b.x),A.length-1):0;A[f]&&(0<c&&A[f].xMin<=b.x||0>c&&A[f].xMax>=m.x);){if(A[f].xMin<=b.x&&A[f].xMax>=m.x&&A[f].yMin<=
g.y&&A[f].yMax>=e.y)return d?{y:a.y,x:a.x<k.x?A[f].xMin-1:A[f].xMax+1,obstacle:A[f]}:{x:a.x,y:a.y<k.y?A[f].yMin-1:A[f].yMax+1,obstacle:A[f]};f+=c}return k}function q(a,k,d,f,c){var m=c.soft,b=c.hard,e=f?"x":"y",g={x:k.x,y:k.y},E={x:k.x,y:k.y};c=a[e+"Max"]>=m[e+"Max"];m=a[e+"Min"]<=m[e+"Min"];var r=a[e+"Max"]>=b[e+"Max"];b=a[e+"Min"]<=b[e+"Min"];var h=l(a[e+"Min"]-k[e]),F=l(a[e+"Max"]-k[e]);d=10>l(h-F)?k[e]<d[e]:F<h;E[e]=a[e+"Min"];g[e]=a[e+"Max"];a=u(k,E,f)[e]!==E[e];k=u(k,g,f)[e]!==g[e];d=a?k?d:
!0:k?!1:d;d=m?c?d:!0:c?!1:d;return b?r?d:!0:r?!1:d}function e(a,k,b){if(a.x===k.x&&a.y===k.y)return[];var g=b?"x":"y",E=p.obstacleOptions.margin;var r={soft:{xMin:m,xMax:f,yMin:G,yMax:I},hard:p.hardBounds};var h=x(A,a);if(-1<h){h=A[h];r=q(h,a,k,b,r);v(h,p.hardBounds);var n=b?{y:a.y,x:h[r?"xMax":"xMin"]+(r?1:-1)}:{x:a.x,y:h[r?"yMax":"yMin"]+(r?1:-1)};var l=x(A,n);-1<l&&(l=A[l],v(l,p.hardBounds),n[g]=r?c(h[g+"Max"]-E+1,(l[g+"Min"]+h[g+"Max"])/2):B(h[g+"Min"]+E-1,(l[g+"Max"]+h[g+"Min"])/2),a.x===n.x&&
a.y===n.y?(d&&(n[g]=r?c(h[g+"Max"],l[g+"Max"])+1:B(h[g+"Min"],l[g+"Min"])-1),d=!d):d=!1);a=[{start:a,end:n}]}else g=u(a,{x:b?k.x:a.x,y:b?a.y:k.y},b),a=[{start:a,end:{x:g.x,y:g.y}}],g[b?"x":"y"]!==k[b?"x":"y"]&&(r=q(g.obstacle,g,k,!b,r),v(g.obstacle,p.hardBounds),r={x:b?g.x:g.obstacle[r?"xMax":"xMin"]+(r?1:-1),y:b?g.obstacle[r?"yMax":"yMin"]+(r?1:-1):g.y},b=!b,a=a.concat(e({x:g.x,y:g.y},r,b)));return a=a.concat(e(a[a.length-1].end,k,!b))}function n(a,k,d){var f=B(a.xMax-k.x,k.x-a.xMin)<B(a.yMax-k.y,
k.y-a.yMin);d=q(a,k,d,f,{soft:p.hardBounds,hard:p.hardBounds});return f?{y:k.y,x:a[d?"xMax":"xMin"]+(d?1:-1)}:{x:k.x,y:a[d?"yMax":"yMin"]+(d?1:-1)}}var h=D(p.startDirectionX,l(z.x-b.x)>l(z.y-b.y)),a=h?"x":"y",g=[],d=!1,r=p.obstacleMetrics,m=B(b.x,z.x)-r.maxWidth-10,f=c(b.x,z.x)+r.maxWidth+10,G=B(b.y,z.y)-r.maxHeight-10,I=c(b.y,z.y)+r.maxHeight+10,A=p.chartObstacles;var M=w(A,m);r=w(A,f);A=A.slice(M,r+1);if(-1<(r=x(A,z))){var K=n(A[r],z,b);g.push({end:z,start:K});z=K}for(;-1<(r=x(A,z));)M=0>z[a]-b[a],
K={x:z.x,y:z.y},K[a]=A[r][M?a+"Max":a+"Min"]+(M?1:-1),g.push({end:z,start:K}),z=K;b=e(b,z,h);b=b.concat(g.reverse());return{path:y(b),obstacles:b}},{requiresObstacles:!0}),straight:function(c,b){return{path:[["M",c.x,c.y],["L",b.x,b.y]],obstacles:[{start:c,end:b}]}},simpleConnect:b}});H(b,"Gantt/Pathfinder.js",[b["Gantt/Connection.js"],b["Core/Chart/Chart.js"],b["Core/Globals.js"],b["Core/Options.js"],b["Core/Series/Point.js"],b["Core/Utilities.js"],b["Gantt/PathfinderAlgorithms.js"]],function(b,
w,x,y,v,q,D){function B(a){var d=a.shapeArgs;return d?{xMin:d.x,xMax:d.x+d.width,yMin:d.y,yMax:d.y+d.height}:(d=a.graphic&&a.graphic.getBBox())?{xMin:a.plotX-d.width/2,xMax:a.plotX+d.width/2,yMin:a.plotY-d.height/2,yMax:a.plotY+d.height/2}:null}function c(d){for(var c=d.length,b=0,f,g,n=[],A=function(d,f,c){c=e(c,10);var k=d.yMax+c>f.yMin-c&&d.yMin-c<f.yMax+c,b=d.xMax+c>f.xMin-c&&d.xMin-c<f.xMax+c,m=k?d.xMin>f.xMax?d.xMin-f.xMax:f.xMin-d.xMax:Infinity,g=b?d.yMin>f.yMax?d.yMin-f.yMax:f.yMin-d.yMax:
Infinity;return b&&k?c?A(d,f,Math.floor(c/2)):Infinity:a(m,g)};b<c;++b)for(f=b+1;f<c;++f)g=A(d[b],d[f]),80>g&&n.push(g);n.push(80);return h(Math.floor(n.sort(function(a,d){return a-d})[Math.floor(n.length/10)]/2-1),1)}function l(a){if(a.options.pathfinder||a.series.reduce(function(a,d){d.options&&C(!0,d.options.connectors=d.options.connectors||{},d.options.pathfinder);return a||d.options&&d.options.pathfinder},!1))C(!0,a.options.connectors=a.options.connectors||{},a.options.pathfinder),p('WARNING: Pathfinder options have been renamed. Use "chart.connectors" or "series.connectors" instead.')}
"";var u=q.addEvent,z=q.defined,p=q.error,t=q.extend,C=q.merge,e=q.pick,n=q.splat,h=Math.max,a=Math.min;t(y.defaultOptions,{connectors:{type:"straight",lineWidth:1,marker:{enabled:!1,align:"center",verticalAlign:"middle",inside:!1,lineWidth:1},startMarker:{symbol:"diamond"},endMarker:{symbol:"arrow-filled"}}});var g=function(){function a(a){this.lineObstacles=this.group=this.connections=this.chartObstacleMetrics=this.chartObstacles=this.chart=void 0;this.init(a)}a.prototype.init=function(a){this.chart=
a;this.connections=[];u(a,"redraw",function(){this.pathfinder.update()})};a.prototype.update=function(a){var d=this.chart,f=this,c=f.connections;f.connections=[];d.series.forEach(function(a){a.visible&&!a.options.isInternal&&a.points.forEach(function(a){var k=a.options;k&&k.dependency&&(k.connect=k.dependency);var c;k=a.options&&a.options.connect&&n(a.options.connect);a.visible&&!1!==a.isInside&&k&&k.forEach(function(k){c=d.get("string"===typeof k?k:k.to);c instanceof v&&c.series.visible&&c.visible&&
!1!==c.isInside&&f.connections.push(new b(a,c,"string"===typeof k?{}:k))})})});for(var g=0,e,h,r=c.length,l=f.connections.length;g<r;++g){h=!1;for(e=0;e<l;++e)if(c[g].fromPoint===f.connections[e].fromPoint&&c[g].toPoint===f.connections[e].toPoint){f.connections[e].graphics=c[g].graphics;h=!0;break}h||c[g].destroy()}delete this.chartObstacles;delete this.lineObstacles;f.renderConnections(a)};a.prototype.renderConnections=function(a){a?this.chart.series.forEach(function(a){var d=function(){var d=a.chart.pathfinder;
(d&&d.connections||[]).forEach(function(d){d.fromPoint&&d.fromPoint.series===a&&d.render()});a.pathfinderRemoveRenderEvent&&(a.pathfinderRemoveRenderEvent(),delete a.pathfinderRemoveRenderEvent)};!1===a.options.animation?d():a.pathfinderRemoveRenderEvent=u(a,"afterAnimate",d)}):this.connections.forEach(function(a){a.render()})};a.prototype.getChartObstacles=function(a){for(var d=[],f=this.chart.series,b=e(a.algorithmMargin,0),g,h=0,r=f.length;h<r;++h)if(f[h].visible&&!f[h].options.isInternal)for(var n=
0,l=f[h].points.length,k;n<l;++n)k=f[h].points[n],k.visible&&(k=B(k))&&d.push({xMin:k.xMin-b,xMax:k.xMax+b,yMin:k.yMin-b,yMax:k.yMax+b});d=d.sort(function(a,d){return a.xMin-d.xMin});z(a.algorithmMargin)||(g=a.algorithmMargin=c(d),d.forEach(function(a){a.xMin-=g;a.xMax+=g;a.yMin-=g;a.yMax+=g}));return d};a.prototype.getObstacleMetrics=function(a){for(var d=0,c=0,b,g,e=a.length;e--;)b=a[e].xMax-a[e].xMin,g=a[e].yMax-a[e].yMin,d<b&&(d=b),c<g&&(c=g);return{maxHeight:c,maxWidth:d}};a.prototype.getAlgorithmStartDirection=
function(a){var d="top"!==a.verticalAlign&&"bottom"!==a.verticalAlign;return"left"!==a.align&&"right"!==a.align?d?void 0:!1:d?!0:void 0};return a}();g.prototype.algorithms=D;x.Pathfinder=g;t(v.prototype,{getPathfinderAnchorPoint:function(a){var d=B(this);switch(a.align){case "right":var c="xMax";break;case "left":c="xMin"}switch(a.verticalAlign){case "top":var f="yMin";break;case "bottom":f="yMax"}return{x:c?d[c]:(d.xMin+d.xMax)/2,y:f?d[f]:(d.yMin+d.yMax)/2}},getRadiansToVector:function(a,c){var d;
z(c)||(d=B(this))&&(c={x:(d.xMin+d.xMax)/2,y:(d.yMin+d.yMax)/2});return Math.atan2(c.y-a.y,a.x-c.x)},getMarkerVector:function(a,c,b){var d=2*Math.PI,g=B(this),e=g.xMax-g.xMin,m=g.yMax-g.yMin,h=Math.atan2(m,e),r=!1;e/=2;var n=m/2,k=g.xMin+e;g=g.yMin+n;for(var E=k,l=g,p={},u=1,t=1;a<-Math.PI;)a+=d;for(;a>Math.PI;)a-=d;d=Math.tan(a);a>-h&&a<=h?(t=-1,r=!0):a>h&&a<=Math.PI-h?t=-1:a>Math.PI-h||a<=-(Math.PI-h)?(u=-1,r=!0):u=-1;r?(E+=u*e,l+=t*e*d):(E+=m/(2*d)*u,l+=t*n);b.x!==k&&(E=b.x);b.y!==g&&(l=b.y);p.x=
E+c*Math.cos(a);p.y=l-c*Math.sin(a);return p}});w.prototype.callbacks.push(function(a){!1!==a.options.connectors.enabled&&(l(a),this.pathfinder=new g(this),this.pathfinder.update(!0))});return g});H(b,"Series/XRangeSeries.js",[b["Core/Axis/Axis.js"],b["Core/Series/Series.js"],b["Core/Globals.js"],b["Core/Color/Color.js"],b["Core/Series/Point.js"],b["Core/Utilities.js"]],function(b,w,x,y,v,q){var D=y.parse;y=q.addEvent;var B=q.clamp,c=q.correctFloat,l=q.defined,u=q.find,z=q.isNumber,p=q.isObject,t=
q.merge,C=q.pick,e=x.Series,n=w.seriesTypes,h=n.column;w.seriesType("xrange","column",{colorByPoint:!0,dataLabels:{formatter:function(){var a=this.point.partialFill;p(a)&&(a=a.amount);if(z(a)&&0<a)return c(100*a)+"%"},inside:!0,verticalAlign:"middle"},tooltip:{headerFormat:'<span style="font-size: 10px">{point.x} - {point.x2}</span><br/>',pointFormat:'<span style="color:{point.color}">\u25cf</span> {series.name}: <b>{point.yCategory}</b><br/>'},borderRadius:3,pointRange:0},{type:"xrange",parallelArrays:["x",
"x2","y"],requireSorting:!1,animate:n.line.prototype.animate,cropShoulder:1,getExtremesFromAll:!0,autoIncrement:x.noop,buildKDTree:x.noop,init:function(){n.column.prototype.init.apply(this,arguments);this.options.stacking=void 0},getColumnMetrics:function(){function a(){c.series.forEach(function(a){var d=a.xAxis;a.xAxis=a.yAxis;a.yAxis=d})}var c=this.chart;a();var d=h.prototype.getColumnMetrics.call(this);a();return d},cropData:function(a,c,d,b){c=e.prototype.cropData.call(this,this.x2Data,c,d,b);
c.xData=a.slice(c.start,c.end);return c},findPointIndex:function(a){var c=this.cropped,d=this.cropStart,b=this.points,e=a.id;if(e)var f=(f=u(b,function(a){return a.id===e}))?f.index:void 0;"undefined"===typeof f&&(f=(f=u(b,function(d){return d.x===a.x&&d.x2===a.x2&&!d.touched}))?f.index:void 0);c&&z(f)&&z(d)&&f>=d&&(f-=d);return f},translatePoint:function(a){var c=this.xAxis,d=this.yAxis,b=this.columnMetrics,e=this.options,f=e.minPointLength||0,h=a.plotX,n=C(a.x2,a.x+(a.len||0)),A=c.translate(n,0,
0,0,1);n=Math.abs(A-h);var u=this.chart.inverted,q=C(e.borderWidth,1)%2/2,J=b.offset,k=Math.round(b.width);f&&(f-=n,0>f&&(f=0),h-=f/2,A+=f/2);h=Math.max(h,-10);A=B(A,-10,c.len+10);l(a.options.pointWidth)&&(J-=(Math.ceil(a.options.pointWidth)-k)/2,k=Math.ceil(a.options.pointWidth));e.pointPlacement&&z(a.plotY)&&d.categories&&(a.plotY=d.translate(a.y,0,1,0,1,e.pointPlacement));a.shapeArgs={x:Math.floor(Math.min(h,A))+q,y:Math.floor(a.plotY+J)+q,width:Math.round(Math.abs(A-h)),height:k,r:this.options.borderRadius};
e=a.shapeArgs.x;f=e+a.shapeArgs.width;0>e||f>c.len?(e=B(e,0,c.len),f=B(f,0,c.len),A=f-e,a.dlBox=t(a.shapeArgs,{x:e,width:f-e,centerX:A?A/2:null})):a.dlBox=null;e=a.tooltipPos;f=u?1:0;A=u?0:1;b=this.columnMetrics?this.columnMetrics.offset:-b.width/2;e[f]=B(e[f]+n/2*(c.reversed?-1:1)*(u?-1:1),0,c.len-1);e[A]=B(e[A]+(u?-1:1)*b,0,d.len-1);if(b=a.partialFill)p(b)&&(b=b.amount),z(b)||(b=0),d=a.shapeArgs,a.partShapeArgs={x:d.x,y:d.y,width:d.width,height:d.height,r:this.options.borderRadius},h=Math.max(Math.round(n*
b+a.plotX-h),0),a.clipRectArgs={x:c.reversed?d.x+n-h:d.x,y:d.y,width:h,height:d.height}},translate:function(){h.prototype.translate.apply(this,arguments);this.points.forEach(function(a){this.translatePoint(a)},this)},drawPoint:function(a,c){var d=this.options,b=this.chart.renderer,e=a.graphic,f=a.shapeType,g=a.shapeArgs,h=a.partShapeArgs,n=a.clipRectArgs,l=a.partialFill,u=d.stacking&&!d.borderRadius,J=a.state,k=d.states[J||"normal"]||{},E="undefined"===typeof J?"attr":c;J=this.pointAttribs(a,J);k=
C(this.chart.options.chart.animation,k.animation);if(a.isNull||!1===a.visible)e&&(a.graphic=e.destroy());else{if(e)e.rect[c](g);else a.graphic=e=b.g("point").addClass(a.getClassName()).add(a.group||this.group),e.rect=b[f](t(g)).addClass(a.getClassName()).addClass("highcharts-partfill-original").add(e);h&&(e.partRect?(e.partRect[c](t(h)),e.partialClipRect[c](t(n))):(e.partialClipRect=b.clipRect(n.x,n.y,n.width,n.height),e.partRect=b[f](h).addClass("highcharts-partfill-overlay").add(e).clip(e.partialClipRect)));
this.chart.styledMode||(e.rect[c](J,k).shadow(d.shadow,null,u),h&&(p(l)||(l={}),p(d.partialFill)&&(l=t(l,d.partialFill)),a=l.fill||D(J.fill).brighten(-.3).get()||D(a.color||this.color).brighten(-.3).get(),J.fill=a,e.partRect[E](J,k).shadow(d.shadow,null,u)))}},drawPoints:function(){var a=this,c=a.getAnimationVerb();a.points.forEach(function(d){a.drawPoint(d,c)})},getAnimationVerb:function(){return this.chart.pointCount<(this.options.animationLimit||250)?"animate":"attr"}},{resolveColor:function(){var a=
this.series;if(a.options.colorByPoint&&!this.options.color){var c=a.options.colors||a.chart.options.colors;var d=this.y%(c?c.length:a.chart.options.chart.colorCount);c=c&&c[d];a.chart.styledMode||(this.color=c);this.options.colorIndex||(this.colorIndex=d)}else this.color||(this.color=a.color)},init:function(){v.prototype.init.apply(this,arguments);this.y||(this.y=0);return this},setState:function(){v.prototype.setState.apply(this,arguments);this.series.drawPoint(this,this.series.getAnimationVerb())},
getLabelConfig:function(){var a=v.prototype.getLabelConfig.call(this),c=this.series.yAxis.categories;a.x2=this.x2;a.yCategory=this.yCategory=c&&c[this.y];return a},tooltipDateKeys:["x","x2"],isValid:function(){return"number"===typeof this.x&&"number"===typeof this.x2}});y(b,"afterGetSeriesExtremes",function(){var a=this.series,c;if(this.isXAxis){var d=C(this.dataMax,-Number.MAX_VALUE);a.forEach(function(a){a.x2Data&&a.x2Data.forEach(function(a){a>d&&(d=a,c=!0)})});c&&(this.dataMax=d)}});""});H(b,
"Series/GanttSeries.js",[b["Core/Series/Series.js"],b["Core/Globals.js"],b["Core/Options.js"],b["Core/Utilities.js"]],function(b,w,x,y){var v=y.isNumber;x=y.merge;var q=y.pick,D=y.splat,B=b.seriesTypes.xrange;b.seriesType("gantt","xrange",{grouping:!1,dataLabels:{enabled:!0},tooltip:{headerFormat:'<span style="font-size: 10px">{series.name}</span><br/>',pointFormat:null,pointFormatter:function(){var c=this.series,b=c.chart.tooltip,u=c.xAxis,z=c.tooltipOptions.dateTimeLabelFormats,p=u.options.startOfWeek,
t=c.tooltipOptions,q=t.xDateFormat,e=this.options.milestone,n="<b>"+(this.name||this.yCategory)+"</b>";if(t.pointFormat)return this.tooltipFormatter(t.pointFormat);q||(q=D(b.getDateFormat(u.closestPointRange,this.start,p,z))[0]);b=c.chart.time.dateFormat(q,this.start);c=c.chart.time.dateFormat(q,this.end);n+="<br/>";return e?n+(b+"<br/>"):n+("Start: "+b+"<br/>End: ")+(c+"<br/>")}},connectors:{type:"simpleConnect",animation:{reversed:!0},startMarker:{enabled:!0,symbol:"arrow-filled",radius:4,fill:"#fa0",
align:"left"},endMarker:{enabled:!1,align:"right"}}},{pointArrayMap:["start","end","y"],keyboardMoveVertical:!1,translatePoint:function(c){B.prototype.translatePoint.call(this,c);if(c.options.milestone){var b=c.shapeArgs;var u=b.height;c.shapeArgs={x:b.x-u/2,y:b.y,width:u,height:u}}},drawPoint:function(c,b){var l=this.options,z=this.chart.renderer,p=c.shapeArgs,t=c.plotY,q=c.graphic,e=c.selected&&"select",n=l.stacking&&!l.borderRadius;if(c.options.milestone)if(v(t)&&null!==c.y&&!1!==c.visible){p=
z.symbols.diamond(p.x,p.y,p.width,p.height);if(q)q[b]({d:p});else c.graphic=z.path(p).addClass(c.getClassName(),!0).add(c.group||this.group);this.chart.styledMode||c.graphic.attr(this.pointAttribs(c,e)).shadow(l.shadow,null,n)}else q&&(c.graphic=q.destroy());else B.prototype.drawPoint.call(this,c,b)},setData:w.Series.prototype.setData,setGanttPointAliases:function(c){function b(b,l){"undefined"!==typeof l&&(c[b]=l)}b("x",q(c.start,c.x));b("x2",q(c.end,c.x2));b("partialFill",q(c.completed,c.partialFill))}},
x(B.prototype.pointClass.prototype,{applyOptions:function(c,b){c=B.prototype.pointClass.prototype.applyOptions.call(this,c,b);w.seriesTypes.gantt.prototype.setGanttPointAliases(c);return c},isValid:function(){return("number"===typeof this.start||"number"===typeof this.x)&&("number"===typeof this.end||"number"===typeof this.x2||this.milestone)}}));""});H(b,"Core/Chart/GanttChart.js",[b["Core/Chart/Chart.js"],b["Core/Globals.js"],b["Core/Utilities.js"]],function(b,w,x){var y=x.getOptions,v=x.isArray,
q=x.merge,D=x.splat;w.ganttChart=function(x,c,l){var u="string"===typeof x||x.nodeName,z=c.series,p=y(),t,w=c;c=arguments[u?1:0];v(c.xAxis)||(c.xAxis=[c.xAxis||{},{}]);c.xAxis=c.xAxis.map(function(c,b){1===b&&(t=0);return q(p.xAxis,{grid:{enabled:!0},opposite:!0,linkedTo:t},c,{type:"datetime"})});c.yAxis=D(c.yAxis||{}).map(function(c){return q(p.yAxis,{grid:{enabled:!0},staticScale:50,reversed:!0,type:c.categories?c.type:"treegrid"},c)});c.series=null;c=q(!0,{chart:{type:"gantt"},title:{text:null},
legend:{enabled:!1},navigator:{series:{type:"gantt"}}},c,{isGantt:!0});c.series=w.series=z;return u?new b(x,c,l):new b(c,c)}});H(b,"Core/Axis/ScrollbarAxis.js",[b["Core/Globals.js"],b["Core/Utilities.js"]],function(b,w){var x=w.addEvent,y=w.defined,v=w.pick;return function(){function q(){}q.compose=function(q,w){x(q,"afterInit",function(){var c=this;c.options&&c.options.scrollbar&&c.options.scrollbar.enabled&&(c.options.scrollbar.vertical=!c.horiz,c.options.startOnTick=c.options.endOnTick=!1,c.scrollbar=
new w(c.chart.renderer,c.options.scrollbar,c.chart),x(c.scrollbar,"changed",function(l){var u=v(c.options&&c.options.min,c.min),q=v(c.options&&c.options.max,c.max),p=y(c.dataMin)?Math.min(u,c.min,c.dataMin):u,t=(y(c.dataMax)?Math.max(q,c.max,c.dataMax):q)-p;y(u)&&y(q)&&(c.horiz&&!c.reversed||!c.horiz&&c.reversed?(u=p+t*this.to,p+=t*this.from):(u=p+t*(1-this.from),p+=t*(1-this.to)),v(this.options.liveRedraw,b.svg&&!b.isTouchDevice&&!this.chart.isBoosting)||"mouseup"===l.DOMType||!y(l.DOMType)?c.setExtremes(p,
u,!0,"mousemove"!==l.DOMType,l):this.setRange(this.from,this.to))}))});x(q,"afterRender",function(){var c=Math.min(v(this.options.min,this.min),this.min,v(this.dataMin,this.min)),b=Math.max(v(this.options.max,this.max),this.max,v(this.dataMax,this.max)),u=this.scrollbar,q=this.axisTitleMargin+(this.titleOffset||0),p=this.chart.scrollbarsOffsets,t=this.options.margin||0;u&&(this.horiz?(this.opposite||(p[1]+=q),u.position(this.left,this.top+this.height+2+p[1]-(this.opposite?t:0),this.width,this.height),
this.opposite||(p[1]+=t),q=1):(this.opposite&&(p[0]+=q),u.position(this.left+this.width+2+p[0]-(this.opposite?0:t),this.top,this.width,this.height),this.opposite&&(p[0]+=t),q=0),p[q]+=u.size+u.options.margin,isNaN(c)||isNaN(b)||!y(this.min)||!y(this.max)||this.min===this.max?u.setRange(0,1):(p=(this.min-c)/(b-c),c=(this.max-c)/(b-c),this.horiz&&!this.reversed||!this.horiz&&this.reversed?u.setRange(p,c):u.setRange(1-c,1-p)))});x(q,"afterGetOffset",function(){var c=this.horiz?2:1,b=this.scrollbar;b&&
(this.chart.scrollbarsOffsets=[0,0],this.chart.axisOffset[c]+=b.size+b.options.margin)})};return q}()});H(b,"Core/Scrollbar.js",[b["Core/Axis/Axis.js"],b["Core/Globals.js"],b["Core/Axis/ScrollbarAxis.js"],b["Core/Utilities.js"],b["Core/Options.js"]],function(b,w,x,y,v){var q=y.addEvent,D=y.correctFloat,B=y.defined,c=y.destroyObjectProperties,l=y.fireEvent,u=y.merge,z=y.pick,p=y.removeEvent;y=v.defaultOptions;var t=w.hasTouch,C=w.isTouchDevice,e=w.swapXY=function(c,b){b&&c.forEach(function(a){for(var c=
a.length,d,b=0;b<c;b+=2)d=a[b+1],"number"===typeof d&&(a[b+1]=a[b+2],a[b+2]=d)});return c};v=function(){function b(b,a,c){this._events=[];this.from=this.chartY=this.chartX=0;this.scrollbar=this.group=void 0;this.scrollbarButtons=[];this.scrollbarGroup=void 0;this.scrollbarLeft=0;this.scrollbarRifles=void 0;this.scrollbarStrokeWidth=1;this.to=this.size=this.scrollbarTop=0;this.track=void 0;this.trackBorderWidth=1;this.userOptions={};this.y=this.x=0;this.chart=c;this.options=a;this.renderer=c.renderer;
this.init(b,a,c)}b.prototype.addEvents=function(){var b=this.options.inverted?[1,0]:[0,1],a=this.scrollbarButtons,c=this.scrollbarGroup.element,d=this.track.element,e=this.mouseDownHandler.bind(this),m=this.mouseMoveHandler.bind(this),f=this.mouseUpHandler.bind(this);b=[[a[b[0]].element,"click",this.buttonToMinClick.bind(this)],[a[b[1]].element,"click",this.buttonToMaxClick.bind(this)],[d,"click",this.trackClick.bind(this)],[c,"mousedown",e],[c.ownerDocument,"mousemove",m],[c.ownerDocument,"mouseup",
f]];t&&b.push([c,"touchstart",e],[c.ownerDocument,"touchmove",m],[c.ownerDocument,"touchend",f]);b.forEach(function(a){q.apply(null,a)});this._events=b};b.prototype.buttonToMaxClick=function(b){var a=(this.to-this.from)*z(this.options.step,.2);this.updatePosition(this.from+a,this.to+a);l(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:b})};b.prototype.buttonToMinClick=function(b){var a=D(this.to-this.from)*z(this.options.step,.2);this.updatePosition(D(this.from-a),D(this.to-
a));l(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:b})};b.prototype.cursorToScrollbarPosition=function(b){var a=this.options;a=a.minWidth>this.calculatedWidth?a.minWidth:0;return{chartX:(b.chartX-this.x-this.xOffset)/(this.barWidth-a),chartY:(b.chartY-this.y-this.yOffset)/(this.barWidth-a)}};b.prototype.destroy=function(){var b=this.chart.scroller;this.removeEvents();["track","scrollbarRifles","scrollbar","scrollbarGroup","group"].forEach(function(a){this[a]&&this[a].destroy&&
(this[a]=this[a].destroy())},this);b&&this===b.scrollbar&&(b.scrollbar=null,c(b.scrollbarButtons))};b.prototype.drawScrollbarButton=function(b){var a=this.renderer,c=this.scrollbarButtons,d=this.options,h=this.size;var m=a.g().add(this.group);c.push(m);m=a.rect().addClass("highcharts-scrollbar-button").add(m);this.chart.styledMode||m.attr({stroke:d.buttonBorderColor,"stroke-width":d.buttonBorderWidth,fill:d.buttonBackgroundColor});m.attr(m.crisp({x:-.5,y:-.5,width:h+1,height:h+1,r:d.buttonBorderRadius},
m.strokeWidth()));m=a.path(e([["M",h/2+(b?-1:1),h/2-3],["L",h/2+(b?-1:1),h/2+3],["L",h/2+(b?2:-2),h/2]],d.vertical)).addClass("highcharts-scrollbar-arrow").add(c[b]);this.chart.styledMode||m.attr({fill:d.buttonArrowColor})};b.prototype.init=function(c,a,e){this.scrollbarButtons=[];this.renderer=c;this.userOptions=a;this.options=u(b.defaultOptions,a);this.chart=e;this.size=z(this.options.size,this.options.height);a.enabled&&(this.render(),this.addEvents())};b.prototype.mouseDownHandler=function(b){b=
this.chart.pointer.normalize(b);b=this.cursorToScrollbarPosition(b);this.chartX=b.chartX;this.chartY=b.chartY;this.initPositions=[this.from,this.to];this.grabbedCenter=!0};b.prototype.mouseMoveHandler=function(b){var a=this.chart.pointer.normalize(b),c=this.options.vertical?"chartY":"chartX",d=this.initPositions||[];!this.grabbedCenter||b.touches&&0===b.touches[0][c]||(a=this.cursorToScrollbarPosition(a)[c],c=this[c],c=a-c,this.hasDragged=!0,this.updatePosition(d[0]+c,d[1]+c),this.hasDragged&&l(this,
"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMType:b.type,DOMEvent:b}))};b.prototype.mouseUpHandler=function(b){this.hasDragged&&l(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMType:b.type,DOMEvent:b});this.grabbedCenter=this.hasDragged=this.chartX=this.chartY=null};b.prototype.position=function(b,a,c,d){var e=this.options.vertical,g=0,f=this.rendered?"animate":"attr";this.x=b;this.y=a+this.trackBorderWidth;this.width=c;this.xOffset=this.height=d;this.yOffset=g;e?
(this.width=this.yOffset=c=g=this.size,this.xOffset=a=0,this.barWidth=d-2*c,this.x=b+=this.options.margin):(this.height=this.xOffset=d=a=this.size,this.barWidth=c-2*d,this.y+=this.options.margin);this.group[f]({translateX:b,translateY:this.y});this.track[f]({width:c,height:d});this.scrollbarButtons[1][f]({translateX:e?0:c-a,translateY:e?d-g:0})};b.prototype.removeEvents=function(){this._events.forEach(function(b){p.apply(null,b)});this._events.length=0};b.prototype.render=function(){var b=this.renderer,
a=this.options,c=this.size,d=this.chart.styledMode,n;this.group=n=b.g("scrollbar").attr({zIndex:a.zIndex,translateY:-99999}).add();this.track=b.rect().addClass("highcharts-scrollbar-track").attr({x:0,r:a.trackBorderRadius||0,height:c,width:c}).add(n);d||this.track.attr({fill:a.trackBackgroundColor,stroke:a.trackBorderColor,"stroke-width":a.trackBorderWidth});this.trackBorderWidth=this.track.strokeWidth();this.track.attr({y:-this.trackBorderWidth%2/2});this.scrollbarGroup=b.g().add(n);this.scrollbar=
b.rect().addClass("highcharts-scrollbar-thumb").attr({height:c,width:c,r:a.barBorderRadius||0}).add(this.scrollbarGroup);this.scrollbarRifles=b.path(e([["M",-3,c/4],["L",-3,2*c/3],["M",0,c/4],["L",0,2*c/3],["M",3,c/4],["L",3,2*c/3]],a.vertical)).addClass("highcharts-scrollbar-rifles").add(this.scrollbarGroup);d||(this.scrollbar.attr({fill:a.barBackgroundColor,stroke:a.barBorderColor,"stroke-width":a.barBorderWidth}),this.scrollbarRifles.attr({stroke:a.rifleColor,"stroke-width":1}));this.scrollbarStrokeWidth=
this.scrollbar.strokeWidth();this.scrollbarGroup.translate(-this.scrollbarStrokeWidth%2/2,-this.scrollbarStrokeWidth%2/2);this.drawScrollbarButton(0);this.drawScrollbarButton(1)};b.prototype.setRange=function(b,a){var c=this.options,d=c.vertical,e=c.minWidth,m=this.barWidth,f,h=!this.rendered||this.hasDragged||this.chart.navigator&&this.chart.navigator.hasDragged?"attr":"animate";if(B(m)){b=Math.max(b,0);var n=Math.ceil(m*b);this.calculatedWidth=f=D(m*Math.min(a,1)-n);f<e&&(n=(m-e+f)*b,f=e);e=Math.floor(n+
this.xOffset+this.yOffset);m=f/2-.5;this.from=b;this.to=a;d?(this.scrollbarGroup[h]({translateY:e}),this.scrollbar[h]({height:f}),this.scrollbarRifles[h]({translateY:m}),this.scrollbarTop=e,this.scrollbarLeft=0):(this.scrollbarGroup[h]({translateX:e}),this.scrollbar[h]({width:f}),this.scrollbarRifles[h]({translateX:m}),this.scrollbarLeft=e,this.scrollbarTop=0);12>=f?this.scrollbarRifles.hide():this.scrollbarRifles.show(!0);!1===c.showFull&&(0>=b&&1<=a?this.group.hide():this.group.show());this.rendered=
!0}};b.prototype.trackClick=function(b){var a=this.chart.pointer.normalize(b),c=this.to-this.from,d=this.y+this.scrollbarTop,e=this.x+this.scrollbarLeft;this.options.vertical&&a.chartY>d||!this.options.vertical&&a.chartX>e?this.updatePosition(this.from+c,this.to+c):this.updatePosition(this.from-c,this.to-c);l(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:b})};b.prototype.update=function(b){this.destroy();this.init(this.chart.renderer,u(!0,this.options,b),this.chart)};b.prototype.updatePosition=
function(b,a){1<a&&(b=D(1-D(a-b)),a=1);0>b&&(a=D(a-b),b=0);this.from=b;this.to=a};b.defaultOptions={height:C?20:14,barBorderRadius:0,buttonBorderRadius:0,liveRedraw:void 0,margin:10,minWidth:6,step:.2,zIndex:3,barBackgroundColor:"#cccccc",barBorderWidth:1,barBorderColor:"#cccccc",buttonArrowColor:"#333333",buttonBackgroundColor:"#e6e6e6",buttonBorderColor:"#cccccc",buttonBorderWidth:1,rifleColor:"#333333",trackBackgroundColor:"#f2f2f2",trackBorderColor:"#f2f2f2",trackBorderWidth:1};return b}();w.Scrollbar||
(y.scrollbar=u(!0,v.defaultOptions,y.scrollbar),w.Scrollbar=v,x.compose(b,v));return w.Scrollbar});H(b,"Extensions/RangeSelector.js",[b["Core/Axis/Axis.js"],b["Core/Chart/Chart.js"],b["Core/Globals.js"],b["Core/Options.js"],b["Core/Renderer/SVG/SVGElement.js"],b["Core/Utilities.js"]],function(b,w,x,y,v,q){var D=y.defaultOptions,B=q.addEvent,c=q.createElement,l=q.css,u=q.defined,z=q.destroyObjectProperties,p=q.discardElement,t=q.extend,C=q.fireEvent,e=q.isNumber,n=q.merge,h=q.objectEach,a=q.pick,g=
q.pInt,d=q.splat;t(D,{rangeSelector:{verticalAlign:"top",buttonTheme:{width:28,height:18,padding:2,zIndex:7},floating:!1,x:0,y:0,height:void 0,inputPosition:{align:"right",x:0,y:0},buttonPosition:{align:"left",x:0,y:0},labelStyle:{color:"#666666"}}});D.lang=n(D.lang,{rangeSelectorZoom:"Zoom",rangeSelectorFrom:"From",rangeSelectorTo:"To"});var r=function(){function m(a){this.buttons=void 0;this.buttonOptions=m.prototype.defaultButtons;this.options=void 0;this.chart=a;this.init(a)}m.prototype.clickButton=
function(c,g){var f=this.chart,m=this.buttonOptions[c],h=f.xAxis[0],n=f.scroller&&f.scroller.getUnionExtremes()||h||{},l=n.dataMin,k=n.dataMax,E=h&&Math.round(Math.min(h.max,a(k,h.max))),F=m.type;n=m._range;var p,r=m.dataGrouping;if(null!==l&&null!==k){f.fixedRange=n;r&&(this.forcedDataGrouping=!0,b.prototype.setDataGrouping.call(h||{chart:this.chart},r,!1),this.frozenStates=m.preserveDataGrouping);if("month"===F||"year"===F)if(h){F={range:m,max:E,chart:f,dataMin:l,dataMax:k};var t=h.minFromRange.call(F);
e(F.newMax)&&(E=F.newMax)}else n=m;else if(n)t=Math.max(E-n,l),E=Math.min(t+n,k);else if("ytd"===F)if(h)"undefined"===typeof k&&(l=Number.MAX_VALUE,k=Number.MIN_VALUE,f.series.forEach(function(a){a=a.xData;l=Math.min(a[0],l);k=Math.max(a[a.length-1],k)}),g=!1),E=this.getYTDExtremes(k,l,f.time.useUTC),t=p=E.min,E=E.max;else{this.deferredYTDClick=c;return}else"all"===F&&h&&(t=l,E=k);u(t)&&(t+=m._offsetMin);u(E)&&(E+=m._offsetMax);this.setSelected(c);if(h)h.setExtremes(t,E,a(g,1),null,{trigger:"rangeSelectorButton",
rangeSelectorButton:m});else{var q=d(f.options.xAxis)[0];var R=q.range;q.range=n;var G=q.min;q.min=p;B(f,"load",function(){q.range=R;q.min=G})}}};m.prototype.setSelected=function(a){this.selected=this.options.selected=a};m.prototype.init=function(a){var b=this,c=a.options.rangeSelector,d=c.buttons||b.defaultButtons.slice(),e=c.selected,f=function(){var a=b.minInput,c=b.maxInput;a&&a.blur&&C(a,"blur");c&&c.blur&&C(c,"blur")};b.chart=a;b.options=c;b.buttons=[];b.buttonOptions=d;this.unMouseDown=B(a.container,
"mousedown",f);this.unResize=B(a,"resize",f);d.forEach(b.computeButtonRange);"undefined"!==typeof e&&d[e]&&this.clickButton(e,!1);B(a,"load",function(){a.xAxis&&a.xAxis[0]&&B(a.xAxis[0],"setExtremes",function(c){this.max-this.min!==a.fixedRange&&"rangeSelectorButton"!==c.trigger&&"updatedData"!==c.trigger&&b.forcedDataGrouping&&!b.frozenStates&&this.setDataGrouping(!1,!1)})})};m.prototype.updateButtonStates=function(){var a=this,b=this.chart,c=b.xAxis[0],d=Math.round(c.max-c.min),g=!c.hasVisibleSeries,
m=b.scroller&&b.scroller.getUnionExtremes()||c,h=m.dataMin,k=m.dataMax;b=a.getYTDExtremes(k,h,b.time.useUTC);var E=b.min,n=b.max,l=a.selected,p=e(l),r=a.options.allButtonsEnabled,u=a.buttons;a.buttonOptions.forEach(function(b,e){var f=b._range,m=b.type,F=b.count||1,A=u[e],t=0,q=b._offsetMax-b._offsetMin;b=e===l;var I=f>k-h,J=f<c.minRange,P=!1,R=!1;f=f===d;("month"===m||"year"===m)&&d+36E5>=864E5*{month:28,year:365}[m]*F-q&&d-36E5<=864E5*{month:31,year:366}[m]*F+q?f=!0:"ytd"===m?(f=n-E+q===d,P=!b):
"all"===m&&(f=c.max-c.min>=k-h,R=!b&&p&&f);m=!r&&(I||J||R||g);F=b&&f||f&&!p&&!P||b&&a.frozenStates;m?t=3:F&&(p=!0,t=2);A.state!==t&&(A.setState(t),0===t&&l===e&&a.setSelected(null))})};m.prototype.computeButtonRange=function(b){var c=b.type,d=b.count||1,e={millisecond:1,second:1E3,minute:6E4,hour:36E5,day:864E5,week:6048E5};if(e[c])b._range=e[c]*d;else if("month"===c||"year"===c)b._range=864E5*{month:30,year:365}[c]*d;b._offsetMin=a(b.offsetMin,0);b._offsetMax=a(b.offsetMax,0);b._range+=b._offsetMax-
b._offsetMin};m.prototype.setInputValue=function(a,b){var c=this.chart.options.rangeSelector,d=this.chart.time,e=this[a+"Input"];u(b)&&(e.previousValue=e.HCTime,e.HCTime=b);e.value=d.dateFormat(c.inputEditDateFormat||"%Y-%m-%d",e.HCTime);this[a+"DateBox"].attr({text:d.dateFormat(c.inputDateFormat||"%b %e, %Y",e.HCTime)})};m.prototype.showInput=function(a){var b=this.inputGroup,c=this[a+"DateBox"];l(this[a+"Input"],{left:b.translateX+c.x+"px",top:b.translateY+"px",width:c.width-2+"px",height:c.height-
2+"px",border:"2px solid silver"})};m.prototype.hideInput=function(a){l(this[a+"Input"],{border:0,width:"1px",height:"1px"});this.setInputValue(a)};m.prototype.defaultInputDateParser=function(a,b){var c=new Date;return x.isSafari?Date.parse(a.split(" ").join("T")):b?Date.parse(a+"Z"):Date.parse(a)-6E4*c.getTimezoneOffset()};m.prototype.drawInput=function(a){function b(){var a=F.value,b=f.xAxis[0];var c=f.scroller&&f.scroller.xAxis?f.scroller.xAxis:b;var k=c.dataMin,m=c.dataMax;c=(p.inputDateParser||
q)(a,f.time.useUTC);c!==F.previousValue&&(F.previousValue=c,e(c)||(c=a.split("-"),c=Date.UTC(g(c[0]),g(c[1])-1,g(c[2]))),e(c)&&(f.time.useUTC||(c+=6E4*(new Date).getTimezoneOffset()),E?c>d.maxInput.HCTime?c=void 0:c<k&&(c=k):c<d.minInput.HCTime?c=void 0:c>m&&(c=m),"undefined"!==typeof c&&b.setExtremes(E?c:b.min,E?b.max:c,void 0,void 0,{trigger:"rangeSelectorInput"})))}var d=this,f=d.chart,m=f.renderer.style||{},h=f.renderer,p=f.options.rangeSelector,k=d.div,E="min"===a,F,r,u=this.inputGroup,q=this.defaultInputDateParser;
this[a+"Label"]=r=h.label(D.lang[E?"rangeSelectorFrom":"rangeSelectorTo"],this.inputGroup.offset).addClass("highcharts-range-label").attr({padding:2}).add(u);u.offset+=r.width+5;this[a+"DateBox"]=h=h.label("",u.offset).addClass("highcharts-range-input").attr({padding:2,width:p.inputBoxWidth||90,height:p.inputBoxHeight||17,"text-align":"center"}).on("click",function(){d.showInput(a);d[a+"Input"].focus()});f.styledMode||h.attr({stroke:p.inputBoxBorderColor||"#cccccc","stroke-width":1});h.add(u);u.offset+=
h.width+(E?10:0);this[a+"Input"]=F=c("input",{name:a,className:"highcharts-range-selector",type:"text"},{top:f.plotTop+"px"},k);f.styledMode||(r.css(n(m,p.labelStyle)),h.css(n({color:"#333333"},m,p.inputStyle)),l(F,t({position:"absolute",border:0,width:"1px",height:"1px",padding:0,textAlign:"center",fontSize:m.fontSize,fontFamily:m.fontFamily,top:"-9999em"},p.inputStyle)));F.onfocus=function(){d.showInput(a)};F.onblur=function(){F===x.doc.activeElement&&b();d.hideInput(a);F.blur()};F.onchange=b;F.onkeypress=
function(a){13===a.keyCode&&b()}};m.prototype.getPosition=function(){var a=this.chart,b=a.options.rangeSelector;a="top"===b.verticalAlign?a.plotTop-a.axisOffset[0]:0;return{buttonTop:a+b.buttonPosition.y,inputTop:a+b.inputPosition.y-10}};m.prototype.getYTDExtremes=function(a,b,c){var d=this.chart.time,e=new d.Date(a),f=d.get("FullYear",e);c=c?d.Date.UTC(f,0,1):+new d.Date(f,0,1);b=Math.max(b||0,c);e=e.getTime();return{max:Math.min(a||e,e),min:b}};m.prototype.render=function(b,d){var e=this,f=e.chart,
m=f.renderer,g=f.container,h=f.options,k=h.exporting&&!1!==h.exporting.enabled&&h.navigation&&h.navigation.buttonOptions,E=D.lang,n=e.div,l=h.rangeSelector,p=a(h.chart.style&&h.chart.style.zIndex,0)+1;h=l.floating;var r=e.buttons;n=e.inputGroup;var u=l.buttonTheme,t=l.buttonPosition,q=l.inputPosition,z=l.inputEnabled,x=u&&u.states,v=f.plotLeft,w=e.buttonGroup,y,C=e.options.verticalAlign,B=f.legend,G=B&&B.options,H=t.y,O=q.y,Q=f.hasLoaded,S=Q?"animate":"attr",N=0,L=0;if(!1!==l.enabled){e.rendered||
(e.group=y=m.g("range-selector-group").attr({zIndex:7}).add(),e.buttonGroup=w=m.g("range-selector-buttons").add(y),e.zoomText=m.text(E.rangeSelectorZoom,0,15).add(w),f.styledMode||(e.zoomText.css(l.labelStyle),u["stroke-width"]=a(u["stroke-width"],0)),e.buttonOptions.forEach(function(a,b){r[b]=m.button(a.text,0,0,function(c){var d=a.events&&a.events.click,k;d&&(k=d.call(a,c));!1!==k&&e.clickButton(b);e.isActive=!0},u,x&&x.hover,x&&x.select,x&&x.disabled).attr({"text-align":"center"}).add(w)}),!1!==
z&&(e.div=n=c("div",null,{position:"relative",height:0,zIndex:p}),g.parentNode.insertBefore(n,g),e.inputGroup=n=m.g("input-group").add(y),n.offset=0,e.drawInput("min"),e.drawInput("max")));e.zoomText[S]({x:a(v+t.x,v)});var T=a(v+t.x,v)+e.zoomText.getBBox().width+5;e.buttonOptions.forEach(function(b,c){r[c][S]({x:T});T+=r[c].width+a(l.buttonSpacing,5)});v=f.plotLeft-f.spacing[3];e.updateButtonStates();k&&this.titleCollision(f)&&"top"===C&&"right"===t.align&&t.y+w.getBBox().height-12<(k.y||0)+k.height&&
(N=-40);g=t.x-f.spacing[3];"right"===t.align?g+=N-v:"center"===t.align&&(g-=v/2);w.align({y:t.y,width:w.getBBox().width,align:t.align,x:g},!0,f.spacingBox);e.group.placed=Q;e.buttonGroup.placed=Q;!1!==z&&(N=k&&this.titleCollision(f)&&"top"===C&&"right"===q.align&&q.y-n.getBBox().height-12<(k.y||0)+k.height+f.spacing[0]?-40:0,"left"===q.align?g=v:"right"===q.align&&(g=-Math.max(f.axisOffset[1],-N)),n.align({y:q.y,width:n.getBBox().width,align:q.align,x:q.x+g-2},!0,f.spacingBox),k=n.alignAttr.translateX+
n.alignOptions.x-N+n.getBBox().x+2,g=n.alignOptions.width,E=w.alignAttr.translateX+w.getBBox().x,v=w.getBBox().width+20,(q.align===t.align||E+v>k&&k+g>E&&H<O+n.getBBox().height)&&n.attr({translateX:n.alignAttr.translateX+(f.axisOffset[1]>=-N?0:-N),translateY:n.alignAttr.translateY+w.getBBox().height+10}),e.setInputValue("min",b),e.setInputValue("max",d),e.inputGroup.placed=Q);e.group.align({verticalAlign:C},!0,f.spacingBox);b=e.group.getBBox().height+20;d=e.group.alignAttr.translateY;"bottom"===C&&
(B=G&&"bottom"===G.verticalAlign&&G.enabled&&!G.floating?B.legendHeight+a(G.margin,10):0,b=b+B-20,L=d-b-(h?0:l.y)-(f.titleOffset?f.titleOffset[2]:0)-10);if("top"===C)h&&(L=0),f.titleOffset&&f.titleOffset[0]&&(L=f.titleOffset[0]),L+=f.margin[0]-f.spacing[0]||0;else if("middle"===C)if(O===H)L=0>O?d+void 0:d;else if(O||H)L=0>O||0>H?L-Math.min(O,H):d-b+NaN;e.group.translate(l.x,l.y+Math.floor(L));!1!==z&&(e.minInput.style.marginTop=e.group.translateY+"px",e.maxInput.style.marginTop=e.group.translateY+
"px");e.rendered=!0}};m.prototype.getHeight=function(){var a=this.options,b=this.group,c=a.y,d=a.buttonPosition.y,e=a.inputPosition.y;if(a.height)return a.height;a=b?b.getBBox(!0).height+13+c:0;b=Math.min(e,d);if(0>e&&0>d||0<e&&0<d)a+=Math.abs(b);return a};m.prototype.titleCollision=function(a){return!(a.options.title.text||a.options.subtitle.text)};m.prototype.update=function(a){var b=this.chart;n(!0,b.options.rangeSelector,a);this.destroy();this.init(b);b.rangeSelector.render()};m.prototype.destroy=
function(){var a=this,b=a.minInput,c=a.maxInput;a.unMouseDown();a.unResize();z(a.buttons);b&&(b.onfocus=b.onblur=b.onchange=null);c&&(c.onfocus=c.onblur=c.onchange=null);h(a,function(b,c){b&&"chart"!==c&&(b instanceof v?b.destroy():b instanceof window.HTMLElement&&p(b));b!==m.prototype[c]&&(a[c]=null)},this)};return m}();r.prototype.defaultButtons=[{type:"month",count:1,text:"1m"},{type:"month",count:3,text:"3m"},{type:"month",count:6,text:"6m"},{type:"ytd",text:"YTD"},{type:"year",count:1,text:"1y"},
{type:"all",text:"All"}];b.prototype.minFromRange=function(){var b=this.range,c=b.type,d=this.max,g=this.chart.time,h=function(a,b){var d="year"===c?"FullYear":"Month",e=new g.Date(a),k=g.get(d,e);g.set(d,e,k+b);k===g.get(d,e)&&g.set("Date",e,0);return e.getTime()-a};if(e(b)){var n=d-b;var l=b}else n=d+h(d,-b.count),this.chart&&(this.chart.fixedRange=d-n);var p=a(this.dataMin,Number.MIN_VALUE);e(n)||(n=p);n<=p&&(n=p,"undefined"===typeof l&&(l=h(n,b.count)),this.newMax=Math.min(n+l,this.dataMax));
e(d)||(n=void 0);return n};x.RangeSelector||(B(w,"afterGetContainer",function(){this.options.rangeSelector.enabled&&(this.rangeSelector=new r(this))}),B(w,"beforeRender",function(){var a=this.axes,b=this.rangeSelector;b&&(e(b.deferredYTDClick)&&(b.clickButton(b.deferredYTDClick),delete b.deferredYTDClick),a.forEach(function(a){a.updateNames();a.setScale()}),this.getAxisMargins(),b.render(),a=b.options.verticalAlign,b.options.floating||("bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=
!0)))}),B(w,"update",function(a){var b=a.options.rangeSelector;a=this.rangeSelector;var c=this.extraBottomMargin,d=this.extraTopMargin;b&&b.enabled&&!u(a)&&(this.options.rangeSelector.enabled=!0,this.rangeSelector=new r(this));this.extraTopMargin=this.extraBottomMargin=!1;a&&(a.render(),b=b&&b.verticalAlign||a.options&&a.options.verticalAlign,a.options.floating||("bottom"===b?this.extraBottomMargin=!0:"middle"!==b&&(this.extraTopMargin=!0)),this.extraBottomMargin!==c||this.extraTopMargin!==d)&&(this.isDirtyBox=
!0)}),B(w,"render",function(){var a=this.rangeSelector;a&&!a.options.floating&&(a.render(),a=a.options.verticalAlign,"bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0))}),B(w,"getMargins",function(){var a=this.rangeSelector;a&&(a=a.getHeight(),this.extraTopMargin&&(this.plotTop+=a),this.extraBottomMargin&&(this.marginBottom+=a))}),w.prototype.callbacks.push(function(a){function b(){c=a.xAxis[0].getExtremes();g=a.legend;m=null===d||void 0===d?void 0:d.options.verticalAlign;
e(c.min)&&d.render(c.min,c.max);d&&g.display&&"top"===m&&m===g.options.verticalAlign&&(h=n(a.spacingBox),h.y="vertical"===g.options.layout?a.plotTop:h.y+d.getHeight(),g.group.placed=!1,g.align(h))}var c,d=a.rangeSelector,g,h,m;if(d){var l=B(a.xAxis[0],"afterSetExtremes",function(a){d.render(a.min,a.max)});var k=B(a,"redraw",b);b()}B(a,"destroy",function(){d&&(k(),l())})}),x.RangeSelector=r);return x.RangeSelector});H(b,"Core/Axis/NavigatorAxis.js",[b["Core/Globals.js"],b["Core/Utilities.js"]],function(b,
w){var x=b.isTouchDevice,y=w.addEvent,v=w.correctFloat,q=w.defined,D=w.isNumber,B=w.pick,c=function(){function b(b){this.axis=b}b.prototype.destroy=function(){this.axis=void 0};b.prototype.toFixedRange=function(b,c,l,t){var p=this.axis,e=p.chart;e=e&&e.fixedRange;var n=(p.pointRange||0)/2;b=B(l,p.translate(b,!0,!p.horiz));c=B(t,p.translate(c,!0,!p.horiz));p=e&&(c-b)/e;q(l)||(b=v(b+n));q(t)||(c=v(c-n));.7<p&&1.3>p&&(t?b=c-e:c=b+e);D(b)&&D(c)||(b=c=void 0);return{min:b,max:c}};return b}();return function(){function b(){}
b.compose=function(b){b.keepProps.push("navigatorAxis");y(b,"init",function(){this.navigatorAxis||(this.navigatorAxis=new c(this))});y(b,"zoom",function(b){var c=this.chart.options,l=c.navigator,u=this.navigatorAxis,e=c.chart.pinchType,n=c.rangeSelector;c=c.chart.zoomType;this.isXAxis&&(l&&l.enabled||n&&n.enabled)&&("y"===c?b.zoomed=!1:(!x&&"xy"===c||x&&"xy"===e)&&this.options.range&&(l=u.previousZoom,q(b.newMin)?u.previousZoom=[this.min,this.max]:l&&(b.newMin=l[0],b.newMax=l[1],u.previousZoom=void 0)));
"undefined"!==typeof b.zoomed&&b.preventDefault()})};b.AdditionsClass=c;return b}()});H(b,"Core/Navigator.js",[b["Core/Axis/Axis.js"],b["Core/Series/Series.js"],b["Core/Chart/Chart.js"],b["Core/Color/Color.js"],b["Core/Globals.js"],b["Series/LineSeries.js"],b["Core/Axis/NavigatorAxis.js"],b["Core/Options.js"],b["Core/Scrollbar.js"],b["Core/Utilities.js"]],function(b,w,x,y,v,q,D,B,c,l){y=y.parse;var u=v.hasTouch,z=v.isTouchDevice,p=B.defaultOptions,t=l.addEvent,C=l.clamp,e=l.correctFloat,n=l.defined,
h=l.destroyObjectProperties,a=l.erase,g=l.extend,d=l.find,r=l.isArray,m=l.isNumber,f=l.merge,G=l.pick,I=l.removeEvent,A=l.splat,H=function(a){for(var b=[],c=1;c<arguments.length;c++)b[c-1]=arguments[c];b=[].filter.call(b,m);if(b.length)return Math[a].apply(0,b)};w="undefined"===typeof w.seriesTypes.areaspline?"line":"areaspline";g(p,{navigator:{height:40,margin:25,maskInside:!0,handles:{width:7,height:15,symbols:["navigator-handle","navigator-handle"],enabled:!0,lineWidth:1,backgroundColor:"#f2f2f2",
borderColor:"#999999"},maskFill:y("#6685c2").setOpacity(.3).get(),outlineColor:"#cccccc",outlineWidth:1,series:{type:w,fillOpacity:.05,lineWidth:1,compare:null,dataGrouping:{approximation:"average",enabled:!0,groupPixelWidth:2,smoothed:!0,units:[["millisecond",[1,2,5,10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1,2,3,4]],["week",[1,2,3]],["month",[1,3,6]],["year",null]]},dataLabels:{enabled:!1,zIndex:2},id:"highcharts-navigator-series",
className:"highcharts-navigator-series",lineColor:null,marker:{enabled:!1},threshold:null},xAxis:{overscroll:0,className:"highcharts-navigator-xaxis",tickLength:0,lineWidth:0,gridLineColor:"#e6e6e6",gridLineWidth:1,tickPixelInterval:200,labels:{align:"left",style:{color:"#999999"},x:3,y:-4},crosshair:!1},yAxis:{className:"highcharts-navigator-yaxis",gridLineWidth:0,startOnTick:!1,endOnTick:!1,minPadding:.1,maxPadding:.1,labels:{enabled:!1},crosshair:!1,title:{text:null},tickLength:0,tickWidth:0}}});
v.Renderer.prototype.symbols["navigator-handle"]=function(a,b,c,d,e){a=(e&&e.width||0)/2;b=Math.round(a/3)+.5;e=e&&e.height||0;return[["M",-a-1,.5],["L",a,.5],["L",a,e+.5],["L",-a-1,e+.5],["L",-a-1,.5],["M",-b,4],["L",-b,e-3],["M",b-1,4],["L",b-1,e-3]]};var K=function(){function l(a){this.zoomedMin=this.zoomedMax=this.yAxis=this.xAxis=this.top=this.size=this.shades=this.rendered=this.range=this.outlineHeight=this.outline=this.opposite=this.navigatorSize=this.navigatorSeries=this.navigatorOptions=
this.navigatorGroup=this.navigatorEnabled=this.left=this.height=this.handles=this.chart=this.baseSeries=void 0;this.init(a)}l.prototype.drawHandle=function(a,b,c,d){var e=this.navigatorOptions.handles.height;this.handles[b][d](c?{translateX:Math.round(this.left+this.height/2),translateY:Math.round(this.top+parseInt(a,10)+.5-e)}:{translateX:Math.round(this.left+parseInt(a,10)),translateY:Math.round(this.top+this.height/2-e/2-1)})};l.prototype.drawOutline=function(a,b,c,d){var e=this.navigatorOptions.maskInside,
k=this.outline.strokeWidth(),f=k/2,g=k%2/2;k=this.outlineHeight;var h=this.scrollbarHeight||0,m=this.size,l=this.left-h,n=this.top;c?(l-=f,c=n+b+g,b=n+a+g,g=[["M",l+k,n-h-g],["L",l+k,c],["L",l,c],["L",l,b],["L",l+k,b],["L",l+k,n+m+h]],e&&g.push(["M",l+k,c-f],["L",l+k,b+f])):(a+=l+h-g,b+=l+h-g,n+=f,g=[["M",l,n],["L",a,n],["L",a,n+k],["L",b,n+k],["L",b,n],["L",l+m+2*h,n]],e&&g.push(["M",a-f,n],["L",b+f,n]));this.outline[d]({d:g})};l.prototype.drawMasks=function(a,b,c,d){var e=this.left,k=this.top,f=
this.height;if(c){var g=[e,e,e];var h=[k,k+a,k+b];var m=[f,f,f];var l=[a,b-a,this.size-b]}else g=[e,e+a,e+b],h=[k,k,k],m=[a,b-a,this.size-b],l=[f,f,f];this.shades.forEach(function(a,b){a[d]({x:g[b],y:h[b],width:m[b],height:l[b]})})};l.prototype.renderElements=function(){var a=this,b=a.navigatorOptions,c=b.maskInside,d=a.chart,e=d.renderer,f,g={cursor:d.inverted?"ns-resize":"ew-resize"};a.navigatorGroup=f=e.g("navigator").attr({zIndex:8,visibility:"hidden"}).add();[!c,c,!c].forEach(function(c,k){a.shades[k]=
e.rect().addClass("highcharts-navigator-mask"+(1===k?"-inside":"-outside")).add(f);d.styledMode||a.shades[k].attr({fill:c?b.maskFill:"rgba(0,0,0,0)"}).css(1===k&&g)});a.outline=e.path().addClass("highcharts-navigator-outline").add(f);d.styledMode||a.outline.attr({"stroke-width":b.outlineWidth,stroke:b.outlineColor});b.handles.enabled&&[0,1].forEach(function(c){b.handles.inverted=d.inverted;a.handles[c]=e.symbol(b.handles.symbols[c],-b.handles.width/2-1,0,b.handles.width,b.handles.height,b.handles);
a.handles[c].attr({zIndex:7-c}).addClass("highcharts-navigator-handle highcharts-navigator-handle-"+["left","right"][c]).add(f);if(!d.styledMode){var k=b.handles;a.handles[c].attr({fill:k.backgroundColor,stroke:k.borderColor,"stroke-width":k.lineWidth}).css(g)}})};l.prototype.update=function(a){(this.series||[]).forEach(function(a){a.baseSeries&&delete a.baseSeries.navigatorSeries});this.destroy();f(!0,this.chart.options.navigator,this.options,a);this.init(this.chart)};l.prototype.render=function(a,
b,c,d){var k=this.chart,f=this.scrollbarHeight,g,h=this.xAxis,l=h.pointRange||0;var p=h.navigatorAxis.fake?k.xAxis[0]:h;var E=this.navigatorEnabled,r,t=this.rendered;var q=k.inverted;var u=k.xAxis[0].minRange,F=k.xAxis[0].options.maxRange;if(!this.hasDragged||n(c)){a=e(a-l/2);b=e(b+l/2);if(!m(a)||!m(b))if(t)c=0,d=G(h.width,p.width);else return;this.left=G(h.left,k.plotLeft+f+(q?k.plotWidth:0));this.size=r=g=G(h.len,(q?k.plotHeight:k.plotWidth)-2*f);k=q?f:g+2*f;c=G(c,h.toPixels(a,!0));d=G(d,h.toPixels(b,
!0));m(c)&&Infinity!==Math.abs(c)||(c=0,d=k);a=h.toValue(c,!0);b=h.toValue(d,!0);var v=Math.abs(e(b-a));v<u?this.grabbedLeft?c=h.toPixels(b-u-l,!0):this.grabbedRight&&(d=h.toPixels(a+u+l,!0)):n(F)&&e(v-l)>F&&(this.grabbedLeft?c=h.toPixels(b-F-l,!0):this.grabbedRight&&(d=h.toPixels(a+F+l,!0)));this.zoomedMax=C(Math.max(c,d),0,r);this.zoomedMin=C(this.fixedWidth?this.zoomedMax-this.fixedWidth:Math.min(c,d),0,r);this.range=this.zoomedMax-this.zoomedMin;r=Math.round(this.zoomedMax);c=Math.round(this.zoomedMin);
E&&(this.navigatorGroup.attr({visibility:"visible"}),t=t&&!this.hasDragged?"animate":"attr",this.drawMasks(c,r,q,t),this.drawOutline(c,r,q,t),this.navigatorOptions.handles.enabled&&(this.drawHandle(c,0,q,t),this.drawHandle(r,1,q,t)));this.scrollbar&&(q?(q=this.top-f,p=this.left-f+(E||!p.opposite?0:(p.titleOffset||0)+p.axisTitleMargin),f=g+2*f):(q=this.top+(E?this.height:-f),p=this.left-f),this.scrollbar.position(p,q,k,f),this.scrollbar.setRange(this.zoomedMin/(g||1),this.zoomedMax/(g||1)));this.rendered=
!0}};l.prototype.addMouseEvents=function(){var a=this,b=a.chart,c=b.container,d=[],e,f;a.mouseMoveHandler=e=function(b){a.onMouseMove(b)};a.mouseUpHandler=f=function(b){a.onMouseUp(b)};d=a.getPartsEvents("mousedown");d.push(t(b.renderTo,"mousemove",e),t(c.ownerDocument,"mouseup",f));u&&(d.push(t(b.renderTo,"touchmove",e),t(c.ownerDocument,"touchend",f)),d.concat(a.getPartsEvents("touchstart")));a.eventsToUnbind=d;a.series&&a.series[0]&&d.push(t(a.series[0].xAxis,"foundExtremes",function(){b.navigator.modifyNavigatorAxisExtremes()}))};
l.prototype.getPartsEvents=function(a){var b=this,c=[];["shades","handles"].forEach(function(d){b[d].forEach(function(e,k){c.push(t(e.element,a,function(a){b[d+"Mousedown"](a,k)}))})});return c};l.prototype.shadesMousedown=function(a,b){a=this.chart.pointer.normalize(a);var c=this.chart,d=this.xAxis,e=this.zoomedMin,k=this.left,f=this.size,g=this.range,h=a.chartX;c.inverted&&(h=a.chartY,k=this.top);if(1===b)this.grabbedCenter=h,this.fixedWidth=g,this.dragOffset=h-e;else{a=h-k-g/2;if(0===b)a=Math.max(0,
a);else if(2===b&&a+g>=f)if(a=f-g,this.reversedExtremes){a-=g;var m=this.getUnionExtremes().dataMin}else var l=this.getUnionExtremes().dataMax;a!==e&&(this.fixedWidth=g,b=d.navigatorAxis.toFixedRange(a,a+g,m,l),n(b.min)&&c.xAxis[0].setExtremes(Math.min(b.min,b.max),Math.max(b.min,b.max),!0,null,{trigger:"navigator"}))}};l.prototype.handlesMousedown=function(a,b){this.chart.pointer.normalize(a);a=this.chart;var c=a.xAxis[0],d=this.reversedExtremes;0===b?(this.grabbedLeft=!0,this.otherHandlePos=this.zoomedMax,
this.fixedExtreme=d?c.min:c.max):(this.grabbedRight=!0,this.otherHandlePos=this.zoomedMin,this.fixedExtreme=d?c.max:c.min);a.fixedRange=null};l.prototype.onMouseMove=function(a){var b=this,c=b.chart,d=b.left,e=b.navigatorSize,k=b.range,f=b.dragOffset,g=c.inverted;a.touches&&0===a.touches[0].pageX||(a=c.pointer.normalize(a),c=a.chartX,g&&(d=b.top,c=a.chartY),b.grabbedLeft?(b.hasDragged=!0,b.render(0,0,c-d,b.otherHandlePos)):b.grabbedRight?(b.hasDragged=!0,b.render(0,0,b.otherHandlePos,c-d)):b.grabbedCenter&&
(b.hasDragged=!0,c<f?c=f:c>e+f-k&&(c=e+f-k),b.render(0,0,c-f,c-f+k)),b.hasDragged&&b.scrollbar&&G(b.scrollbar.options.liveRedraw,v.svg&&!z&&!this.chart.isBoosting)&&(a.DOMType=a.type,setTimeout(function(){b.onMouseUp(a)},0)))};l.prototype.onMouseUp=function(a){var b=this.chart,c=this.xAxis,d=this.scrollbar,e=a.DOMEvent||a,k=b.inverted,f=this.rendered&&!this.hasDragged?"animate":"attr";if(this.hasDragged&&(!d||!d.hasDragged)||"scrollbar"===a.trigger){d=this.getUnionExtremes();if(this.zoomedMin===this.otherHandlePos)var g=
this.fixedExtreme;else if(this.zoomedMax===this.otherHandlePos)var h=this.fixedExtreme;this.zoomedMax===this.size&&(h=this.reversedExtremes?d.dataMin:d.dataMax);0===this.zoomedMin&&(g=this.reversedExtremes?d.dataMax:d.dataMin);c=c.navigatorAxis.toFixedRange(this.zoomedMin,this.zoomedMax,g,h);n(c.min)&&b.xAxis[0].setExtremes(Math.min(c.min,c.max),Math.max(c.min,c.max),!0,this.hasDragged?!1:null,{trigger:"navigator",triggerOp:"navigator-drag",DOMEvent:e})}"mousemove"!==a.DOMType&&"touchmove"!==a.DOMType&&
(this.grabbedLeft=this.grabbedRight=this.grabbedCenter=this.fixedWidth=this.fixedExtreme=this.otherHandlePos=this.hasDragged=this.dragOffset=null);this.navigatorEnabled&&m(this.zoomedMin)&&m(this.zoomedMax)&&(b=Math.round(this.zoomedMin),a=Math.round(this.zoomedMax),this.shades&&this.drawMasks(b,a,k,f),this.outline&&this.drawOutline(b,a,k,f),this.navigatorOptions.handles.enabled&&Object.keys(this.handles).length===this.handles.length&&(this.drawHandle(b,0,k,f),this.drawHandle(a,1,k,f)))};l.prototype.removeEvents=
function(){this.eventsToUnbind&&(this.eventsToUnbind.forEach(function(a){a()}),this.eventsToUnbind=void 0);this.removeBaseSeriesEvents()};l.prototype.removeBaseSeriesEvents=function(){var a=this.baseSeries||[];this.navigatorEnabled&&a[0]&&(!1!==this.navigatorOptions.adaptToUpdatedData&&a.forEach(function(a){I(a,"updatedData",this.updatedDataHandler)},this),a[0].xAxis&&I(a[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes))};l.prototype.init=function(a){var d=a.options,e=d.navigator,k=e.enabled,
g=d.scrollbar,h=g.enabled;d=k?e.height:0;var m=h?g.height:0;this.handles=[];this.shades=[];this.chart=a;this.setBaseSeries();this.height=d;this.scrollbarHeight=m;this.scrollbarEnabled=h;this.navigatorEnabled=k;this.navigatorOptions=e;this.scrollbarOptions=g;this.outlineHeight=d+m;this.opposite=G(e.opposite,!(k||!a.inverted));var l=this;k=l.baseSeries;g=a.xAxis.length;h=a.yAxis.length;var n=k&&k[0]&&k[0].xAxis||a.xAxis[0]||{options:{}};a.isDirtyBox=!0;l.navigatorEnabled?(l.xAxis=new b(a,f({breaks:n.options.breaks,
ordinal:n.options.ordinal},e.xAxis,{id:"navigator-x-axis",yAxis:"navigator-y-axis",isX:!0,type:"datetime",index:g,isInternal:!0,offset:0,keepOrdinalPadding:!0,startOnTick:!1,endOnTick:!1,minPadding:0,maxPadding:0,zoomEnabled:!1},a.inverted?{offsets:[m,0,-m,0],width:d}:{offsets:[0,-m,0,m],height:d})),l.yAxis=new b(a,f(e.yAxis,{id:"navigator-y-axis",alignTicks:!1,offset:0,index:h,isInternal:!0,zoomEnabled:!1},a.inverted?{width:d}:{height:d})),k||e.series.data?l.updateNavigatorSeries(!1):0===a.series.length&&
(l.unbindRedraw=t(a,"beforeRedraw",function(){0<a.series.length&&!l.series&&(l.setBaseSeries(),l.unbindRedraw())})),l.reversedExtremes=a.inverted&&!l.xAxis.reversed||!a.inverted&&l.xAxis.reversed,l.renderElements(),l.addMouseEvents()):(l.xAxis={chart:a,navigatorAxis:{fake:!0},translate:function(b,c){var d=a.xAxis[0],e=d.getExtremes(),f=d.len-2*m,k=H("min",d.options.min,e.dataMin);d=H("max",d.options.max,e.dataMax)-k;return c?b*d/f+k:f*(b-k)/d},toPixels:function(a){return this.translate(a)},toValue:function(a){return this.translate(a,
!0)}},l.xAxis.navigatorAxis.axis=l.xAxis,l.xAxis.navigatorAxis.toFixedRange=D.AdditionsClass.prototype.toFixedRange.bind(l.xAxis.navigatorAxis));a.options.scrollbar.enabled&&(a.scrollbar=l.scrollbar=new c(a.renderer,f(a.options.scrollbar,{margin:l.navigatorEnabled?0:10,vertical:a.inverted}),a),t(l.scrollbar,"changed",function(b){var c=l.size,d=c*this.to;c*=this.from;l.hasDragged=l.scrollbar.hasDragged;l.render(0,0,c,d);(a.options.scrollbar.liveRedraw||"mousemove"!==b.DOMType&&"touchmove"!==b.DOMType)&&
setTimeout(function(){l.onMouseUp(b)})}));l.addBaseSeriesEvents();l.addChartEvents()};l.prototype.getUnionExtremes=function(a){var b=this.chart.xAxis[0],c=this.xAxis,d=c.options,e=b.options,f;a&&null===b.dataMin||(f={dataMin:G(d&&d.min,H("min",e.min,b.dataMin,c.dataMin,c.min)),dataMax:G(d&&d.max,H("max",e.max,b.dataMax,c.dataMax,c.max))});return f};l.prototype.setBaseSeries=function(a,b){var c=this.chart,e=this.baseSeries=[];a=a||c.options&&c.options.navigator.baseSeries||(c.series.length?d(c.series,
function(a){return!a.options.isInternal}).index:0);(c.series||[]).forEach(function(b,c){b.options.isInternal||!b.options.showInNavigator&&(c!==a&&b.options.id!==a||!1===b.options.showInNavigator)||e.push(b)});this.xAxis&&!this.xAxis.navigatorAxis.fake&&this.updateNavigatorSeries(!0,b)};l.prototype.updateNavigatorSeries=function(a,b){var c=this,d=c.chart,e=c.baseSeries,k,h,l=c.navigatorOptions.series,m,n={enableMouseTracking:!1,index:null,linkedTo:null,group:"nav",padXAxis:!1,xAxis:"navigator-x-axis",
yAxis:"navigator-y-axis",showInLegend:!1,stacking:void 0,isInternal:!0,states:{inactive:{opacity:1}}},q=c.series=(c.series||[]).filter(function(a){var b=a.baseSeries;return 0>e.indexOf(b)?(b&&(I(b,"updatedData",c.updatedDataHandler),delete b.navigatorSeries),a.chart&&a.destroy(),!1):!0});e&&e.length&&e.forEach(function(a){var t=a.navigatorSeries,u=g({color:a.color,visible:a.visible},r(l)?p.navigator.series:l);t&&!1===c.navigatorOptions.adaptToUpdatedData||(n.name="Navigator "+e.length,k=a.options||
{},m=k.navigatorOptions||{},h=f(k,n,u,m),h.pointRange=G(u.pointRange,m.pointRange,p.plotOptions[h.type||"line"].pointRange),u=m.data||u.data,c.hasNavigatorData=c.hasNavigatorData||!!u,h.data=u||k.data&&k.data.slice(0),t&&t.options?t.update(h,b):(a.navigatorSeries=d.initSeries(h),a.navigatorSeries.baseSeries=a,q.push(a.navigatorSeries)))});if(l.data&&(!e||!e.length)||r(l))c.hasNavigatorData=!1,l=A(l),l.forEach(function(a,b){n.name="Navigator "+(q.length+1);h=f(p.navigator.series,{color:d.series[b]&&
!d.series[b].options.isInternal&&d.series[b].color||d.options.colors[b]||d.options.colors[0]},n,a);h.data=a.data;h.data&&(c.hasNavigatorData=!0,q.push(d.initSeries(h)))});a&&this.addBaseSeriesEvents()};l.prototype.addBaseSeriesEvents=function(){var b=this,c=b.baseSeries||[];c[0]&&c[0].xAxis&&t(c[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes);c.forEach(function(c){t(c,"show",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!0,!1)});t(c,"hide",function(){this.navigatorSeries&&
this.navigatorSeries.setVisible(!1,!1)});!1!==this.navigatorOptions.adaptToUpdatedData&&c.xAxis&&t(c,"updatedData",this.updatedDataHandler);t(c,"remove",function(){this.navigatorSeries&&(a(b.series,this.navigatorSeries),n(this.navigatorSeries.options)&&this.navigatorSeries.remove(!1),delete this.navigatorSeries)})},this)};l.prototype.getBaseSeriesMin=function(a){return this.baseSeries.reduce(function(a,b){return Math.min(a,b.xData?b.xData[0]:a)},a)};l.prototype.modifyNavigatorAxisExtremes=function(){var a=
this.xAxis,b;"undefined"!==typeof a.getExtremes&&(!(b=this.getUnionExtremes(!0))||b.dataMin===a.min&&b.dataMax===a.max||(a.min=b.dataMin,a.max=b.dataMax))};l.prototype.modifyBaseAxisExtremes=function(){var a=this.chart.navigator,b=this.getExtremes(),c=b.dataMin,d=b.dataMax;b=b.max-b.min;var e=a.stickToMin,f=a.stickToMax,g=G(this.options.overscroll,0),h=a.series&&a.series[0],l=!!this.setExtremes;if(!this.eventArgs||"rangeSelectorButton"!==this.eventArgs.trigger){if(e){var n=c;var p=n+b}f&&(p=d+g,e||
(n=Math.max(c,p-b,a.getBaseSeriesMin(h&&h.xData?h.xData[0]:-Number.MAX_VALUE))));l&&(e||f)&&m(n)&&(this.min=this.userMin=n,this.max=this.userMax=p)}a.stickToMin=a.stickToMax=null};l.prototype.updatedDataHandler=function(){var a=this.chart.navigator,b=this.navigatorSeries,c=a.getBaseSeriesMin(this.xData[0]);a.stickToMax=a.reversedExtremes?0===Math.round(a.zoomedMin):Math.round(a.zoomedMax)>=Math.round(a.size);a.stickToMin=m(this.xAxis.min)&&this.xAxis.min<=c&&(!this.chart.fixedRange||!a.stickToMax);
b&&!a.hasNavigatorData&&(b.options.pointStart=this.xData[0],b.setData(this.options.data,!1,null,!1))};l.prototype.addChartEvents=function(){this.eventsToUnbind||(this.eventsToUnbind=[]);this.eventsToUnbind.push(t(this.chart,"redraw",function(){var a=this.navigator,b=a&&(a.baseSeries&&a.baseSeries[0]&&a.baseSeries[0].xAxis||this.xAxis[0]);b&&a.render(b.min,b.max)}),t(this.chart,"getMargins",function(){var a=this.navigator,b=a.opposite?"plotTop":"marginBottom";this.inverted&&(b=a.opposite?"marginRight":
"plotLeft");this[b]=(this[b]||0)+(a.navigatorEnabled||!this.inverted?a.outlineHeight:0)+a.navigatorOptions.margin}))};l.prototype.destroy=function(){this.removeEvents();this.xAxis&&(a(this.chart.xAxis,this.xAxis),a(this.chart.axes,this.xAxis));this.yAxis&&(a(this.chart.yAxis,this.yAxis),a(this.chart.axes,this.yAxis));(this.series||[]).forEach(function(a){a.destroy&&a.destroy()});"series xAxis yAxis shades outline scrollbarTrack scrollbarRifles scrollbarGroup scrollbar navigatorGroup rendered".split(" ").forEach(function(a){this[a]&&
this[a].destroy&&this[a].destroy();this[a]=null},this);[this.handles].forEach(function(a){h(a)},this)};return l}();v.Navigator||(v.Navigator=K,D.compose(b),t(x,"beforeShowResetZoom",function(){var a=this.options,b=a.navigator,c=a.rangeSelector;if((b&&b.enabled||c&&c.enabled)&&(!z&&"x"===a.chart.zoomType||z&&"x"===a.chart.pinchType))return!1}),t(x,"beforeRender",function(){var a=this.options;if(a.navigator.enabled||a.scrollbar.enabled)this.scroller=this.navigator=new K(this)}),t(x,"afterSetChartSize",
function(){var a=this.legend,b=this.navigator;if(b){var c=a&&a.options;var d=b.xAxis;var e=b.yAxis;var f=b.scrollbarHeight;this.inverted?(b.left=b.opposite?this.chartWidth-f-b.height:this.spacing[3]+f,b.top=this.plotTop+f):(b.left=this.plotLeft+f,b.top=b.navigatorOptions.top||this.chartHeight-b.height-f-this.spacing[2]-(this.rangeSelector&&this.extraBottomMargin?this.rangeSelector.getHeight():0)-(c&&"bottom"===c.verticalAlign&&"proximate"!==c.layout&&c.enabled&&!c.floating?a.legendHeight+G(c.margin,
10):0)-(this.titleOffset?this.titleOffset[2]:0));d&&e&&(this.inverted?d.options.left=e.options.left=b.left:d.options.top=e.options.top=b.top,d.setAxisSize(),e.setAxisSize())}}),t(x,"update",function(a){var b=a.options.navigator||{},c=a.options.scrollbar||{};this.navigator||this.scroller||!b.enabled&&!c.enabled||(f(!0,this.options.navigator,b),f(!0,this.options.scrollbar,c),delete a.options.navigator,delete a.options.scrollbar)}),t(x,"afterUpdate",function(a){this.navigator||this.scroller||!this.options.navigator.enabled&&
!this.options.scrollbar.enabled||(this.scroller=this.navigator=new K(this),G(a.redraw,!0)&&this.redraw(a.animation))}),t(x,"afterAddSeries",function(){this.navigator&&this.navigator.setBaseSeries(null,!1)}),t(q,"afterUpdate",function(){this.chart.navigator&&!this.options.isInternal&&this.chart.navigator.setBaseSeries(null,!1)}),x.prototype.callbacks.push(function(a){var b=a.navigator;b&&a.xAxis[0]&&(a=a.xAxis[0].getExtremes(),b.render(a.min,a.max))}));v.Navigator=K;return v.Navigator});H(b,"masters/modules/gantt.src.js",
[],function(){})});
//# sourceMappingURL=gantt.js.map