/*
 Highmaps JS v8.2.0 (2020-10-07)

 Highmaps as a plugin for Highcharts or Highstock.

 (c) 2011-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/map",["highcharts"],function(w){a(w);a.Highcharts=w;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function w(a,g,k,t){a.hasOwnProperty(g)||(a[g]=t.apply(null,k))}a=a?a._modules:{};w(a,"Core/Axis/MapAxis.js",[a["Core/Axis/Axis.js"],a["Core/Utilities.js"]],function(a,g){var k=g.addEvent,q=g.pick,b=function(){return function(a){this.axis=
a}}();g=function(){function a(){}a.compose=function(a){a.keepProps.push("mapAxis");k(a,"init",function(){this.mapAxis||(this.mapAxis=new b(this))});k(a,"getSeriesExtremes",function(){if(this.mapAxis){var a=[];this.isXAxis&&(this.series.forEach(function(b,l){b.useMapGeometry&&(a[l]=b.xData,b.xData=[])}),this.mapAxis.seriesXData=a)}});k(a,"afterGetSeriesExtremes",function(){if(this.mapAxis){var a=this.mapAxis.seriesXData||[],b;if(this.isXAxis){var l=q(this.dataMin,Number.MAX_VALUE);var e=q(this.dataMax,
-Number.MAX_VALUE);this.series.forEach(function(f,m){f.useMapGeometry&&(l=Math.min(l,q(f.minX,l)),e=Math.max(e,q(f.maxX,e)),f.xData=a[m],b=!0)});b&&(this.dataMin=l,this.dataMax=e);this.mapAxis.seriesXData=void 0}}});k(a,"afterSetAxisTranslation",function(){if(this.mapAxis){var a=this.chart,b=a.plotWidth/a.plotHeight;a=a.xAxis[0];var l;"yAxis"===this.coll&&"undefined"!==typeof a.transA&&this.series.forEach(function(a){a.preserveAspectRatio&&(l=!0)});if(l&&(this.transA=a.transA=Math.min(this.transA,
a.transA),b/=(a.max-a.min)/(this.max-this.min),b=1>b?this:a,a=(b.max-b.min)*b.transA,b.mapAxis.pixelPadding=b.len-a,b.minPixelPadding=b.mapAxis.pixelPadding/2,a=b.mapAxis.fixTo)){a=a[1]-b.toValue(a[0],!0);a*=b.transA;if(Math.abs(a)>b.minPixelPadding||b.min===b.dataMin&&b.max===b.dataMax)a=0;b.minPixelPadding-=a}}});k(a,"render",function(){this.mapAxis&&(this.mapAxis.fixTo=void 0)})};return a}();g.compose(a);return g});w(a,"Mixins/ColorSeries.js",[],function(){return{colorPointMixin:{setVisible:function(a){var g=
this,k=a?"show":"hide";g.visible=g.options.visible=!!a;["graphic","dataLabel"].forEach(function(a){if(g[a])g[a][k]()});this.series.buildKDTree()}},colorSeriesMixin:{optionalAxis:"colorAxis",colorAxis:0,translateColors:function(){var a=this,g=this.options.nullColor,k=this.colorAxis,t=this.colorKey;(this.data.length?this.data:this.points).forEach(function(b){var n=b.getNestedProperty(t);(n=b.options.color||(b.isNull||null===b.value?g:k&&"undefined"!==typeof n?k.toColor(n,b):b.color||a.color))&&b.color!==
n&&(b.color=n,"point"===a.options.legendType&&b.legendItem&&a.chart.legend.colorizeItem(b,b.visible))})}}}});w(a,"Core/Axis/ColorAxis.js",[a["Core/Axis/Axis.js"],a["Core/Chart/Chart.js"],a["Core/Color/Color.js"],a["Mixins/ColorSeries.js"],a["Core/Animation/Fx.js"],a["Core/Globals.js"],a["Core/Legend.js"],a["Mixins/LegendSymbol.js"],a["Series/LineSeries.js"],a["Core/Series/Point.js"],a["Core/Utilities.js"]],function(a,g,k,t,b,n,A,v,x,l,e){var f=this&&this.__extends||function(){var a=function(d,h){a=
Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(h,d){h.__proto__=d}||function(h,d){for(var a in d)d.hasOwnProperty(a)&&(h[a]=d[a])};return a(d,h)};return function(d,h){function c(){this.constructor=d}a(d,h);d.prototype=null===h?Object.create(h):(c.prototype=h.prototype,new c)}}(),m=k.parse;k=t.colorPointMixin;t=t.colorSeriesMixin;var F=n.noop,r=e.addEvent,C=e.erase,c=e.extend,p=e.isNumber,G=e.merge,u=e.pick,y=e.splat;"";c(x.prototype,t);c(l.prototype,k);g.prototype.collectionsWithUpdate.push("colorAxis");
g.prototype.collectionsWithInit.colorAxis=[g.prototype.addColorAxis];var B=function(a){function d(h,d){var c=a.call(this,h,d)||this;c.beforePadding=!1;c.chart=void 0;c.coll="colorAxis";c.dataClasses=void 0;c.legendItem=void 0;c.legendItems=void 0;c.name="";c.options=void 0;c.stops=void 0;c.visible=!0;c.init(h,d);return c}f(d,a);d.buildOptions=function(h,d,a){h=h.options.legend||{};var c=a.layout?"vertical"!==a.layout:"vertical"!==h.layout;return G(d,{side:c?2:1,reversed:!c},a,{opposite:!c,showEmpty:!1,
title:null,visible:h.enabled&&(a?!1!==a.visible:!0)})};d.prototype.init=function(h,c){var f=d.buildOptions(h,d.defaultOptions,c);this.coll="colorAxis";a.prototype.init.call(this,h,f);c.dataClasses&&this.initDataClasses(c);this.initStops();this.horiz=!f.opposite;this.zoomEnabled=!1};d.prototype.initDataClasses=function(h){var d=this.chart,a,c=0,f=d.options.chart.colorCount,b=this.options,e=h.dataClasses.length;this.dataClasses=a=[];this.legendItems=[];h.dataClasses.forEach(function(h,D){h=G(h);a.push(h);
if(d.styledMode||!h.color)"category"===b.dataClassColor?(d.styledMode||(D=d.options.colors,f=D.length,h.color=D[c]),h.colorIndex=c,c++,c===f&&(c=0)):h.color=m(b.minColor).tweenTo(m(b.maxColor),2>e?.5:D/(e-1))})};d.prototype.hasData=function(){return!!(this.tickPositions||[]).length};d.prototype.setTickPositions=function(){if(!this.dataClasses)return a.prototype.setTickPositions.call(this)};d.prototype.initStops=function(){this.stops=this.options.stops||[[0,this.options.minColor],[1,this.options.maxColor]];
this.stops.forEach(function(h){h.color=m(h[1])})};d.prototype.setOptions=function(h){a.prototype.setOptions.call(this,h);this.options.crosshair=this.options.marker};d.prototype.setAxisSize=function(){var h=this.legendSymbol,a=this.chart,c=a.options.legend||{},f,b;h?(this.left=c=h.attr("x"),this.top=f=h.attr("y"),this.width=b=h.attr("width"),this.height=h=h.attr("height"),this.right=a.chartWidth-c-b,this.bottom=a.chartHeight-f-h,this.len=this.horiz?b:h,this.pos=this.horiz?c:f):this.len=(this.horiz?
c.symbolWidth:c.symbolHeight)||d.defaultLegendLength};d.prototype.normalizedValue=function(h){this.logarithmic&&(h=this.logarithmic.log2lin(h));return 1-(this.max-h)/(this.max-this.min||1)};d.prototype.toColor=function(h,d){var a=this.dataClasses,c=this.stops,f;if(a)for(f=a.length;f--;){var b=a[f];var e=b.from;c=b.to;if(("undefined"===typeof e||h>=e)&&("undefined"===typeof c||h<=c)){var m=b.color;d&&(d.dataClass=f,d.colorIndex=b.colorIndex);break}}else{h=this.normalizedValue(h);for(f=c.length;f--&&
!(h>c[f][0]););e=c[f]||c[f+1];c=c[f+1]||e;h=1-(c[0]-h)/(c[0]-e[0]||1);m=e.color.tweenTo(c.color,h)}return m};d.prototype.getOffset=function(){var h=this.legendGroup,d=this.chart.axisOffset[this.side];h&&(this.axisParent=h,a.prototype.getOffset.call(this),this.added||(this.added=!0,this.labelLeft=0,this.labelRight=this.width),this.chart.axisOffset[this.side]=d)};d.prototype.setLegendColor=function(){var h=this.reversed,d=h?1:0;h=h?0:1;d=this.horiz?[d,0,h,0]:[0,h,0,d];this.legendColor={linearGradient:{x1:d[0],
y1:d[1],x2:d[2],y2:d[3]},stops:this.stops}};d.prototype.drawLegendSymbol=function(h,a){var c=h.padding,f=h.options,b=this.horiz,e=u(f.symbolWidth,b?d.defaultLegendLength:12),m=u(f.symbolHeight,b?12:d.defaultLegendLength),p=u(f.labelPadding,b?16:30);f=u(f.itemDistance,10);this.setLegendColor();a.legendSymbol=this.chart.renderer.rect(0,h.baseline-11,e,m).attr({zIndex:1}).add(a.legendGroup);this.legendItemWidth=e+c+(b?f:p);this.legendItemHeight=m+c+(b?p:0)};d.prototype.setState=function(h){this.series.forEach(function(d){d.setState(h)})};
d.prototype.setVisible=function(){};d.prototype.getSeriesExtremes=function(){var h=this.series,d=h.length,a;this.dataMin=Infinity;for(this.dataMax=-Infinity;d--;){var c=h[d];var f=c.colorKey=u(c.options.colorKey,c.colorKey,c.pointValKey,c.zoneAxis,"y");var b=c.pointArrayMap;var e=c[f+"Min"]&&c[f+"Max"];if(c[f+"Data"])var m=c[f+"Data"];else if(b){m=[];b=b.indexOf(f);var p=c.yData;if(0<=b&&p)for(a=0;a<p.length;a++)m.push(u(p[a][b],p[a]))}else m=c.yData;e?(c.minColorValue=c[f+"Min"],c.maxColorValue=
c[f+"Max"]):(m=x.prototype.getExtremes.call(c,m),c.minColorValue=m.dataMin,c.maxColorValue=m.dataMax);"undefined"!==typeof c.minColorValue&&(this.dataMin=Math.min(this.dataMin,c.minColorValue),this.dataMax=Math.max(this.dataMax,c.maxColorValue));e||x.prototype.applyExtremes.call(c)}};d.prototype.drawCrosshair=function(h,d){var c=d&&d.plotX,f=d&&d.plotY,b=this.pos,e=this.len;if(d){var m=this.toPixels(d.getNestedProperty(d.series.colorKey));m<b?m=b-2:m>b+e&&(m=b+e+2);d.plotX=m;d.plotY=this.len-m;a.prototype.drawCrosshair.call(this,
h,d);d.plotX=c;d.plotY=f;this.cross&&!this.cross.addedToColorAxis&&this.legendGroup&&(this.cross.addClass("highcharts-coloraxis-marker").add(this.legendGroup),this.cross.addedToColorAxis=!0,!this.chart.styledMode&&this.crosshair&&this.cross.attr({fill:this.crosshair.color}))}};d.prototype.getPlotLinePath=function(d){var h=this.left,c=d.translatedValue,f=this.top;return p(c)?this.horiz?[["M",c-4,f-6],["L",c+4,f-6],["L",c,f],["Z"]]:[["M",h,c],["L",h-6,c+6],["L",h-6,c-6],["Z"]]:a.prototype.getPlotLinePath.call(this,
d)};d.prototype.update=function(c,f){var h=this.chart,b=h.legend,e=d.buildOptions(h,{},c);this.series.forEach(function(d){d.isDirtyData=!0});(c.dataClasses&&b.allItems||this.dataClasses)&&this.destroyItems();h.options[this.coll]=G(this.userOptions,e);a.prototype.update.call(this,e,f);this.legendItem&&(this.setLegendColor(),b.colorizeItem(this,!0))};d.prototype.destroyItems=function(){var d=this.chart;this.legendItem?d.legend.destroyItem(this):this.legendItems&&this.legendItems.forEach(function(c){d.legend.destroyItem(c)});
d.isDirtyLegend=!0};d.prototype.remove=function(d){this.destroyItems();a.prototype.remove.call(this,d)};d.prototype.getDataClassLegendSymbols=function(){var d=this,a=d.chart,f=d.legendItems,b=a.options.legend,e=b.valueDecimals,m=b.valueSuffix||"",p;f.length||d.dataClasses.forEach(function(h,b){var l=!0,r=h.from,n=h.to,z=a.numberFormatter;p="";"undefined"===typeof r?p="< ":"undefined"===typeof n&&(p="> ");"undefined"!==typeof r&&(p+=z(r,e)+m);"undefined"!==typeof r&&"undefined"!==typeof n&&(p+=" - ");
"undefined"!==typeof n&&(p+=z(n,e)+m);f.push(c({chart:a,name:p,options:{},drawLegendSymbol:v.drawRectangle,visible:!0,setState:F,isDataClass:!0,setVisible:function(){l=d.visible=!l;d.series.forEach(function(d){d.points.forEach(function(d){d.dataClass===b&&d.setVisible(l)})});a.legend.colorizeItem(this,l)}},h))});return f};d.defaultLegendLength=200;d.defaultOptions={lineWidth:0,minPadding:0,maxPadding:0,gridLineWidth:1,tickPixelInterval:72,startOnTick:!0,endOnTick:!0,offset:0,marker:{animation:{duration:50},
width:.01,color:"#999999"},labels:{overflow:"justify",rotation:0},minColor:"#e6ebf5",maxColor:"#003399",tickLength:5,showInLegend:!0};d.keepProps=["legendGroup","legendItemHeight","legendItemWidth","legendItem","legendSymbol"];return d}(a);Array.prototype.push.apply(a.keepProps,B.keepProps);n.ColorAxis=B;["fill","stroke"].forEach(function(c){b.prototype[c+"Setter"]=function(){this.elem.attr(c,m(this.start).tweenTo(m(this.end),this.pos),null,!0)}});r(g,"afterGetAxes",function(){var c=this,d=c.options;
this.colorAxis=[];d.colorAxis&&(d.colorAxis=y(d.colorAxis),d.colorAxis.forEach(function(d,a){d.index=a;new B(c,d)}))});r(x,"bindAxes",function(){var c=this.axisTypes;c?-1===c.indexOf("colorAxis")&&c.push("colorAxis"):this.axisTypes=["colorAxis"]});r(A,"afterGetAllItems",function(c){var d=[],h,a;(this.chart.colorAxis||[]).forEach(function(a){(h=a.options)&&h.showInLegend&&(h.dataClasses&&h.visible?d=d.concat(a.getDataClassLegendSymbols()):h.visible&&d.push(a),a.series.forEach(function(d){if(!d.options.showInLegend||
h.dataClasses)"point"===d.options.legendType?d.points.forEach(function(d){C(c.allItems,d)}):C(c.allItems,d)}))});for(a=d.length;a--;)c.allItems.unshift(d[a])});r(A,"afterColorizeItem",function(c){c.visible&&c.item.legendColor&&c.item.legendSymbol.attr({fill:c.item.legendColor})});r(A,"afterUpdate",function(){var c=this.chart.colorAxis;c&&c.forEach(function(d,c,a){d.update({},a)})});r(x,"afterTranslate",function(){(this.chart.colorAxis&&this.chart.colorAxis.length||this.colorAttribs)&&this.translateColors()});
return B});w(a,"Mixins/ColorMapSeries.js",[a["Core/Globals.js"],a["Core/Series/Point.js"],a["Core/Utilities.js"]],function(a,g,k){var q=k.defined;return{colorMapPointMixin:{dataLabelOnNull:!0,isValid:function(){return null!==this.value&&Infinity!==this.value&&-Infinity!==this.value},setState:function(a){g.prototype.setState.call(this,a);this.graphic&&this.graphic.attr({zIndex:"hover"===a?1:0})}},colorMapSeriesMixin:{pointArrayMap:["value"],axisTypes:["xAxis","yAxis","colorAxis"],trackerGroups:["group",
"markerGroup","dataLabelsGroup"],getSymbol:a.noop,parallelArrays:["x","y","value"],colorKey:"value",pointAttribs:a.seriesTypes.column.prototype.pointAttribs,colorAttribs:function(a){var b={};q(a.color)&&(b[this.colorProp||"fill"]=a.color);return b}}}});w(a,"Maps/MapNavigation.js",[a["Core/Chart/Chart.js"],a["Core/Globals.js"],a["Core/Utilities.js"]],function(a,g,k){function q(a){a&&(a.preventDefault&&a.preventDefault(),a.stopPropagation&&a.stopPropagation(),a.cancelBubble=!0)}function b(a){this.init(a)}
var n=g.doc,A=k.addEvent,v=k.extend,x=k.merge,l=k.objectEach,e=k.pick;b.prototype.init=function(a){this.chart=a;a.mapNavButtons=[]};b.prototype.update=function(a){var f=this.chart,b=f.options.mapNavigation,r,n,c,p,k,g=function(c){this.handler.call(f,c);q(c)},y=f.mapNavButtons;a&&(b=f.options.mapNavigation=x(f.options.mapNavigation,a));for(;y.length;)y.pop().destroy();e(b.enableButtons,b.enabled)&&!f.renderer.forExport&&l(b.buttons,function(a,e){r=x(b.buttonOptions,a);f.styledMode||(n=r.theme,n.style=
x(r.theme.style,r.style),p=(c=n.states)&&c.hover,k=c&&c.select);a=f.renderer.button(r.text,0,0,g,n,p,k,0,"zoomIn"===e?"topbutton":"bottombutton").addClass("highcharts-map-navigation highcharts-"+{zoomIn:"zoom-in",zoomOut:"zoom-out"}[e]).attr({width:r.width,height:r.height,title:f.options.lang[e],padding:r.padding,zIndex:5}).add();a.handler=r.onclick;A(a.element,"dblclick",q);y.push(a);var d=r,h=A(f,"load",function(){a.align(v(d,{width:a.width,height:2*a.height}),null,d.alignTo);h()})});this.updateEvents(b)};
b.prototype.updateEvents=function(a){var f=this.chart;e(a.enableDoubleClickZoom,a.enabled)||a.enableDoubleClickZoomTo?this.unbindDblClick=this.unbindDblClick||A(f.container,"dblclick",function(a){f.pointer.onContainerDblClick(a)}):this.unbindDblClick&&(this.unbindDblClick=this.unbindDblClick());e(a.enableMouseWheelZoom,a.enabled)?this.unbindMouseWheel=this.unbindMouseWheel||A(f.container,"undefined"===typeof n.onmousewheel?"DOMMouseScroll":"mousewheel",function(a){f.pointer.onContainerMouseWheel(a);
q(a);return!1}):this.unbindMouseWheel&&(this.unbindMouseWheel=this.unbindMouseWheel())};v(a.prototype,{fitToBox:function(a,b){[["x","width"],["y","height"]].forEach(function(f){var e=f[0];f=f[1];a[e]+a[f]>b[e]+b[f]&&(a[f]>b[f]?(a[f]=b[f],a[e]=b[e]):a[e]=b[e]+b[f]-a[f]);a[f]>b[f]&&(a[f]=b[f]);a[e]<b[e]&&(a[e]=b[e])});return a},mapZoom:function(a,b,l,n,k){var c=this.xAxis[0],f=c.max-c.min,m=e(b,c.min+f/2),g=f*a;f=this.yAxis[0];var r=f.max-f.min,C=e(l,f.min+r/2);r*=a;m=this.fitToBox({x:m-g*(n?(n-c.pos)/
c.len:.5),y:C-r*(k?(k-f.pos)/f.len:.5),width:g,height:r},{x:c.dataMin,y:f.dataMin,width:c.dataMax-c.dataMin,height:f.dataMax-f.dataMin});g=m.x<=c.dataMin&&m.width>=c.dataMax-c.dataMin&&m.y<=f.dataMin&&m.height>=f.dataMax-f.dataMin;n&&c.mapAxis&&(c.mapAxis.fixTo=[n-c.pos,b]);k&&f.mapAxis&&(f.mapAxis.fixTo=[k-f.pos,l]);"undefined"===typeof a||g?(c.setExtremes(void 0,void 0,!1),f.setExtremes(void 0,void 0,!1)):(c.setExtremes(m.x,m.x+m.width,!1),f.setExtremes(m.y,m.y+m.height,!1));this.redraw()}});A(a,
"beforeRender",function(){this.mapNavigation=new b(this);this.mapNavigation.update()});g.MapNavigation=b});w(a,"Maps/MapPointer.js",[a["Core/Pointer.js"],a["Core/Utilities.js"]],function(a,g){var k=g.extend,q=g.pick;g=g.wrap;k(a.prototype,{onContainerDblClick:function(a){var b=this.chart;a=this.normalize(a);b.options.mapNavigation.enableDoubleClickZoomTo?b.pointer.inClass(a.target,"highcharts-tracker")&&b.hoverPoint&&b.hoverPoint.zoomTo():b.isInsidePlot(a.chartX-b.plotLeft,a.chartY-b.plotTop)&&b.mapZoom(.5,
b.xAxis[0].toValue(a.chartX),b.yAxis[0].toValue(a.chartY),a.chartX,a.chartY)},onContainerMouseWheel:function(a){var b=this.chart;a=this.normalize(a);var k=a.detail||-(a.wheelDelta/120);b.isInsidePlot(a.chartX-b.plotLeft,a.chartY-b.plotTop)&&b.mapZoom(Math.pow(b.options.mapNavigation.mouseWheelSensitivity,k),b.xAxis[0].toValue(a.chartX),b.yAxis[0].toValue(a.chartY),a.chartX,a.chartY)}});g(a.prototype,"zoomOption",function(a){var b=this.chart.options.mapNavigation;q(b.enableTouchZoom,b.enabled)&&(this.chart.options.chart.pinchType=
"xy");a.apply(this,[].slice.call(arguments,1))});g(a.prototype,"pinchTranslate",function(a,k,g,q,t,l,e){a.call(this,k,g,q,t,l,e);"map"===this.chart.options.chart.type&&this.hasZoom&&(a=q.scaleX>q.scaleY,this.pinchTranslateDirection(!a,k,g,q,t,l,e,a?q.scaleX:q.scaleY))})});w(a,"Maps/Map.js",[a["Core/Chart/Chart.js"],a["Core/Globals.js"],a["Core/Options.js"],a["Core/Renderer/SVG/SVGRenderer.js"],a["Core/Utilities.js"]],function(a,g,k,t,b){function n(a,b,e,l,k,c,p,g){return[["M",a+k,b],["L",a+e-c,b],
["C",a+e-c/2,b,a+e,b+c/2,a+e,b+c],["L",a+e,b+l-p],["C",a+e,b+l-p/2,a+e-p/2,b+l,a+e-p,b+l],["L",a+g,b+l],["C",a+g/2,b+l,a,b+l-g/2,a,b+l-g],["L",a,b+k],["C",a,b+k/2,a+k/2,b,a+k,b],["Z"]]}k=k.defaultOptions;var q=b.extend,v=b.getOptions,x=b.merge,l=b.pick;b=g.Renderer;var e=g.VMLRenderer;q(k.lang,{zoomIn:"Zoom in",zoomOut:"Zoom out"});k.mapNavigation={buttonOptions:{alignTo:"plotBox",align:"left",verticalAlign:"top",x:0,width:18,height:18,padding:5,style:{fontSize:"15px",fontWeight:"bold"},theme:{"stroke-width":1,
"text-align":"center"}},buttons:{zoomIn:{onclick:function(){this.mapZoom(.5)},text:"+",y:0},zoomOut:{onclick:function(){this.mapZoom(2)},text:"-",y:28}},mouseWheelSensitivity:1.1};k=g.splitPath=function(a){"string"===typeof a&&(a=a.replace(/([A-Za-z])/g," $1 ").replace(/^\s*/,"").replace(/\s*$/,""),a=a.split(/[ ,;]+/).map(function(a){return/[A-za-z]/.test(a)?a:parseFloat(a)}));return t.prototype.pathToSegments(a)};g.maps={};t.prototype.symbols.topbutton=function(a,b,e,l,k){k=k&&k.r||0;return n(a-
1,b-1,e,l,k,k,0,0)};t.prototype.symbols.bottombutton=function(a,b,e,l,k){k=k&&k.r||0;return n(a-1,b-1,e,l,0,0,k,k)};b===e&&["topbutton","bottombutton"].forEach(function(a){e.prototype.symbols[a]=t.prototype.symbols[a]});return{mapChart:g.Map=g.mapChart=function(b,e,k){var f="string"===typeof b||b.nodeName,g=arguments[f?1:0],c=g,p={endOnTick:!1,visible:!1,minPadding:0,maxPadding:0,startOnTick:!1},m=v().credits;var n=g.series;g.series=null;g=x({chart:{panning:{enabled:!0,type:"xy"},type:"map"},credits:{mapText:l(m.mapText,
' \u00a9 <a href="{geojson.copyrightUrl}">{geojson.copyrightShort}</a>'),mapTextFull:l(m.mapTextFull,"{geojson.copyright}")},tooltip:{followTouchMove:!1},xAxis:p,yAxis:x(p,{reversed:!0})},g,{chart:{inverted:!1,alignTicks:!1}});g.series=c.series=n;return f?new a(b,g,k):new a(g,e)},maps:g.maps,splitPath:k}});w(a,"Series/MapSeries.js",[a["Core/Series/Series.js"],a["Mixins/ColorMapSeries.js"],a["Core/Globals.js"],a["Mixins/LegendSymbol.js"],a["Maps/Map.js"],a["Core/Series/Point.js"],a["Core/Renderer/SVG/SVGRenderer.js"],
a["Core/Utilities.js"]],function(a,g,k,t,b,n,A,v){var q=g.colorMapPointMixin,l=k.noop,e=b.maps,f=b.splitPath,m=v.extend,F=v.fireEvent,r=v.getNestedProperty,C=v.isArray,c=v.isNumber,p=v.merge,G=v.objectEach,u=v.pick,y=v.splat,B=k.Series,z=a.seriesTypes;a.seriesType("map","scatter",{animation:!1,dataLabels:{crop:!1,formatter:function(){return this.point.value},inside:!0,overflow:!1,padding:0,verticalAlign:"middle"},marker:null,nullColor:"#f7f7f7",stickyTracking:!1,tooltip:{followPointer:!0,pointFormat:"{point.name}: {point.value}<br/>"},
turboThreshold:0,allAreas:!0,borderColor:"#cccccc",borderWidth:1,joinBy:"hc-key",states:{hover:{halo:null,brightness:.2},normal:{animation:!0},select:{color:"#cccccc"},inactive:{opacity:1}}},p(g.colorMapSeriesMixin,{type:"map",getExtremesFromAll:!0,useMapGeometry:!0,forceDL:!0,searchPoint:l,directTouch:!0,preserveAspectRatio:!0,pointArrayMap:["value"],setOptions:function(a){a=B.prototype.setOptions.call(this,a);var d=a.joinBy;null===d&&(d="_i");d=this.joinBy=y(d);d[1]||(d[1]=d[0]);return a},getBox:function(a){var d=
Number.MAX_VALUE,c=-d,b=d,e=-d,l=d,k=d,p=this.xAxis,g=this.yAxis,m;(a||[]).forEach(function(a){if(a.path){"string"===typeof a.path?a.path=f(a.path):"M"===a.path[0]&&(a.path=A.prototype.pathToSegments(a.path));var h=a.path||[],p=-d,g=d,n=-d,r=d,D=a.properties;a._foundBox||(h.forEach(function(a){var d=a[a.length-2];a=a[a.length-1];"number"===typeof d&&"number"===typeof a&&(g=Math.min(g,d),p=Math.max(p,d),r=Math.min(r,a),n=Math.max(n,a))}),a._midX=g+(p-g)*u(a.middleX,D&&D["hc-middle-x"],.5),a._midY=
r+(n-r)*u(a.middleY,D&&D["hc-middle-y"],.5),a._maxX=p,a._minX=g,a._maxY=n,a._minY=r,a.labelrank=u(a.labelrank,(p-g)*(n-r)),a._foundBox=!0);c=Math.max(c,a._maxX);b=Math.min(b,a._minX);e=Math.max(e,a._maxY);l=Math.min(l,a._minY);k=Math.min(a._maxX-a._minX,a._maxY-a._minY,k);m=!0}});m&&(this.minY=Math.min(l,u(this.minY,d)),this.maxY=Math.max(e,u(this.maxY,-d)),this.minX=Math.min(b,u(this.minX,d)),this.maxX=Math.max(c,u(this.maxX,-d)),p&&"undefined"===typeof p.options.minRange&&(p.minRange=Math.min(5*
k,(this.maxX-this.minX)/5,p.minRange||d)),g&&"undefined"===typeof g.options.minRange&&(g.minRange=Math.min(5*k,(this.maxY-this.minY)/5,g.minRange||d)))},hasData:function(){return!!this.processedXData.length},getExtremes:function(){var a=B.prototype.getExtremes.call(this,this.valueData),b=a.dataMin;a=a.dataMax;this.chart.hasRendered&&this.isDirtyData&&this.getBox(this.options.data);c(b)&&(this.valueMin=b);c(a)&&(this.valueMax=a);return{dataMin:this.minY,dataMax:this.maxY}},translatePath:function(a){var d=
this.xAxis,c=this.yAxis,b=d.min,e=d.transA,f=d.minPixelPadding,l=c.min,p=c.transA,k=c.minPixelPadding,g=[];a&&a.forEach(function(a){"M"===a[0]?g.push(["M",(a[1]-(b||0))*e+f,(a[2]-(l||0))*p+k]):"L"===a[0]?g.push(["L",(a[1]-(b||0))*e+f,(a[2]-(l||0))*p+k]):"C"===a[0]?g.push(["C",(a[1]-(b||0))*e+f,(a[2]-(l||0))*p+k,(a[3]-(b||0))*e+f,(a[4]-(l||0))*p+k,(a[5]-(b||0))*e+f,(a[6]-(l||0))*p+k]):"Q"===a[0]?g.push(["Q",(a[1]-(b||0))*e+f,(a[2]-(l||0))*p+k,(a[3]-(b||0))*e+f,(a[4]-(l||0))*p+k]):"Z"===a[0]&&g.push(["Z"])});
return g},setData:function(a,b,f,l){var d=this.options,h=this.chart.options.chart,g=h&&h.map,m=d.mapData,q=this.joinBy,z=d.keys||this.pointArrayMap,u=[],y={},E=this.chart.mapTransforms;!m&&g&&(m="string"===typeof g?e[g]:g);a&&a.forEach(function(b,h){var e=0;if(c(b))a[h]={value:b};else if(C(b)){a[h]={};!d.keys&&b.length>z.length&&"string"===typeof b[0]&&(a[h]["hc-key"]=b[0],++e);for(var f=0;f<z.length;++f,++e)z[f]&&"undefined"!==typeof b[e]&&(0<z[f].indexOf(".")?n.prototype.setNestedProperty(a[h],
b[e],z[f]):a[h][z[f]]=b[e])}q&&"_i"===q[0]&&(a[h]._i=h)});this.getBox(a);(this.chart.mapTransforms=E=h&&h.mapTransforms||m&&m["hc-transform"]||E)&&G(E,function(a){a.rotation&&(a.cosAngle=Math.cos(a.rotation),a.sinAngle=Math.sin(a.rotation))});if(m){"FeatureCollection"===m.type&&(this.mapTitle=m.title,m=k.geojson(m,this.type,this));this.mapData=m;this.mapMap={};for(E=0;E<m.length;E++)h=m[E],g=h.properties,h._i=E,q[0]&&g&&g[q[0]]&&(h[q[0]]=g[q[0]]),y[h[q[0]]]=h;this.mapMap=y;if(a&&q[1]){var t=q[1];
a.forEach(function(a){a=r(t,a);y[a]&&u.push(y[a])})}if(d.allAreas){this.getBox(m);a=a||[];if(q[1]){var A=q[1];a.forEach(function(a){u.push(r(A,a))})}u="|"+u.map(function(a){return a&&a[q[0]]}).join("|")+"|";m.forEach(function(d){q[0]&&-1!==u.indexOf("|"+d[q[0]]+"|")||(a.push(p(d,{value:null})),l=!1)})}else this.getBox(u)}B.prototype.setData.call(this,a,b,f,l)},drawGraph:l,drawDataLabels:l,doFullTranslate:function(){return this.isDirtyData||this.chart.isResizing||this.chart.renderer.isVML||!this.baseTrans},
translate:function(){var a=this,b=a.xAxis,e=a.yAxis,f=a.doFullTranslate();a.generatePoints();a.data.forEach(function(d){c(d._midX)&&c(d._midY)&&(d.plotX=b.toPixels(d._midX,!0),d.plotY=e.toPixels(d._midY,!0));f&&(d.shapeType="path",d.shapeArgs={d:a.translatePath(d.path)})});F(a,"afterTranslate")},pointAttribs:function(a,c){c=a.series.chart.styledMode?this.colorAttribs(a):z.column.prototype.pointAttribs.call(this,a,c);c["stroke-width"]=u(a.options[this.pointAttrToOptions&&this.pointAttrToOptions["stroke-width"]||
"borderWidth"],"inherit");return c},drawPoints:function(){var a=this,c=a.xAxis,b=a.yAxis,e=a.group,f=a.chart,g=f.renderer,l=this.baseTrans;a.transformGroup||(a.transformGroup=g.g().attr({scaleX:1,scaleY:1}).add(e),a.transformGroup.survive=!0);if(a.doFullTranslate())f.hasRendered&&!f.styledMode&&a.points.forEach(function(c){c.shapeArgs&&(c.shapeArgs.fill=a.pointAttribs(c,c.state).fill)}),a.group=a.transformGroup,z.column.prototype.drawPoints.apply(a),a.group=e,a.points.forEach(function(c){if(c.graphic){var d=
"";c.name&&(d+="highcharts-name-"+c.name.replace(/ /g,"-").toLowerCase());c.properties&&c.properties["hc-key"]&&(d+=" highcharts-key-"+c.properties["hc-key"].toLowerCase());d&&c.graphic.addClass(d);f.styledMode&&c.graphic.css(a.pointAttribs(c,c.selected&&"select"||void 0))}}),this.baseTrans={originX:c.min-c.minPixelPadding/c.transA,originY:b.min-b.minPixelPadding/b.transA+(b.reversed?0:b.len/b.transA),transAX:c.transA,transAY:b.transA},this.transformGroup.animate({translateX:0,translateY:0,scaleX:1,
scaleY:1});else{var p=c.transA/l.transAX;var k=b.transA/l.transAY;var m=c.toPixels(l.originX,!0);var n=b.toPixels(l.originY,!0);.99<p&&1.01>p&&.99<k&&1.01>k&&(k=p=1,m=Math.round(m),n=Math.round(n));var q=this.transformGroup;if(f.renderer.globalAnimation){var r=q.attr("translateX");var B=q.attr("translateY");var y=q.attr("scaleX");var t=q.attr("scaleY");q.attr({animator:0}).animate({animator:1},{step:function(a,c){q.attr({translateX:r+(m-r)*c.pos,translateY:B+(n-B)*c.pos,scaleX:y+(p-y)*c.pos,scaleY:t+
(k-t)*c.pos})}})}else q.attr({translateX:m,translateY:n,scaleX:p,scaleY:k})}f.styledMode||e.element.setAttribute("stroke-width",u(a.options[a.pointAttrToOptions&&a.pointAttrToOptions["stroke-width"]||"borderWidth"],1)/(p||1));this.drawMapDataLabels()},drawMapDataLabels:function(){B.prototype.drawDataLabels.call(this);this.dataLabelsGroup&&this.dataLabelsGroup.clip(this.chart.clipRect)},render:function(){var a=this,c=B.prototype.render;a.chart.renderer.isVML&&3E3<a.data.length?setTimeout(function(){c.call(a)}):
c.call(a)},animate:function(a){var c=this.options.animation,d=this.group,b=this.xAxis,e=this.yAxis,f=b.pos,l=e.pos;this.chart.renderer.isSVG&&(!0===c&&(c={duration:1E3}),a?d.attr({translateX:f+b.len/2,translateY:l+e.len/2,scaleX:.001,scaleY:.001}):d.animate({translateX:f,translateY:l,scaleX:1,scaleY:1},c))},animateDrilldown:function(a){var c=this.chart.plotBox,b=this.chart.drilldownLevels[this.chart.drilldownLevels.length-1],d=b.bBox,e=this.chart.options.drilldown.animation;a||(a=Math.min(d.width/
c.width,d.height/c.height),b.shapeArgs={scaleX:a,scaleY:a,translateX:d.x,translateY:d.y},this.points.forEach(function(a){a.graphic&&a.graphic.attr(b.shapeArgs).animate({scaleX:1,scaleY:1,translateX:0,translateY:0},e)}))},drawLegendSymbol:t.drawRectangle,animateDrillupFrom:function(a){z.column.prototype.animateDrillupFrom.call(this,a)},animateDrillupTo:function(a){z.column.prototype.animateDrillupTo.call(this,a)}}),m({applyOptions:function(a,c){var b=this.series;a=n.prototype.applyOptions.call(this,
a,c);c=b.joinBy;b.mapData&&b.mapMap&&(c=n.prototype.getNestedProperty.call(a,c[1]),(c="undefined"!==typeof c&&b.mapMap[c])?(b.xyFromShape&&(a.x=c._midX,a.y=c._midY),m(a,c)):a.value=a.value||null);return a},onMouseOver:function(a){v.clearTimeout(this.colorInterval);if(null!==this.value||this.series.options.nullInteraction)n.prototype.onMouseOver.call(this,a);else this.series.onMouseOut(a)},zoomTo:function(){var a=this.series;a.xAxis.setExtremes(this._minX,this._maxX,!1);a.yAxis.setExtremes(this._minY,
this._maxY,!1);a.chart.redraw()}},q));""});w(a,"Series/MapLineSeries.js",[a["Core/Series/Series.js"]],function(a){var g=a.seriesTypes;a.seriesType("mapline","map",{lineWidth:1,fillColor:"none"},{type:"mapline",colorProp:"stroke",pointAttrToOptions:{stroke:"color","stroke-width":"lineWidth"},pointAttribs:function(a,q){a=g.map.prototype.pointAttribs.call(this,a,q);a.fill=this.options.fillColor;return a},drawLegendSymbol:g.line.prototype.drawLegendSymbol});""});w(a,"Series/MapPointSeries.js",[a["Core/Series/Series.js"],
a["Core/Globals.js"],a["Core/Series/Point.js"],a["Core/Utilities.js"]],function(a,g,k,t){var b=t.merge,n=g.Series;a.seriesType("mappoint","scatter",{dataLabels:{crop:!1,defer:!1,enabled:!0,formatter:function(){return this.point.name},overflow:!1,style:{color:"#000000"}}},{type:"mappoint",forceDL:!0,drawDataLabels:function(){n.prototype.drawDataLabels.call(this);this.dataLabelsGroup&&this.dataLabelsGroup.clip(this.chart.clipRect)}},{applyOptions:function(a,g){a="undefined"!==typeof a.lat&&"undefined"!==
typeof a.lon?b(a,this.series.chart.fromLatLonToPoint(a)):a;return k.prototype.applyOptions.call(this,a,g)}});""});w(a,"Series/MapBubbleSeries.js",[a["Core/Series/Series.js"],a["Core/Series/Point.js"],a["Core/Utilities.js"]],function(a,g,k){var q=k.merge,b=a.seriesTypes;b.bubble&&a.seriesType("mapbubble","bubble",{animationLimit:500,tooltip:{pointFormat:"{point.name}: {point.z}"}},{xyFromShape:!0,type:"mapbubble",pointArrayMap:["z"],getMapData:b.map.prototype.getMapData,getBox:b.map.prototype.getBox,
setData:b.map.prototype.setData,setOptions:b.map.prototype.setOptions},{applyOptions:function(a,k){return a&&"undefined"!==typeof a.lat&&"undefined"!==typeof a.lon?g.prototype.applyOptions.call(this,q(a,this.series.chart.fromLatLonToPoint(a)),k):b.map.prototype.pointClass.prototype.applyOptions.call(this,a,k)},isValid:function(){return"number"===typeof this.z},ttBelow:!1});""});w(a,"Series/HeatmapSeries.js",[a["Core/Series/Series.js"],a["Mixins/ColorMapSeries.js"],a["Core/Globals.js"],a["Mixins/LegendSymbol.js"],
a["Core/Renderer/SVG/SVGRenderer.js"],a["Core/Utilities.js"]],function(a,g,k,t,b,n){var q=g.colorMapPointMixin;g=g.colorMapSeriesMixin;var v=k.noop,x=n.clamp,l=n.extend,e=n.fireEvent,f=n.isNumber,m=n.merge,F=n.pick,r=k.Series;n=a.seriesTypes;var C=b.prototype.symbols;"";a.seriesType("heatmap","scatter",{animation:!1,borderWidth:0,nullColor:"#f7f7f7",dataLabels:{formatter:function(){return this.point.value},inside:!0,verticalAlign:"middle",crop:!1,overflow:!1,padding:0},marker:{symbol:"rect",radius:0,
lineColor:void 0,states:{hover:{lineWidthPlus:0},select:{}}},clip:!0,pointRange:null,tooltip:{pointFormat:"{point.x}, {point.y}: {point.value}<br/>"},states:{hover:{halo:!1,brightness:.2}}},m(g,{pointArrayMap:["y","value"],hasPointSpecificOptions:!0,getExtremesFromAll:!0,directTouch:!0,init:function(){r.prototype.init.apply(this,arguments);var a=this.options;a.pointRange=F(a.pointRange,a.colsize||1);this.yAxis.axisPointRange=a.rowsize||1;l(C,{ellipse:C.circle,rect:C.square})},getSymbol:r.prototype.getSymbol,
setClip:function(a){var c=this.chart;r.prototype.setClip.apply(this,arguments);(!1!==this.options.clip||a)&&this.markerGroup.clip((a||this.clipBox)&&this.sharedClipKey?c[this.sharedClipKey]:c.clipRect)},translate:function(){var a=this.options,b=a.marker&&a.marker.symbol||"",f=C[b]?b:"rect";a=this.options;var g=-1!==["circle","square"].indexOf(f);this.generatePoints();this.points.forEach(function(a){var c=a.getCellAttributes(),e={x:Math.min(c.x1,c.x2),y:Math.min(c.y1,c.y2),width:Math.max(Math.abs(c.x2-
c.x1),0),height:Math.max(Math.abs(c.y2-c.y1),0)};var d=a.hasImage=0===(a.marker&&a.marker.symbol||b||"").indexOf("url");if(g){var h=Math.abs(e.width-e.height);e.x=Math.min(c.x1,c.x2)+(e.width<e.height?0:h/2);e.y=Math.min(c.y1,c.y2)+(e.width<e.height?h/2:0);e.width=e.height=Math.min(e.width,e.height)}h={plotX:(c.x1+c.x2)/2,plotY:(c.y1+c.y2)/2,clientX:(c.x1+c.x2)/2,shapeType:"path",shapeArgs:m(!0,e,{d:C[f](e.x,e.y,e.width,e.height)})};d&&(a.marker={width:e.width,height:e.height});l(a,h)});e(this,"afterTranslate")},
pointAttribs:function(a,b){var c=r.prototype.pointAttribs.call(this,a,b),e=this.options||{},f=this.chart.options.plotOptions||{},l=f.series||{},g=f.heatmap||{};f=e.borderColor||g.borderColor||l.borderColor;l=e.borderWidth||g.borderWidth||l.borderWidth||c["stroke-width"];c.stroke=a&&a.marker&&a.marker.lineColor||e.marker&&e.marker.lineColor||f||this.color;c["stroke-width"]=l;b&&(a=m(e.states[b],e.marker&&e.marker.states[b],a.options.states&&a.options.states[b]||{}),b=a.brightness,c.fill=a.color||k.color(c.fill).brighten(b||
0).get(),c.stroke=a.lineColor);return c},markerAttribs:function(a,b){var c=a.marker||{},e=this.options.marker||{},f=a.shapeArgs||{},l={};if(a.hasImage)return{x:a.plotX,y:a.plotY};if(b){var g=e.states[b]||{};var d=c.states&&c.states[b]||{};[["width","x"],["height","y"]].forEach(function(a){l[a[0]]=(d[a[0]]||g[a[0]]||f[a[0]])+(d[a[0]+"Plus"]||g[a[0]+"Plus"]||0);l[a[1]]=f[a[1]]+(f[a[0]]-l[a[0]])/2})}return b?l:f},drawPoints:function(){var a=this;if((this.options.marker||{}).enabled||this._hasPointMarkers)r.prototype.drawPoints.call(this),
this.points.forEach(function(c){c.graphic&&c.graphic[a.chart.styledMode?"css":"animate"](a.colorAttribs(c))})},hasData:function(){return!!this.processedXData.length},getValidPoints:function(a,b){return r.prototype.getValidPoints.call(this,a,b,!0)},getBox:v,drawLegendSymbol:t.drawRectangle,alignDataLabel:n.column.prototype.alignDataLabel,getExtremes:function(){var a=r.prototype.getExtremes.call(this,this.valueData),b=a.dataMin;a=a.dataMax;f(b)&&(this.valueMin=b);f(a)&&(this.valueMax=a);return r.prototype.getExtremes.call(this)}}),
m(q,{applyOptions:function(a,b){a=k.Point.prototype.applyOptions.call(this,a,b);a.formatPrefix=a.isNull||null===a.value?"null":"point";return a},isValid:function(){return Infinity!==this.value&&-Infinity!==this.value},haloPath:function(a){if(!a)return[];var c=this.shapeArgs;return["M",c.x-a,c.y-a,"L",c.x-a,c.y+c.height+a,c.x+c.width+a,c.y+c.height+a,c.x+c.width+a,c.y-a,"Z"]},getCellAttributes:function(){var a=this.series,b=a.options,e=(b.colsize||1)/2,f=(b.rowsize||1)/2,l=a.xAxis,g=a.yAxis,k=this.options.marker||
a.options.marker;a=a.pointPlacementToXValue();var d=F(this.pointPadding,b.pointPadding,0),h={x1:x(Math.round(l.len-(l.translate(this.x-e,!1,!0,!1,!0,-a)||0)),-l.len,2*l.len),x2:x(Math.round(l.len-(l.translate(this.x+e,!1,!0,!1,!0,-a)||0)),-l.len,2*l.len),y1:x(Math.round(g.translate(this.y-f,!1,!0,!1,!0)||0),-g.len,2*g.len),y2:x(Math.round(g.translate(this.y+f,!1,!0,!1,!0)||0),-g.len,2*g.len)};[["width","x"],["height","y"]].forEach(function(a){var c=a[0];a=a[1];var b=a+"1",e=a+"2",f=Math.abs(h[b]-
h[e]),l=k&&k.lineWidth||0,g=Math.abs(h[b]+h[e])/2;k[c]&&k[c]<f&&(h[b]=g-k[c]/2-l/2,h[e]=g+k[c]/2+l/2);d&&("y"===a&&(b=e,e=a+"1"),h[b]+=d,h[e]-=d)});return h}}));""});w(a,"Extensions/GeoJSON.js",[a["Core/Chart/Chart.js"],a["Core/Globals.js"],a["Core/Utilities.js"]],function(a,g,k){function q(a,b){var e,g=!1,l=a.x,k=a.y;a=0;for(e=b.length-1;a<b.length;e=a++){var n=b[a][1]>k;var c=b[e][1]>k;n!==c&&l<(b[e][0]-b[a][0])*(k-b[a][1])/(b[e][1]-b[a][1])+b[a][0]&&(g=!g)}return g}var b=g.win,n=k.error,w=k.extend,
v=k.format,x=k.merge;k=k.wrap;"";a.prototype.transformFromLatLon=function(a,e){var f,g=(null===(f=this.userOptions.chart)||void 0===f?void 0:f.proj4)||b.proj4;if(!g)return n(21,!1,this),{x:0,y:null};a=g(e.crs,[a.lon,a.lat]);f=e.cosAngle||e.rotation&&Math.cos(e.rotation);g=e.sinAngle||e.rotation&&Math.sin(e.rotation);a=e.rotation?[a[0]*f+a[1]*g,-a[0]*g+a[1]*f]:a;return{x:((a[0]-(e.xoffset||0))*(e.scale||1)+(e.xpan||0))*(e.jsonres||1)+(e.jsonmarginX||0),y:(((e.yoffset||0)-a[1])*(e.scale||1)+(e.ypan||
0))*(e.jsonres||1)-(e.jsonmarginY||0)}};a.prototype.transformToLatLon=function(a,e){if("undefined"===typeof b.proj4)n(21,!1,this);else{a={x:((a.x-(e.jsonmarginX||0))/(e.jsonres||1)-(e.xpan||0))/(e.scale||1)+(e.xoffset||0),y:((-a.y-(e.jsonmarginY||0))/(e.jsonres||1)+(e.ypan||0))/(e.scale||1)+(e.yoffset||0)};var f=e.cosAngle||e.rotation&&Math.cos(e.rotation),g=e.sinAngle||e.rotation&&Math.sin(e.rotation);e=b.proj4(e.crs,"WGS84",e.rotation?{x:a.x*f+a.y*-g,y:a.x*g+a.y*f}:a);return{lat:e.y,lon:e.x}}};
a.prototype.fromPointToLatLon=function(a){var b=this.mapTransforms,f;if(b){for(f in b)if(Object.hasOwnProperty.call(b,f)&&b[f].hitZone&&q({x:a.x,y:-a.y},b[f].hitZone.coordinates[0]))return this.transformToLatLon(a,b[f]);return this.transformToLatLon(a,b["default"])}n(22,!1,this)};a.prototype.fromLatLonToPoint=function(a){var b=this.mapTransforms,f;if(!b)return n(22,!1,this),{x:0,y:null};for(f in b)if(Object.hasOwnProperty.call(b,f)&&b[f].hitZone){var g=this.transformFromLatLon(a,b[f]);if(q({x:g.x,
y:-g.y},b[f].hitZone.coordinates[0]))return g}return this.transformFromLatLon(a,b["default"])};g.geojson=function(a,b,f){var e=[],g=[],k=function(a){a.forEach(function(a,b){0===b?g.push(["M",a[0],-a[1]]):g.push(["L",a[0],-a[1]])})};b=b||"map";a.features.forEach(function(a){var c=a.geometry,f=c.type;c=c.coordinates;a=a.properties;var l;g=[];"map"===b||"mapbubble"===b?("Polygon"===f?(c.forEach(k),g.push(["Z"])):"MultiPolygon"===f&&(c.forEach(function(a){a.forEach(k)}),g.push(["Z"])),g.length&&(l={path:g})):
"mapline"===b?("LineString"===f?k(c):"MultiLineString"===f&&c.forEach(k),g.length&&(l={path:g})):"mappoint"===b&&"Point"===f&&(l={x:c[0],y:-c[1]});l&&e.push(w(l,{name:a.name||a.NAME,properties:a}))});f&&a.copyrightShort&&(f.chart.mapCredits=v(f.chart.options.credits.mapText,{geojson:a}),f.chart.mapCreditsFull=v(f.chart.options.credits.mapTextFull,{geojson:a}));return e};k(a.prototype,"addCredits",function(a,b){b=x(!0,this.options.credits,b);this.mapCredits&&(b.href=null);a.call(this,b);this.credits&&
this.mapCreditsFull&&this.credits.attr({title:this.mapCreditsFull})})});w(a,"masters/modules/map.src.js",[],function(){})});
//# sourceMappingURL=map.js.map