/*
 Highstock JS v8.2.0 (2020-10-07)

 Indicator series type for Highstock

 (c) 2010-2019 Daniel Studencki

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/indicators/acceleration-bands",["highcharts","highcharts/modules/stock"],function(e){a(e);a.Highcharts=e;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function e(a,h,l,f){a.hasOwnProperty(h)||(a[h]=f.apply(null,l))}a=a?a._modules:{};e(a,"Mixins/MultipleLines.js",[a["Core/Globals.js"],a["Core/Utilities.js"]],function(a,h){var l=
h.defined,f=h.error,x=h.merge,b=a.seriesTypes.sma;return{pointArrayMap:["top","bottom"],pointValKey:"top",linesApiNames:["bottomLine"],getTranslatedLinesNames:function(k){var a=[];(this.pointArrayMap||[]).forEach(function(b){b!==k&&a.push("plot"+b.charAt(0).toUpperCase()+b.slice(1))});return a},toYData:function(k){var a=[];(this.pointArrayMap||[]).forEach(function(b){a.push(k[b])});return a},translate:function(){var k=this,a=k.pointArrayMap,f=[],l;f=k.getTranslatedLinesNames();b.prototype.translate.apply(k,
arguments);k.points.forEach(function(b){a.forEach(function(a,h){l=b[a];null!==l&&(b[f[h]]=k.yAxis.toPixels(l,!0))})})},drawGraph:function(){var a=this,h=a.linesApiNames,e=a.points,r=e.length,m=a.options,n=a.graph,p={options:{gapSize:m.gapSize}},q=[],d;a.getTranslatedLinesNames(a.pointValKey).forEach(function(a,g){for(q[g]=[];r--;)d=e[r],q[g].push({x:d.x,plotX:d.plotX,plotY:d[a],isNull:!l(d[a])});r=e.length});h.forEach(function(d,g){q[g]?(a.points=q[g],m[d]?a.options=x(m[d].styles,p):f('Error: "There is no '+
d+' in DOCS options declared. Check if linesApiNames are consistent with your DOCS line names." at mixin/multiple-line.js:34'),a.graph=a["graph"+d],b.prototype.drawGraph.call(a),a["graph"+d]=a.graph):f('Error: "'+d+" doesn't have equivalent in pointArrayMap. To many elements in linesApiNames relative to pointArrayMap.\"")});a.points=e;a.options=m;a.graph=n;b.prototype.drawGraph.call(a)}}});e(a,"Mixins/IndicatorRequired.js",[a["Core/Utilities.js"]],function(a){var h=a.error;return{isParentLoaded:function(a,
f,e,b,k){if(a)return b?b(a):!0;h(k||this.generateMessage(e,f));return!1},generateMessage:function(a,f){return'Error: "'+a+'" indicator type requires "'+f+'" indicator loaded before. Please read docs: https://api.highcharts.com/highstock/plotOptions.'+a}}});e(a,"Stock/Indicators/SMAIndicator.js",[a["Core/Series/Series.js"],a["Core/Globals.js"],a["Mixins/IndicatorRequired.js"],a["Core/Utilities.js"]],function(a,h,e,f){var l=a.seriesTypes,b=f.addEvent,k=f.error,w=f.extend,r=f.isArray,y=f.pick,m=f.splat,
n=h.Series,p=l.ohlc.prototype,q=e.generateMessage;b(h.Series,"init",function(a){a=a.options;a.useOhlcData&&"highcharts-navigator-series"!==a.id&&w(this,{pointValKey:p.pointValKey,keys:p.keys,pointArrayMap:p.pointArrayMap,toYData:p.toYData})});b(n,"afterSetOptions",function(a){a=a.options;var d=a.dataGrouping;d&&a.useOhlcData&&"highcharts-navigator-series"!==a.id&&(d.approximation="ohlc")});a.seriesType("sma","line",{name:void 0,tooltip:{valueDecimals:4},linkedTo:void 0,compareToMain:!1,params:{index:0,
period:14}},{processData:function(){var a=this.options.compareToMain,b=this.linkedParent;n.prototype.processData.apply(this,arguments);b&&b.compareValue&&a&&(this.compareValue=b.compareValue)},bindTo:{series:!0,eventName:"updatedData"},hasDerivedData:!0,useCommonDataGrouping:!0,nameComponents:["period"],nameSuffixes:[],calculateOn:"init",requiredIndicators:[],requireIndicators:function(){var a={allLoaded:!0};this.requiredIndicators.forEach(function(d){l[d]?l[d].prototype.requireIndicators():(a.allLoaded=
!1,a.needed=d)});return a},init:function(a,f){function d(){var a=c.points||[],d=(c.xData||[]).length,b=c.getValues(c.linkedParent,c.options.params)||{values:[],xData:[],yData:[]},g=[],f=!0;if(d&&!c.hasGroupedData&&c.visible&&c.points)if(c.cropped){if(c.xAxis){var e=c.xAxis.min;var k=c.xAxis.max}d=c.cropData(b.xData,b.yData,e,k);for(e=0;e<d.xData.length;e++)g.push([d.xData[e]].concat(m(d.yData[e])));d=b.xData.indexOf(c.xData[0]);e=b.xData.indexOf(c.xData[c.xData.length-1]);-1===d&&e===b.xData.length-
2&&g[0][0]===a[0].x&&g.shift();c.updateData(g)}else b.xData.length!==d-1&&b.xData.length!==d+1&&(f=!1,c.updateData(b.values));f&&(c.xData=b.xData,c.yData=b.yData,c.options.data=b.values);!1===c.bindTo.series&&(delete c.processedXData,c.isDirty=!0,c.redraw());c.isDirtyData=!1}var c=this,e=c.requireIndicators();if(!e.allLoaded)return k(q(c.type,e.needed));n.prototype.init.call(c,a,f);a.linkSeries();c.dataEventsToUnbind=[];if(!c.linkedParent)return k("Series "+c.options.linkedTo+" not found! Check `linkedTo`.",
!1,a);c.dataEventsToUnbind.push(b(c.bindTo.series?c.linkedParent:c.linkedParent.xAxis,c.bindTo.eventName,d));if("init"===c.calculateOn)d();else var h=b(c.chart,c.calculateOn,function(){d();h()});return c},getName:function(){var a=this.name,b=[];a||((this.nameComponents||[]).forEach(function(a,c){b.push(this.options.params[a]+y(this.nameSuffixes[c],""))},this),a=(this.nameBase||this.type.toUpperCase())+(this.nameComponents?" ("+b.join(", ")+")":""));return a},getValues:function(a,b){var d=b.period,
c=a.xData;a=a.yData;var e=a.length,f=0,k=0,h=[],l=[],w=[],m=-1;if(!(c.length<d)){for(r(a[0])&&(m=b.index?b.index:0);f<d-1;)k+=0>m?a[f]:a[f][m],f++;for(b=f;b<e;b++){k+=0>m?a[b]:a[b][m];var n=[c[b],k/d];h.push(n);l.push(n[0]);w.push(n[1]);k-=0>m?a[b-f]:a[b-f][m]}return{values:h,xData:l,yData:w}}},destroy:function(){this.dataEventsToUnbind.forEach(function(a){a()});n.prototype.destroy.apply(this,arguments)}});""});e(a,"Stock/Indicators/ABIndicator.js",[a["Core/Series/Series.js"],a["Mixins/MultipleLines.js"],
a["Core/Utilities.js"]],function(a,e,l){var f=l.correctFloat;l=l.merge;var h=a.seriesTypes.sma;a.seriesType("abands","sma",{params:{period:20,factor:.001,index:3},lineWidth:1,topLine:{styles:{lineWidth:1}},bottomLine:{styles:{lineWidth:1}},dataGrouping:{approximation:"averages"}},l(e,{pointArrayMap:["top","middle","bottom"],pointValKey:"middle",nameBase:"Acceleration Bands",nameComponents:["period","factor"],linesApiNames:["topLine","bottomLine"],getValues:function(a,e){var b=e.period,k=e.factor;
e=e.index;var l=a.xData,m=(a=a.yData)?a.length:0,n=[],p=[],q=[],d=[],r=[],g;if(!(m<b)){for(g=0;g<=m;g++){if(g<m){var c=a[g][2];var u=a[g][1];var v=k;c=f(u-c)/(f(u+c)/2)*1E3*v;n.push(a[g][1]*f(1+2*c));p.push(a[g][2]*f(1-2*c))}if(g>=b){c=l.slice(g-b,g);var t=a.slice(g-b,g);v=h.prototype.getValues.call(this,{xData:c,yData:n.slice(g-b,g)},{period:b});u=h.prototype.getValues.call(this,{xData:c,yData:p.slice(g-b,g)},{period:b});t=h.prototype.getValues.call(this,{xData:c,yData:t},{period:b,index:e});c=t.xData[0];
v=v.yData[0];u=u.yData[0];t=t.yData[0];q.push([c,v,t,u]);d.push(c);r.push([v,t,u])}}return{values:q,xData:d,yData:r}}}}));""});e(a,"masters/indicators/acceleration-bands.src.js",[],function(){})});
//# sourceMappingURL=acceleration-bands.js.map