/*
 Highstock JS v8.2.0 (2020-10-07)

 Indicator series type for Highstock

 (c) 2010-2019 Wojciech Chmiel

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/indicators/ao",["highcharts","highcharts/modules/stock"],function(f){a(f);a.Highcharts=f;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function f(a,p,q,d){a.hasOwnProperty(p)||(a[p]=d.apply(null,q))}a=a?a._modules:{};f(a,"Mixins/IndicatorRequired.js",[a["Core/Utilities.js"]],function(a){var p=a.error;return{isParentLoaded:function(a,
d,f,e,m){if(a)return e?e(a):!0;p(m||this.generateMessage(f,d));return!1},generateMessage:function(a,d){return'Error: "'+a+'" indicator type requires "'+d+'" indicator loaded before. Please read docs: https://api.highcharts.com/highstock/plotOptions.'+a}}});f(a,"Stock/Indicators/SMAIndicator.js",[a["Core/Series/Series.js"],a["Core/Globals.js"],a["Mixins/IndicatorRequired.js"],a["Core/Utilities.js"]],function(a,p,f,d){var t=a.seriesTypes,e=d.addEvent,m=d.error,u=d.extend,g=d.isArray,q=d.pick,r=d.splat,
k=p.Series,l=t.ohlc.prototype,h=f.generateMessage;e(p.Series,"init",function(c){c=c.options;c.useOhlcData&&"highcharts-navigator-series"!==c.id&&u(this,{pointValKey:l.pointValKey,keys:l.keys,pointArrayMap:l.pointArrayMap,toYData:l.toYData})});e(k,"afterSetOptions",function(c){c=c.options;var a=c.dataGrouping;a&&c.useOhlcData&&"highcharts-navigator-series"!==c.id&&(a.approximation="ohlc")});a.seriesType("sma","line",{name:void 0,tooltip:{valueDecimals:4},linkedTo:void 0,compareToMain:!1,params:{index:0,
period:14}},{processData:function(){var c=this.options.compareToMain,a=this.linkedParent;k.prototype.processData.apply(this,arguments);a&&a.compareValue&&c&&(this.compareValue=a.compareValue)},bindTo:{series:!0,eventName:"updatedData"},hasDerivedData:!0,useCommonDataGrouping:!0,nameComponents:["period"],nameSuffixes:[],calculateOn:"init",requiredIndicators:[],requireIndicators:function(){var c={allLoaded:!0};this.requiredIndicators.forEach(function(a){t[a]?t[a].prototype.requireIndicators():(c.allLoaded=
!1,c.needed=a)});return c},init:function(c,a){function d(){var c=b.points||[],a=(b.xData||[]).length,e=b.getValues(b.linkedParent,b.options.params)||{values:[],xData:[],yData:[]},d=[],n=!0;if(a&&!b.hasGroupedData&&b.visible&&b.points)if(b.cropped){if(b.xAxis){var g=b.xAxis.min;var m=b.xAxis.max}a=b.cropData(e.xData,e.yData,g,m);for(g=0;g<a.xData.length;g++)d.push([a.xData[g]].concat(r(a.yData[g])));a=e.xData.indexOf(b.xData[0]);g=e.xData.indexOf(b.xData[b.xData.length-1]);-1===a&&g===e.xData.length-
2&&d[0][0]===c[0].x&&d.shift();b.updateData(d)}else e.xData.length!==a-1&&e.xData.length!==a+1&&(n=!1,b.updateData(e.values));n&&(b.xData=e.xData,b.yData=e.yData,b.options.data=e.values);!1===b.bindTo.series&&(delete b.processedXData,b.isDirty=!0,b.redraw());b.isDirtyData=!1}var b=this,n=b.requireIndicators();if(!n.allLoaded)return m(h(b.type,n.needed));k.prototype.init.call(b,c,a);c.linkSeries();b.dataEventsToUnbind=[];if(!b.linkedParent)return m("Series "+b.options.linkedTo+" not found! Check `linkedTo`.",
!1,c);b.dataEventsToUnbind.push(e(b.bindTo.series?b.linkedParent:b.linkedParent.xAxis,b.bindTo.eventName,d));if("init"===b.calculateOn)d();else var g=e(b.chart,b.calculateOn,function(){d();g()});return b},getName:function(){var a=this.name,e=[];a||((this.nameComponents||[]).forEach(function(a,c){e.push(this.options.params[a]+q(this.nameSuffixes[c],""))},this),a=(this.nameBase||this.type.toUpperCase())+(this.nameComponents?" ("+e.join(", ")+")":""));return a},getValues:function(a,e){var c=e.period,
b=a.xData;a=a.yData;var d=a.length,m=0,h=0,p=[],k=[],l=[],f=-1;if(!(b.length<c)){for(g(a[0])&&(f=e.index?e.index:0);m<c-1;)h+=0>f?a[m]:a[m][f],m++;for(e=m;e<d;e++){h+=0>f?a[e]:a[e][f];var n=[b[e],h/c];p.push(n);k.push(n[0]);l.push(n[1]);h-=0>f?a[e-m]:a[e-m][f]}return{values:p,xData:k,yData:l}}},destroy:function(){this.dataEventsToUnbind.forEach(function(a){a()});k.prototype.destroy.apply(this,arguments)}});""});f(a,"Stock/Indicators/AOIndicator.js",[a["Core/Series/Series.js"],a["Core/Globals.js"],
a["Core/Utilities.js"]],function(a,f,q){var d=q.correctFloat,p=q.isArray;a.seriesType("ao","sma",{greaterBarColor:"#06B535",lowerBarColor:"#F21313",threshold:0,groupPadding:.2,pointPadding:.2,crisp:!1,states:{hover:{halo:{size:0}}}},{nameBase:"AO",nameComponents:!1,markerAttribs:f.noop,getColumnMetrics:f.seriesTypes.column.prototype.getColumnMetrics,crispCol:f.seriesTypes.column.prototype.crispCol,translate:f.seriesTypes.column.prototype.translate,drawPoints:f.seriesTypes.column.prototype.drawPoints,
drawGraph:function(){var a=this.options,d=this.points,f=a.greaterBarColor;a=a.lowerBarColor;var g=d[0];if(!this.userOptions.color&&g)for(g.color=f,g=1;g<d.length;g++)d[g].color=d[g].y>d[g-1].y?f:d[g].y<d[g-1].y?a:d[g-1].color},getValues:function(a){var e=a.xData||[];a=a.yData||[];var f=a.length,g=[],q=[],r=[],k=0,l=0,h;if(!(34>=e.length)&&p(a[0])&&4===a[0].length){for(h=0;33>h;h++){var c=(a[h][1]+a[h][2])/2;29<=h&&(k=d(k+c));l=d(l+c)}for(h=33;h<f;h++){c=(a[h][1]+a[h][2])/2;k=d(k+c);l=d(l+c);c=k/5;
var n=l/34;c=d(c-n);g.push([e[h],c]);q.push(e[h]);r.push(c);c=h+1-5;n=h+1-34;k=d(k-(a[c][1]+a[c][2])/2);l=d(l-(a[n][1]+a[n][2])/2)}return{values:g,xData:q,yData:r}}}});""});f(a,"masters/indicators/ao.src.js",[],function(){})});
//# sourceMappingURL=ao.js.map