/*
 Highstock JS v8.2.0 (2020-10-07)

 Indicator series type for Highstock

 (c) 2010-2019 Wojciech Chmiel

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/indicators/aroon",["highcharts","highcharts/modules/stock"],function(k){a(k);a.Highcharts=k;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function k(a,f,r,e){a.hasOwnProperty(f)||(a[f]=e.apply(null,r))}a=a?a._modules:{};k(a,"Mixins/MultipleLines.js",[a["Core/Globals.js"],a["Core/Utilities.js"]],function(a,f){var r=f.defined,
e=f.error,p=f.merge,n=a.seriesTypes.sma;return{pointArrayMap:["top","bottom"],pointValKey:"top",linesApiNames:["bottomLine"],getTranslatedLinesNames:function(b){var a=[];(this.pointArrayMap||[]).forEach(function(h){h!==b&&a.push("plot"+h.charAt(0).toUpperCase()+h.slice(1))});return a},toYData:function(b){var a=[];(this.pointArrayMap||[]).forEach(function(h){a.push(b[h])});return a},translate:function(){var b=this,a=b.pointArrayMap,h=[],e;h=b.getTranslatedLinesNames();n.prototype.translate.apply(b,
arguments);b.points.forEach(function(g){a.forEach(function(a,r){e=g[a];null!==e&&(g[h[r]]=b.yAxis.toPixels(e,!0))})})},drawGraph:function(){var b=this,a=b.linesApiNames,h=b.points,f=h.length,g=b.options,t=b.graph,u={options:{gapSize:g.gapSize}},l=[],c;b.getTranslatedLinesNames(b.pointValKey).forEach(function(b,a){for(l[a]=[];f--;)c=h[f],l[a].push({x:c.x,plotX:c.plotX,plotY:c[b],isNull:!r(c[b])});f=h.length});a.forEach(function(c,a){l[a]?(b.points=l[a],g[c]?b.options=p(g[c].styles,u):e('Error: "There is no '+
c+' in DOCS options declared. Check if linesApiNames are consistent with your DOCS line names." at mixin/multiple-line.js:34'),b.graph=b["graph"+c],n.prototype.drawGraph.call(b),b["graph"+c]=b.graph):e('Error: "'+c+" doesn't have equivalent in pointArrayMap. To many elements in linesApiNames relative to pointArrayMap.\"")});b.points=h;b.options=g;b.graph=t;n.prototype.drawGraph.call(b)}}});k(a,"Mixins/IndicatorRequired.js",[a["Core/Utilities.js"]],function(a){var f=a.error;return{isParentLoaded:function(a,
e,p,n,b){if(a)return n?n(a):!0;f(b||this.generateMessage(p,e));return!1},generateMessage:function(a,e){return'Error: "'+a+'" indicator type requires "'+e+'" indicator loaded before. Please read docs: https://api.highcharts.com/highstock/plotOptions.'+a}}});k(a,"Stock/Indicators/SMAIndicator.js",[a["Core/Series/Series.js"],a["Core/Globals.js"],a["Mixins/IndicatorRequired.js"],a["Core/Utilities.js"]],function(a,f,r,e){var p=a.seriesTypes,n=e.addEvent,b=e.error,q=e.extend,h=e.isArray,k=e.pick,g=e.splat,
t=f.Series,u=p.ohlc.prototype,l=r.generateMessage;n(f.Series,"init",function(a){a=a.options;a.useOhlcData&&"highcharts-navigator-series"!==a.id&&q(this,{pointValKey:u.pointValKey,keys:u.keys,pointArrayMap:u.pointArrayMap,toYData:u.toYData})});n(t,"afterSetOptions",function(a){a=a.options;var c=a.dataGrouping;c&&a.useOhlcData&&"highcharts-navigator-series"!==a.id&&(c.approximation="ohlc")});a.seriesType("sma","line",{name:void 0,tooltip:{valueDecimals:4},linkedTo:void 0,compareToMain:!1,params:{index:0,
period:14}},{processData:function(){var a=this.options.compareToMain,b=this.linkedParent;t.prototype.processData.apply(this,arguments);b&&b.compareValue&&a&&(this.compareValue=b.compareValue)},bindTo:{series:!0,eventName:"updatedData"},hasDerivedData:!0,useCommonDataGrouping:!0,nameComponents:["period"],nameSuffixes:[],calculateOn:"init",requiredIndicators:[],requireIndicators:function(){var a={allLoaded:!0};this.requiredIndicators.forEach(function(b){p[b]?p[b].prototype.requireIndicators():(a.allLoaded=
!1,a.needed=b)});return a},init:function(a,h){function c(){var a=d.points||[],b=(d.xData||[]).length,c=d.getValues(d.linkedParent,d.options.params)||{values:[],xData:[],yData:[]},e=[],h=!0;if(b&&!d.hasGroupedData&&d.visible&&d.points)if(d.cropped){if(d.xAxis){var m=d.xAxis.min;var f=d.xAxis.max}b=d.cropData(c.xData,c.yData,m,f);for(m=0;m<b.xData.length;m++)e.push([b.xData[m]].concat(g(b.yData[m])));b=c.xData.indexOf(d.xData[0]);m=c.xData.indexOf(d.xData[d.xData.length-1]);-1===b&&m===c.xData.length-
2&&e[0][0]===a[0].x&&e.shift();d.updateData(e)}else c.xData.length!==b-1&&c.xData.length!==b+1&&(h=!1,d.updateData(c.values));h&&(d.xData=c.xData,d.yData=c.yData,d.options.data=c.values);!1===d.bindTo.series&&(delete d.processedXData,d.isDirty=!0,d.redraw());d.isDirtyData=!1}var d=this,e=d.requireIndicators();if(!e.allLoaded)return b(l(d.type,e.needed));t.prototype.init.call(d,a,h);a.linkSeries();d.dataEventsToUnbind=[];if(!d.linkedParent)return b("Series "+d.options.linkedTo+" not found! Check `linkedTo`.",
!1,a);d.dataEventsToUnbind.push(n(d.bindTo.series?d.linkedParent:d.linkedParent.xAxis,d.bindTo.eventName,c));if("init"===d.calculateOn)c();else var m=n(d.chart,d.calculateOn,function(){c();m()});return d},getName:function(){var a=this.name,b=[];a||((this.nameComponents||[]).forEach(function(a,c){b.push(this.options.params[a]+k(this.nameSuffixes[c],""))},this),a=(this.nameBase||this.type.toUpperCase())+(this.nameComponents?" ("+b.join(", ")+")":""));return a},getValues:function(a,b){var c=b.period,
d=a.xData;a=a.yData;var e=a.length,g=0,f=0,l=[],m=[],n=[],q=-1;if(!(d.length<c)){for(h(a[0])&&(q=b.index?b.index:0);g<c-1;)f+=0>q?a[g]:a[g][q],g++;for(b=g;b<e;b++){f+=0>q?a[b]:a[b][q];var k=[d[b],f/c];l.push(k);m.push(k[0]);n.push(k[1]);f-=0>q?a[b-g]:a[b-g][q]}return{values:l,xData:m,yData:n}}},destroy:function(){this.dataEventsToUnbind.forEach(function(a){a()});t.prototype.destroy.apply(this,arguments)}});""});k(a,"Stock/Indicators/AroonIndicator.js",[a["Core/Series/Series.js"],a["Mixins/MultipleLines.js"],
a["Core/Utilities.js"]],function(a,f,k){function e(a,e){var b=a[0],f=0,g;for(g=1;g<a.length;g++)if("max"===e&&a[g]>=b||"min"===e&&a[g]<=b)b=a[g],f=g;return f}var p=k.merge,n=k.pick;a.seriesType("aroon","sma",{params:{period:25},marker:{enabled:!1},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>Aroon Up: {point.y}<br/>Aroon Down: {point.aroonDown}<br/>'},aroonDown:{styles:{lineWidth:1,lineColor:void 0}},dataGrouping:{approximation:"averages"}},p(f,{nameBase:"Aroon",
pointArrayMap:["y","aroonDown"],pointValKey:"y",linesApiNames:["aroonDown"],getValues:function(a,f){f=f.period;var b=a.xData,k=(a=a.yData)?a.length:0,g=[],p=[],q=[],l;for(l=f-1;l<k;l++){var c=a.slice(l-f+1,l+2);var m=e(c.map(function(a){return n(a[2],a)}),"min");c=e(c.map(function(a){return n(a[1],a)}),"max");c=c/f*100;m=m/f*100;b[l+1]&&(g.push([b[l+1],c,m]),p.push(b[l+1]),q.push([c,m]))}return{values:g,xData:p,yData:q}}}));""});k(a,"masters/indicators/aroon.src.js",[],function(){})});
//# sourceMappingURL=aroon.js.map