/*
 Highstock JS v8.2.0 (2020-10-07)

 Indicator series type for Highstock

 (c) 2010-2019 Sebastian Bochan

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/indicators/atr",["highcharts","highcharts/modules/stock"],function(g){a(g);a.Highcharts=g;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function g(a,k,r,f){a.hasOwnProperty(k)||(a[k]=f.apply(null,r))}a=a?a._modules:{};g(a,"Mixins/IndicatorRequired.js",[a["Core/Utilities.js"]],function(a){var k=a.error;return{isParentLoaded:function(a,
f,c,e,n){if(a)return e?e(a):!0;k(n||this.generateMessage(c,f));return!1},generateMessage:function(a,f){return'Error: "'+a+'" indicator type requires "'+f+'" indicator loaded before. Please read docs: https://api.highcharts.com/highstock/plotOptions.'+a}}});g(a,"Stock/Indicators/SMAIndicator.js",[a["Core/Series/Series.js"],a["Core/Globals.js"],a["Mixins/IndicatorRequired.js"],a["Core/Utilities.js"]],function(a,k,g,f){var c=a.seriesTypes,e=f.addEvent,n=f.error,r=f.extend,t=f.isArray,l=f.pick,v=f.splat,
m=k.Series,h=c.ohlc.prototype,u=g.generateMessage;e(k.Series,"init",function(d){d=d.options;d.useOhlcData&&"highcharts-navigator-series"!==d.id&&r(this,{pointValKey:h.pointValKey,keys:h.keys,pointArrayMap:h.pointArrayMap,toYData:h.toYData})});e(m,"afterSetOptions",function(d){d=d.options;var a=d.dataGrouping;a&&d.useOhlcData&&"highcharts-navigator-series"!==d.id&&(a.approximation="ohlc")});a.seriesType("sma","line",{name:void 0,tooltip:{valueDecimals:4},linkedTo:void 0,compareToMain:!1,params:{index:0,
period:14}},{processData:function(){var d=this.options.compareToMain,a=this.linkedParent;m.prototype.processData.apply(this,arguments);a&&a.compareValue&&d&&(this.compareValue=a.compareValue)},bindTo:{series:!0,eventName:"updatedData"},hasDerivedData:!0,useCommonDataGrouping:!0,nameComponents:["period"],nameSuffixes:[],calculateOn:"init",requiredIndicators:[],requireIndicators:function(){var d={allLoaded:!0};this.requiredIndicators.forEach(function(a){c[a]?c[a].prototype.requireIndicators():(d.allLoaded=
!1,d.needed=a)});return d},init:function(d,a){function c(){var d=b.points||[],a=(b.xData||[]).length,c=b.getValues(b.linkedParent,b.options.params)||{values:[],xData:[],yData:[]},e=[],q=!0;if(a&&!b.hasGroupedData&&b.visible&&b.points)if(b.cropped){if(b.xAxis){var f=b.xAxis.min;var p=b.xAxis.max}a=b.cropData(c.xData,c.yData,f,p);for(f=0;f<a.xData.length;f++)e.push([a.xData[f]].concat(v(a.yData[f])));a=c.xData.indexOf(b.xData[0]);f=c.xData.indexOf(b.xData[b.xData.length-1]);-1===a&&f===c.xData.length-
2&&e[0][0]===d[0].x&&e.shift();b.updateData(e)}else c.xData.length!==a-1&&c.xData.length!==a+1&&(q=!1,b.updateData(c.values));q&&(b.xData=c.xData,b.yData=c.yData,b.options.data=c.values);!1===b.bindTo.series&&(delete b.processedXData,b.isDirty=!0,b.redraw());b.isDirtyData=!1}var b=this,q=b.requireIndicators();if(!q.allLoaded)return n(u(b.type,q.needed));m.prototype.init.call(b,d,a);d.linkSeries();b.dataEventsToUnbind=[];if(!b.linkedParent)return n("Series "+b.options.linkedTo+" not found! Check `linkedTo`.",
!1,d);b.dataEventsToUnbind.push(e(b.bindTo.series?b.linkedParent:b.linkedParent.xAxis,b.bindTo.eventName,c));if("init"===b.calculateOn)c();else var f=e(b.chart,b.calculateOn,function(){c();f()});return b},getName:function(){var a=this.name,c=[];a||((this.nameComponents||[]).forEach(function(a,d){c.push(this.options.params[a]+l(this.nameSuffixes[d],""))},this),a=(this.nameBase||this.type.toUpperCase())+(this.nameComponents?" ("+c.join(", ")+")":""));return a},getValues:function(a,c){var d=c.period,
b=a.xData;a=a.yData;var f=a.length,e=0,n=0,g=[],k=[],m=[],h=-1;if(!(b.length<d)){for(t(a[0])&&(h=c.index?c.index:0);e<d-1;)n+=0>h?a[e]:a[e][h],e++;for(c=e;c<f;c++){n+=0>h?a[c]:a[c][h];var l=[b[c],n/d];g.push(l);k.push(l[0]);m.push(l[1]);n-=0>h?a[c-e]:a[c-e][h]}return{values:g,xData:k,yData:m}}},destroy:function(){this.dataEventsToUnbind.forEach(function(a){a()});m.prototype.destroy.apply(this,arguments)}});""});g(a,"Stock/Indicators/ATRIndicator.js",[a["Core/Series/Series.js"],a["Core/Utilities.js"]],
function(a,g){function k(a,e){return Math.max(a[1]-a[2],"undefined"===typeof e?0:Math.abs(a[1]-e[3]),"undefined"===typeof e?0:Math.abs(a[2]-e[3]))}var f=g.isArray;a.seriesType("atr","sma",{params:{period:14}},{getValues:function(a,e){e=e.period;var c=a.xData,g=(a=a.yData)?a.length:0,t=1,l=0,v=0,m=[],h=[],u=[],d;var q=[[c[0],a[0]]];if(!(c.length<=e)&&f(a[0])&&4===a[0].length){for(d=1;d<=g;d++)if(q.push([c[d],a[d]]),e<t){var p=e;var b=c[d-1],r=k(a[d-1],a[d-2]);p=[b,(l*(p-1)+r)/p];l=p[1];m.push(p);h.push(p[0]);
u.push(p[1])}else e===t?(l=v/(d-1),m.push([c[d-1],l]),h.push(c[d-1]),u.push(l)):v+=k(a[d-1],a[d-2]),t++;return{values:m,xData:h,yData:u}}}});""});g(a,"masters/indicators/atr.src.js",[],function(){})});
//# sourceMappingURL=atr.js.map