/*
 Highstock JS v8.2.0 (2020-10-07)

 Indicator series type for Highstock

 (c) 2010-2019 Sebastian Bochan

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/indicators/cci",["highcharts","highcharts/modules/stock"],function(h){a(h);a.Highcharts=h;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function h(a,m,r,e){a.hasOwnProperty(m)||(a[m]=e.apply(null,r))}a=a?a._modules:{};h(a,"Mixins/IndicatorRequired.js",[a["Core/Utilities.js"]],function(a){var m=a.error;return{isParentLoaded:function(a,
e,f,g,n){if(a)return g?g(a):!0;m(n||this.generateMessage(f,e));return!1},generateMessage:function(a,e){return'Error: "'+a+'" indicator type requires "'+e+'" indicator loaded before. Please read docs: https://api.highcharts.com/highstock/plotOptions.'+a}}});h(a,"Stock/Indicators/SMAIndicator.js",[a["Core/Series/Series.js"],a["Core/Globals.js"],a["Mixins/IndicatorRequired.js"],a["Core/Utilities.js"]],function(a,m,h,e){var f=a.seriesTypes,g=e.addEvent,n=e.error,r=e.extend,t=e.isArray,l=e.pick,u=e.splat,
p=m.Series,q=f.ohlc.prototype,k=h.generateMessage;g(m.Series,"init",function(c){c=c.options;c.useOhlcData&&"highcharts-navigator-series"!==c.id&&r(this,{pointValKey:q.pointValKey,keys:q.keys,pointArrayMap:q.pointArrayMap,toYData:q.toYData})});g(p,"afterSetOptions",function(c){c=c.options;var a=c.dataGrouping;a&&c.useOhlcData&&"highcharts-navigator-series"!==c.id&&(a.approximation="ohlc")});a.seriesType("sma","line",{name:void 0,tooltip:{valueDecimals:4},linkedTo:void 0,compareToMain:!1,params:{index:0,
period:14}},{processData:function(){var c=this.options.compareToMain,a=this.linkedParent;p.prototype.processData.apply(this,arguments);a&&a.compareValue&&c&&(this.compareValue=a.compareValue)},bindTo:{series:!0,eventName:"updatedData"},hasDerivedData:!0,useCommonDataGrouping:!0,nameComponents:["period"],nameSuffixes:[],calculateOn:"init",requiredIndicators:[],requireIndicators:function(){var a={allLoaded:!0};this.requiredIndicators.forEach(function(c){f[c]?f[c].prototype.requireIndicators():(a.allLoaded=
!1,a.needed=c)});return a},init:function(a,d){function c(){var a=b.points||[],c=(b.xData||[]).length,d=b.getValues(b.linkedParent,b.options.params)||{values:[],xData:[],yData:[]},f=[],g=!0;if(c&&!b.hasGroupedData&&b.visible&&b.points)if(b.cropped){if(b.xAxis){var e=b.xAxis.min;var k=b.xAxis.max}c=b.cropData(d.xData,d.yData,e,k);for(e=0;e<c.xData.length;e++)f.push([c.xData[e]].concat(u(c.yData[e])));c=d.xData.indexOf(b.xData[0]);e=d.xData.indexOf(b.xData[b.xData.length-1]);-1===c&&e===d.xData.length-
2&&f[0][0]===a[0].x&&f.shift();b.updateData(f)}else d.xData.length!==c-1&&d.xData.length!==c+1&&(g=!1,b.updateData(d.values));g&&(b.xData=d.xData,b.yData=d.yData,b.options.data=d.values);!1===b.bindTo.series&&(delete b.processedXData,b.isDirty=!0,b.redraw());b.isDirtyData=!1}var b=this,f=b.requireIndicators();if(!f.allLoaded)return n(k(b.type,f.needed));p.prototype.init.call(b,a,d);a.linkSeries();b.dataEventsToUnbind=[];if(!b.linkedParent)return n("Series "+b.options.linkedTo+" not found! Check `linkedTo`.",
!1,a);b.dataEventsToUnbind.push(g(b.bindTo.series?b.linkedParent:b.linkedParent.xAxis,b.bindTo.eventName,c));if("init"===b.calculateOn)c();else var e=g(b.chart,b.calculateOn,function(){c();e()});return b},getName:function(){var a=this.name,d=[];a||((this.nameComponents||[]).forEach(function(a,c){d.push(this.options.params[a]+l(this.nameSuffixes[c],""))},this),a=(this.nameBase||this.type.toUpperCase())+(this.nameComponents?" ("+d.join(", ")+")":""));return a},getValues:function(a,d){var c=d.period,
b=a.xData;a=a.yData;var e=a.length,f=0,g=0,k=[],l=[],n=[],h=-1;if(!(b.length<c)){for(t(a[0])&&(h=d.index?d.index:0);f<c-1;)g+=0>h?a[f]:a[f][h],f++;for(d=f;d<e;d++){g+=0>h?a[d]:a[d][h];var m=[b[d],g/c];k.push(m);l.push(m[0]);n.push(m[1]);g-=0>h?a[d-f]:a[d-f][h]}return{values:k,xData:l,yData:n}}},destroy:function(){this.dataEventsToUnbind.forEach(function(a){a()});p.prototype.destroy.apply(this,arguments)}});""});h(a,"Stock/Indicators/CCIIndicator.js",[a["Core/Series/Series.js"],a["Core/Utilities.js"]],
function(a,h){function m(a){return a.reduce(function(a,f){return a+f},0)}var e=h.isArray;a.seriesType("cci","sma",{params:{period:14}},{getValues:function(a,g){g=g.period;var f=a.xData,h=(a=a.yData)?a.length:0,t=[],l=1,u=[],p=[],q=[];if(!(f.length<=g)&&e(a[0])&&4===a[0].length){for(;l<g;){var k=a[l-1];t.push((k[1]+k[2]+k[3])/3);l++}for(l=g;l<=h;l++){k=a[l-1];k=(k[1]+k[2]+k[3])/3;var c=t.push(k);var d=t.slice(c-g);c=m(d)/g;var v,b=d.length,r=0;for(v=0;v<b;v++)r+=Math.abs(c-d[v]);d=r/g;k=(k-c)/(.015*
d);u.push([f[l-1],k]);p.push(f[l-1]);q.push(k)}return{values:u,xData:p,yData:q}}}});""});h(a,"masters/indicators/cci.src.js",[],function(){})});
//# sourceMappingURL=cci.js.map