/*
 Highstock JS v8.2.0 (2020-10-07)

 Indicator series type for Highstock

 (c) 2010-2019 Wojciech Chmiel

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/indicators/chaikin",["highcharts","highcharts/modules/stock"],function(m){a(m);a.Highcharts=m;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function m(a,l,t,g){a.hasOwnProperty(l)||(a[l]=g.apply(null,t))}a=a?a._modules:{};m(a,"Mixins/IndicatorRequired.js",[a["Core/Utilities.js"]],function(a){var l=a.error;return{isParentLoaded:function(a,
g,k,e,h){if(a)return e?e(a):!0;l(h||this.generateMessage(k,g));return!1},generateMessage:function(a,g){return'Error: "'+a+'" indicator type requires "'+g+'" indicator loaded before. Please read docs: https://api.highcharts.com/highstock/plotOptions.'+a}}});m(a,"Stock/Indicators/SMAIndicator.js",[a["Core/Series/Series.js"],a["Core/Globals.js"],a["Mixins/IndicatorRequired.js"],a["Core/Utilities.js"]],function(a,l,t,g){var k=a.seriesTypes,e=g.addEvent,h=g.error,p=g.extend,c=g.isArray,d=g.pick,q=g.splat,
n=l.Series,u=k.ohlc.prototype,v=t.generateMessage;e(l.Series,"init",function(b){b=b.options;b.useOhlcData&&"highcharts-navigator-series"!==b.id&&p(this,{pointValKey:u.pointValKey,keys:u.keys,pointArrayMap:u.pointArrayMap,toYData:u.toYData})});e(n,"afterSetOptions",function(b){b=b.options;var a=b.dataGrouping;a&&b.useOhlcData&&"highcharts-navigator-series"!==b.id&&(a.approximation="ohlc")});a.seriesType("sma","line",{name:void 0,tooltip:{valueDecimals:4},linkedTo:void 0,compareToMain:!1,params:{index:0,
period:14}},{processData:function(){var b=this.options.compareToMain,a=this.linkedParent;n.prototype.processData.apply(this,arguments);a&&a.compareValue&&b&&(this.compareValue=a.compareValue)},bindTo:{series:!0,eventName:"updatedData"},hasDerivedData:!0,useCommonDataGrouping:!0,nameComponents:["period"],nameSuffixes:[],calculateOn:"init",requiredIndicators:[],requireIndicators:function(){var b={allLoaded:!0};this.requiredIndicators.forEach(function(a){k[a]?k[a].prototype.requireIndicators():(b.allLoaded=
!1,b.needed=a)});return b},init:function(a,d){function b(){var a=f.points||[],b=(f.xData||[]).length,c=f.getValues(f.linkedParent,f.options.params)||{values:[],xData:[],yData:[]},d=[],e=!0;if(b&&!f.hasGroupedData&&f.visible&&f.points)if(f.cropped){if(f.xAxis){var k=f.xAxis.min;var h=f.xAxis.max}b=f.cropData(c.xData,c.yData,k,h);for(k=0;k<b.xData.length;k++)d.push([b.xData[k]].concat(q(b.yData[k])));b=c.xData.indexOf(f.xData[0]);k=c.xData.indexOf(f.xData[f.xData.length-1]);-1===b&&k===c.xData.length-
2&&d[0][0]===a[0].x&&d.shift();f.updateData(d)}else c.xData.length!==b-1&&c.xData.length!==b+1&&(e=!1,f.updateData(c.values));e&&(f.xData=c.xData,f.yData=c.yData,f.options.data=c.values);!1===f.bindTo.series&&(delete f.processedXData,f.isDirty=!0,f.redraw());f.isDirtyData=!1}var f=this,c=f.requireIndicators();if(!c.allLoaded)return h(v(f.type,c.needed));n.prototype.init.call(f,a,d);a.linkSeries();f.dataEventsToUnbind=[];if(!f.linkedParent)return h("Series "+f.options.linkedTo+" not found! Check `linkedTo`.",
!1,a);f.dataEventsToUnbind.push(e(f.bindTo.series?f.linkedParent:f.linkedParent.xAxis,f.bindTo.eventName,b));if("init"===f.calculateOn)b();else var k=e(f.chart,f.calculateOn,function(){b();k()});return f},getName:function(){var b=this.name,a=[];b||((this.nameComponents||[]).forEach(function(b,c){a.push(this.options.params[b]+d(this.nameSuffixes[c],""))},this),b=(this.nameBase||this.type.toUpperCase())+(this.nameComponents?" ("+a.join(", ")+")":""));return b},getValues:function(b,a){var d=a.period,
f=b.xData;b=b.yData;var k=b.length,e=0,h=0,g=[],q=[],p=[],n=-1;if(!(f.length<d)){for(c(b[0])&&(n=a.index?a.index:0);e<d-1;)h+=0>n?b[e]:b[e][n],e++;for(a=e;a<k;a++){h+=0>n?b[a]:b[a][n];var l=[f[a],h/d];g.push(l);q.push(l[0]);p.push(l[1]);h-=0>n?b[a-e]:b[a-e][n]}return{values:g,xData:q,yData:p}}},destroy:function(){this.dataEventsToUnbind.forEach(function(a){a()});n.prototype.destroy.apply(this,arguments)}});""});m(a,"Stock/Indicators/ADIndicator.js",[a["Core/Series/Series.js"],a["Core/Utilities.js"]],
function(a,l){var t=l.error;a.seriesType("ad","sma",{params:{volumeSeriesID:"volume"}},{nameComponents:!1,nameBase:"Accumulation/Distribution",getValues:function(a,k){var e=k.period,h=a.xData,p=a.yData,c=k.volumeSeriesID,d=a.chart.get(c);k=d&&d.yData;var q=p?p.length:0,n=[],g=[],l=[];if(!(h.length<=e&&q&&4!==p[0].length)){if(d){for(;e<q;e++){a=n.length;c=p[e][1];d=p[e][2];var b=p[e][3],m=k[e];c=[h[e],b===c&&b===d||c===d?0:(2*b-d-c)/(c-d)*m];0<a&&(c[1]+=n[a-1][1]);n.push(c);g.push(c[0]);l.push(c[1])}return{values:n,
xData:g,yData:l}}t("Series "+c+" not found! Check `volumeSeriesID`.",!0,a.chart)}}});""});m(a,"Stock/Indicators/EMAIndicator.js",[a["Core/Series/Series.js"],a["Core/Utilities.js"]],function(a,l){var m=l.correctFloat,g=l.isArray;a.seriesType("ema","sma",{params:{index:3,period:9}},{accumulatePeriodPoints:function(a,e,h){for(var k=0,c=0,d;c<a;)d=0>e?h[c]:h[c][e],k+=d,c++;return k},calculateEma:function(a,e,h,g,c,d,q){a=a[h-1];e=0>d?e[h-1]:e[h-1][d];g="undefined"===typeof c?q:m(e*g+c*(1-g));return[a,
g]},getValues:function(a,e){var h=e.period,k=a.xData,c=(a=a.yData)?a.length:0,d=2/(h+1),q=[],n=[],l=[],m=-1;if(!(c<h)){g(a[0])&&(m=e.index?e.index:0);e=this.accumulatePeriodPoints(h,m,a);for(e/=h;h<c+1;h++){var b=this.calculateEma(k,a,h,d,b,m,e);q.push(b);n.push(b[0]);l.push(b[1]);b=b[1]}return{values:q,xData:n,yData:l}}}});""});m(a,"Stock/Indicators/ChaikinIndicator.js",[a["Core/Series/Series.js"],a["Mixins/IndicatorRequired.js"],a["Core/Utilities.js"]],function(a,l,m){var g=a.seriesTypes,k=m.correctFloat,
e=m.error,h=g.ema,p=g.ad;a.seriesType("chaikin","ema",{params:{volumeSeriesID:"volume",periods:[3,10]}},{nameBase:"Chaikin Osc",nameComponents:["periods"],init:function(){var a=arguments,d=this;l.isParentLoaded(h,"ema",d.type,function(c){c.prototype.init.apply(d,a)})},getValues:function(a,d){var c=d.periods,g=d.period,l=[],m=[],b=[],r;if(2!==c.length||c[1]<=c[0])e('Error: "Chaikin requires two periods. Notice, first period should be lower than the second one."');else if(d=p.prototype.getValues.call(this,
a,{volumeSeriesID:d.volumeSeriesID,period:g}))if(a=h.prototype.getValues.call(this,d,{period:c[0]}),d=h.prototype.getValues.call(this,d,{period:c[1]}),a&&d){c=c[1]-c[0];for(r=0;r<d.yData.length;r++)g=k(a.yData[r+c]-d.yData[r]),l.push([d.xData[r],g]),m.push(d.xData[r]),b.push(g);return{values:l,xData:m,yData:b}}}});""});m(a,"masters/indicators/chaikin.src.js",[],function(){})});
//# sourceMappingURL=chaikin.js.map