/*
 Highstock JS v8.2.0 (2020-10-07)

 (c) 2010-2019 Highsoft AS
 Author: Sebastian Domas

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/indicators/cmf",["highcharts","highcharts/modules/stock"],function(h){a(h);a.Highcharts=h;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function h(a,f,l,b){a.hasOwnProperty(f)||(a[f]=b.apply(null,l))}a=a?a._modules:{};h(a,"Mixins/IndicatorRequired.js",[a["Core/Utilities.js"]],function(a){var f=a.error;return{isParentLoaded:function(a,
b,g,m,h){if(a)return m?m(a):!0;f(h||this.generateMessage(g,b));return!1},generateMessage:function(a,b){return'Error: "'+a+'" indicator type requires "'+b+'" indicator loaded before. Please read docs: https://api.highcharts.com/highstock/plotOptions.'+a}}});h(a,"Stock/Indicators/SMAIndicator.js",[a["Core/Series/Series.js"],a["Core/Globals.js"],a["Mixins/IndicatorRequired.js"],a["Core/Utilities.js"]],function(a,f,l,b){var g=a.seriesTypes,m=b.addEvent,h=b.error,r=b.extend,p=b.isArray,t=b.pick,u=b.splat,
n=f.Series,q=g.ohlc.prototype,e=l.generateMessage;m(f.Series,"init",function(d){d=d.options;d.useOhlcData&&"highcharts-navigator-series"!==d.id&&r(this,{pointValKey:q.pointValKey,keys:q.keys,pointArrayMap:q.pointArrayMap,toYData:q.toYData})});m(n,"afterSetOptions",function(d){d=d.options;var a=d.dataGrouping;a&&d.useOhlcData&&"highcharts-navigator-series"!==d.id&&(a.approximation="ohlc")});a.seriesType("sma","line",{name:void 0,tooltip:{valueDecimals:4},linkedTo:void 0,compareToMain:!1,params:{index:0,
period:14}},{processData:function(){var d=this.options.compareToMain,a=this.linkedParent;n.prototype.processData.apply(this,arguments);a&&a.compareValue&&d&&(this.compareValue=a.compareValue)},bindTo:{series:!0,eventName:"updatedData"},hasDerivedData:!0,useCommonDataGrouping:!0,nameComponents:["period"],nameSuffixes:[],calculateOn:"init",requiredIndicators:[],requireIndicators:function(){var a={allLoaded:!0};this.requiredIndicators.forEach(function(d){g[d]?g[d].prototype.requireIndicators():(a.allLoaded=
!1,a.needed=d)});return a},init:function(a,b){function d(){var a=c.points||[],d=(c.xData||[]).length,b=c.getValues(c.linkedParent,c.options.params)||{values:[],xData:[],yData:[]},e=[],f=!0;if(d&&!c.hasGroupedData&&c.visible&&c.points)if(c.cropped){if(c.xAxis){var k=c.xAxis.min;var g=c.xAxis.max}d=c.cropData(b.xData,b.yData,k,g);for(k=0;k<d.xData.length;k++)e.push([d.xData[k]].concat(u(d.yData[k])));d=b.xData.indexOf(c.xData[0]);k=b.xData.indexOf(c.xData[c.xData.length-1]);-1===d&&k===b.xData.length-
2&&e[0][0]===a[0].x&&e.shift();c.updateData(e)}else b.xData.length!==d-1&&b.xData.length!==d+1&&(f=!1,c.updateData(b.values));f&&(c.xData=b.xData,c.yData=b.yData,c.options.data=b.values);!1===c.bindTo.series&&(delete c.processedXData,c.isDirty=!0,c.redraw());c.isDirtyData=!1}var c=this,f=c.requireIndicators();if(!f.allLoaded)return h(e(c.type,f.needed));n.prototype.init.call(c,a,b);a.linkSeries();c.dataEventsToUnbind=[];if(!c.linkedParent)return h("Series "+c.options.linkedTo+" not found! Check `linkedTo`.",
!1,a);c.dataEventsToUnbind.push(m(c.bindTo.series?c.linkedParent:c.linkedParent.xAxis,c.bindTo.eventName,d));if("init"===c.calculateOn)d();else var k=m(c.chart,c.calculateOn,function(){d();k()});return c},getName:function(){var a=this.name,b=[];a||((this.nameComponents||[]).forEach(function(a,c){b.push(this.options.params[a]+t(this.nameSuffixes[c],""))},this),a=(this.nameBase||this.type.toUpperCase())+(this.nameComponents?" ("+b.join(", ")+")":""));return a},getValues:function(a,b){var d=b.period,
c=a.xData;a=a.yData;var e=a.length,f=0,g=0,k=[],l=[],h=[],m=-1;if(!(c.length<d)){for(p(a[0])&&(m=b.index?b.index:0);f<d-1;)g+=0>m?a[f]:a[f][m],f++;for(b=f;b<e;b++){g+=0>m?a[b]:a[b][m];var n=[c[b],g/d];k.push(n);l.push(n[0]);h.push(n[1]);g-=0>m?a[b-f]:a[b-f][m]}return{values:k,xData:l,yData:h}}},destroy:function(){this.dataEventsToUnbind.forEach(function(a){a()});n.prototype.destroy.apply(this,arguments)}});""});h(a,"Stock/Indicators/CMFIndicator.js",[a["Core/Series/Series.js"]],function(a){a.seriesType("cmf",
"sma",{params:{period:14,volumeSeriesID:"volume"}},{nameBase:"Chaikin Money Flow",isValid:function(){var a=this.chart,l=this.options,b=this.linkedParent;a=this.volumeSeries||(this.volumeSeries=a.get(l.params.volumeSeriesID));var g=b&&b.yData&&4===b.yData[0].length;return!!(b&&a&&b.xData&&b.xData.length>=l.params.period&&a.xData&&a.xData.length>=l.params.period&&g)},getValues:function(a,l){if(this.isValid())return this.getMoneyFlow(a.xData,a.yData,this.volumeSeries.yData,l.period)},getMoneyFlow:function(a,
l,b,g){function f(a,b){var c=a[1],f=a[2];a=a[3];return null!==b&&null!==c&&null!==f&&null!==a&&c!==f?(a-f-(c-a))/(c-f)*b:(d=e,null)}var h=l.length,r=[],p=0,t=0,u=[],n=[],q=[],e,d=-1;if(0<g&&g<=h){for(e=0;e<g;e++)r[e]=f(l[e],b[e]),p+=b[e],t+=r[e];u.push(a[e-1]);n.push(e-d>=g&&0!==p?t/p:null);for(q.push([u[0],n[0]]);e<h;e++){r[e]=f(l[e],b[e]);p-=b[e-g];p+=b[e];t-=r[e-g];t+=r[e];var k=[a[e],e-d>=g?t/p:null];u.push(k[0]);n.push(k[1]);q.push([k[0],k[1]])}}return{values:q,xData:u,yData:n}}});""});h(a,"masters/indicators/cmf.src.js",
[],function(){})});
//# sourceMappingURL=cmf.js.map