/*
 Highstock JS v8.2.0 (2020-10-07)

 Indicator series type for Highstock

 (c) 2010-2019 Wojciech Chmiel

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/indicators/dpo",["highcharts","highcharts/modules/stock"],function(k){a(k);a.Highcharts=k;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function k(a,g,m,e){a.hasOwnProperty(g)||(a[g]=e.apply(null,m))}a=a?a._modules:{};k(a,"Mixins/IndicatorRequired.js",[a["Core/Utilities.js"]],function(a){var g=a.error;return{isParentLoaded:function(a,
e,l,h,f){if(a)return h?h(a):!0;g(f||this.generateMessage(l,e));return!1},generateMessage:function(a,e){return'Error: "'+a+'" indicator type requires "'+e+'" indicator loaded before. Please read docs: https://api.highcharts.com/highstock/plotOptions.'+a}}});k(a,"Stock/Indicators/SMAIndicator.js",[a["Core/Series/Series.js"],a["Core/Globals.js"],a["Mixins/IndicatorRequired.js"],a["Core/Utilities.js"]],function(a,g,k,e){var l=a.seriesTypes,h=e.addEvent,f=e.error,r=e.extend,u=e.isArray,v=e.pick,m=e.splat,
n=g.Series,p=l.ohlc.prototype,t=k.generateMessage;h(g.Series,"init",function(d){d=d.options;d.useOhlcData&&"highcharts-navigator-series"!==d.id&&r(this,{pointValKey:p.pointValKey,keys:p.keys,pointArrayMap:p.pointArrayMap,toYData:p.toYData})});h(n,"afterSetOptions",function(d){d=d.options;var c=d.dataGrouping;c&&d.useOhlcData&&"highcharts-navigator-series"!==d.id&&(c.approximation="ohlc")});a.seriesType("sma","line",{name:void 0,tooltip:{valueDecimals:4},linkedTo:void 0,compareToMain:!1,params:{index:0,
period:14}},{processData:function(){var d=this.options.compareToMain,c=this.linkedParent;n.prototype.processData.apply(this,arguments);c&&c.compareValue&&d&&(this.compareValue=c.compareValue)},bindTo:{series:!0,eventName:"updatedData"},hasDerivedData:!0,useCommonDataGrouping:!0,nameComponents:["period"],nameSuffixes:[],calculateOn:"init",requiredIndicators:[],requireIndicators:function(){var d={allLoaded:!0};this.requiredIndicators.forEach(function(c){l[c]?l[c].prototype.requireIndicators():(d.allLoaded=
!1,d.needed=c)});return d},init:function(d,c){function a(){var d=b.points||[],a=(b.xData||[]).length,c=b.getValues(b.linkedParent,b.options.params)||{values:[],xData:[],yData:[]},h=[],e=!0;if(a&&!b.hasGroupedData&&b.visible&&b.points)if(b.cropped){if(b.xAxis){var f=b.xAxis.min;var g=b.xAxis.max}a=b.cropData(c.xData,c.yData,f,g);for(f=0;f<a.xData.length;f++)h.push([a.xData[f]].concat(m(a.yData[f])));a=c.xData.indexOf(b.xData[0]);f=c.xData.indexOf(b.xData[b.xData.length-1]);-1===a&&f===c.xData.length-
2&&h[0][0]===d[0].x&&h.shift();b.updateData(h)}else c.xData.length!==a-1&&c.xData.length!==a+1&&(e=!1,b.updateData(c.values));e&&(b.xData=c.xData,b.yData=c.yData,b.options.data=c.values);!1===b.bindTo.series&&(delete b.processedXData,b.isDirty=!0,b.redraw());b.isDirtyData=!1}var b=this,e=b.requireIndicators();if(!e.allLoaded)return f(t(b.type,e.needed));n.prototype.init.call(b,d,c);d.linkSeries();b.dataEventsToUnbind=[];if(!b.linkedParent)return f("Series "+b.options.linkedTo+" not found! Check `linkedTo`.",
!1,d);b.dataEventsToUnbind.push(h(b.bindTo.series?b.linkedParent:b.linkedParent.xAxis,b.bindTo.eventName,a));if("init"===b.calculateOn)a();else var g=h(b.chart,b.calculateOn,function(){a();g()});return b},getName:function(){var a=this.name,c=[];a||((this.nameComponents||[]).forEach(function(a,b){c.push(this.options.params[a]+v(this.nameSuffixes[b],""))},this),a=(this.nameBase||this.type.toUpperCase())+(this.nameComponents?" ("+c.join(", ")+")":""));return a},getValues:function(a,c){var d=c.period,
b=a.xData;a=a.yData;var f=a.length,h=0,e=0,g=[],r=[],k=[],l=-1;if(!(b.length<d)){for(u(a[0])&&(l=c.index?c.index:0);h<d-1;)e+=0>l?a[h]:a[h][l],h++;for(c=h;c<f;c++){e+=0>l?a[c]:a[c][l];var m=[b[c],e/d];g.push(m);r.push(m[0]);k.push(m[1]);e-=0>l?a[c-h]:a[c-h][l]}return{values:g,xData:r,yData:k}}},destroy:function(){this.dataEventsToUnbind.forEach(function(a){a()});n.prototype.destroy.apply(this,arguments)}});""});k(a,"Stock/Indicators/DPOIndicator.js",[a["Core/Series/Series.js"],a["Core/Utilities.js"]],
function(a,g){function k(a,f,g,k,m){f=l(f[g][k],f[g]);return m?e(a-f):e(a+f)}var e=g.correctFloat,l=g.pick;a.seriesType("dpo","sma",{params:{period:21}},{nameBase:"DPO",getValues:function(a,f){var e=f.period;f=f.index;var g=e+Math.floor(e/2+1),h=a.xData||[];a=a.yData||[];var m=a.length,n=[],p=[],t=[],d=0,c,q;if(!(h.length<=g)){for(c=0;c<e-1;c++)d=k(d,a,c,f);for(q=0;q<=m-g;q++){var b=q+e-1;c=q+g-1;d=k(d,a,b,f);b=l(a[c][f],a[c]);b-=d/e;d=k(d,a,q,f,!0);n.push([h[c],b]);p.push(h[c]);t.push(b)}return{values:n,
xData:p,yData:t}}}});""});k(a,"masters/indicators/dpo.src.js",[],function(){})});
//# sourceMappingURL=dpo.js.map