/*
 Highstock JS v8.2.0 (2020-10-07)

 Money Flow Index indicator for Highstock

 (c) 2010-2019 Grzegorz Blachliski

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/indicators/mfi",["highcharts","highcharts/modules/stock"],function(f){a(f);a.Highcharts=f;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function f(a,k,y,e){a.hasOwnProperty(k)||(a[k]=e.apply(null,y))}a=a?a._modules:{};f(a,"Mixins/IndicatorRequired.js",[a["Core/Utilities.js"]],function(a){var k=a.error;return{isParentLoaded:function(a,
e,f,m,h){if(a)return m?m(a):!0;k(h||this.generateMessage(f,e));return!1},generateMessage:function(a,e){return'Error: "'+a+'" indicator type requires "'+e+'" indicator loaded before. Please read docs: https://api.highcharts.com/highstock/plotOptions.'+a}}});f(a,"Stock/Indicators/SMAIndicator.js",[a["Core/Series/Series.js"],a["Core/Globals.js"],a["Mixins/IndicatorRequired.js"],a["Core/Utilities.js"]],function(a,k,f,e){var r=a.seriesTypes,m=e.addEvent,h=e.error,b=e.extend,v=e.isArray,z=e.pick,n=e.splat,
p=k.Series,q=r.ohlc.prototype,g=f.generateMessage;m(k.Series,"init",function(d){d=d.options;d.useOhlcData&&"highcharts-navigator-series"!==d.id&&b(this,{pointValKey:q.pointValKey,keys:q.keys,pointArrayMap:q.pointArrayMap,toYData:q.toYData})});m(p,"afterSetOptions",function(d){d=d.options;var a=d.dataGrouping;a&&d.useOhlcData&&"highcharts-navigator-series"!==d.id&&(a.approximation="ohlc")});a.seriesType("sma","line",{name:void 0,tooltip:{valueDecimals:4},linkedTo:void 0,compareToMain:!1,params:{index:0,
period:14}},{processData:function(){var d=this.options.compareToMain,a=this.linkedParent;p.prototype.processData.apply(this,arguments);a&&a.compareValue&&d&&(this.compareValue=a.compareValue)},bindTo:{series:!0,eventName:"updatedData"},hasDerivedData:!0,useCommonDataGrouping:!0,nameComponents:["period"],nameSuffixes:[],calculateOn:"init",requiredIndicators:[],requireIndicators:function(){var d={allLoaded:!0};this.requiredIndicators.forEach(function(a){r[a]?r[a].prototype.requireIndicators():(d.allLoaded=
!1,d.needed=a)});return d},init:function(d,a){function b(){var d=c.points||[],a=(c.xData||[]).length,b=c.getValues(c.linkedParent,c.options.params)||{values:[],xData:[],yData:[]},h=[],l=!0;if(a&&!c.hasGroupedData&&c.visible&&c.points)if(c.cropped){if(c.xAxis){var e=c.xAxis.min;var v=c.xAxis.max}a=c.cropData(b.xData,b.yData,e,v);for(e=0;e<a.xData.length;e++)h.push([a.xData[e]].concat(n(a.yData[e])));a=b.xData.indexOf(c.xData[0]);e=b.xData.indexOf(c.xData[c.xData.length-1]);-1===a&&e===b.xData.length-
2&&h[0][0]===d[0].x&&h.shift();c.updateData(h)}else b.xData.length!==a-1&&b.xData.length!==a+1&&(l=!1,c.updateData(b.values));l&&(c.xData=b.xData,c.yData=b.yData,c.options.data=b.values);!1===c.bindTo.series&&(delete c.processedXData,c.isDirty=!0,c.redraw());c.isDirtyData=!1}var c=this,l=c.requireIndicators();if(!l.allLoaded)return h(g(c.type,l.needed));p.prototype.init.call(c,d,a);d.linkSeries();c.dataEventsToUnbind=[];if(!c.linkedParent)return h("Series "+c.options.linkedTo+" not found! Check `linkedTo`.",
!1,d);c.dataEventsToUnbind.push(m(c.bindTo.series?c.linkedParent:c.linkedParent.xAxis,c.bindTo.eventName,b));if("init"===c.calculateOn)b();else var e=m(c.chart,c.calculateOn,function(){b();e()});return c},getName:function(){var a=this.name,b=[];a||((this.nameComponents||[]).forEach(function(a,c){b.push(this.options.params[a]+z(this.nameSuffixes[c],""))},this),a=(this.nameBase||this.type.toUpperCase())+(this.nameComponents?" ("+b.join(", ")+")":""));return a},getValues:function(a,b){var d=b.period,
c=a.xData;a=a.yData;var h=a.length,e=0,f=0,k=[],m=[],n=[],g=-1;if(!(c.length<d)){for(v(a[0])&&(g=b.index?b.index:0);e<d-1;)f+=0>g?a[e]:a[e][g],e++;for(b=e;b<h;b++){f+=0>g?a[b]:a[b][g];var l=[c[b],f/d];k.push(l);m.push(l[0]);n.push(l[1]);f-=0>g?a[b-e]:a[b-e][g]}return{values:k,xData:m,yData:n}}},destroy:function(){this.dataEventsToUnbind.forEach(function(a){a()});p.prototype.destroy.apply(this,arguments)}});""});f(a,"Stock/Indicators/MFIIndicator.js",[a["Core/Series/Series.js"],a["Core/Utilities.js"]],
function(a,f){function k(a){return a.reduce(function(a,e){return a+e})}function e(a){return(a[1]+a[2]+a[3])/3}var r=f.error,m=f.isArray;a.seriesType("mfi","sma",{params:{period:14,volumeSeriesID:"volume",decimals:4}},{nameBase:"Money Flow Index",getValues:function(a,b){var f=b.period,h=a.xData,n=a.yData,p=n?n.length:0,q=b.decimals,g=1,d=a.chart.get(b.volumeSeriesID),l=d&&d.yData,w=[],c=[],x=[],u=[],t=[];if(!d)r("Series "+b.volumeSeriesID+" not found! Check `volumeSeriesID`.",!0,a.chart);else if(!(h.length<=
f)&&m(n[0])&&4===n[0].length&&l){for(a=e(n[g]);g<f+1;)b=a,a=e(n[g]),b=a>=b,d=a*l[g],u.push(b?d:0),t.push(b?0:d),g++;for(f=g-1;f<p;f++)f>g-1&&(u.shift(),t.shift(),b=a,a=e(n[f]),b=a>b,d=a*l[f],u.push(b?d:0),t.push(b?0:d)),b=k(t),d=k(u),b=d/b,b=parseFloat((100-100/(1+b)).toFixed(q)),w.push([h[f],b]),c.push(h[f]),x.push(b);return{values:w,xData:c,yData:x}}}});""});f(a,"masters/indicators/mfi.src.js",[],function(){})});
//# sourceMappingURL=mfi.js.map