/*
 Highstock JS v8.2.0 (2020-10-07)

 Indicator series type for Highstock

 (c) 2010-2019 Sebastian Bochan

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/indicators/momentum",["highcharts","highcharts/modules/stock"],function(h){a(h);a.Highcharts=h;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function h(a,l,u,e){a.hasOwnProperty(l)||(a[l]=e.apply(null,u))}a=a?a._modules:{};h(a,"Mixins/IndicatorRequired.js",[a["Core/Utilities.js"]],function(a){var l=a.error;return{isParentLoaded:function(a,
e,f,g,m){if(a)return g?g(a):!0;l(m||this.generateMessage(f,e));return!1},generateMessage:function(a,e){return'Error: "'+a+'" indicator type requires "'+e+'" indicator loaded before. Please read docs: https://api.highcharts.com/highstock/plotOptions.'+a}}});h(a,"Stock/Indicators/SMAIndicator.js",[a["Core/Series/Series.js"],a["Core/Globals.js"],a["Mixins/IndicatorRequired.js"],a["Core/Utilities.js"]],function(a,l,h,e){var f=a.seriesTypes,g=e.addEvent,m=e.error,v=e.extend,p=e.isArray,r=e.pick,t=e.splat,
q=l.Series,k=f.ohlc.prototype,n=h.generateMessage;g(l.Series,"init",function(c){c=c.options;c.useOhlcData&&"highcharts-navigator-series"!==c.id&&v(this,{pointValKey:k.pointValKey,keys:k.keys,pointArrayMap:k.pointArrayMap,toYData:k.toYData})});g(q,"afterSetOptions",function(c){c=c.options;var a=c.dataGrouping;a&&c.useOhlcData&&"highcharts-navigator-series"!==c.id&&(a.approximation="ohlc")});a.seriesType("sma","line",{name:void 0,tooltip:{valueDecimals:4},linkedTo:void 0,compareToMain:!1,params:{index:0,
period:14}},{processData:function(){var a=this.options.compareToMain,d=this.linkedParent;q.prototype.processData.apply(this,arguments);d&&d.compareValue&&a&&(this.compareValue=d.compareValue)},bindTo:{series:!0,eventName:"updatedData"},hasDerivedData:!0,useCommonDataGrouping:!0,nameComponents:["period"],nameSuffixes:[],calculateOn:"init",requiredIndicators:[],requireIndicators:function(){var a={allLoaded:!0};this.requiredIndicators.forEach(function(c){f[c]?f[c].prototype.requireIndicators():(a.allLoaded=
!1,a.needed=c)});return a},init:function(a,d){function c(){var a=b.points||[],c=(b.xData||[]).length,d=b.getValues(b.linkedParent,b.options.params)||{values:[],xData:[],yData:[]},f=[],g=!0;if(c&&!b.hasGroupedData&&b.visible&&b.points)if(b.cropped){if(b.xAxis){var e=b.xAxis.min;var m=b.xAxis.max}c=b.cropData(d.xData,d.yData,e,m);for(e=0;e<c.xData.length;e++)f.push([c.xData[e]].concat(t(c.yData[e])));c=d.xData.indexOf(b.xData[0]);e=d.xData.indexOf(b.xData[b.xData.length-1]);-1===c&&e===d.xData.length-
2&&f[0][0]===a[0].x&&f.shift();b.updateData(f)}else d.xData.length!==c-1&&d.xData.length!==c+1&&(g=!1,b.updateData(d.values));g&&(b.xData=d.xData,b.yData=d.yData,b.options.data=d.values);!1===b.bindTo.series&&(delete b.processedXData,b.isDirty=!0,b.redraw());b.isDirtyData=!1}var b=this,f=b.requireIndicators();if(!f.allLoaded)return m(n(b.type,f.needed));q.prototype.init.call(b,a,d);a.linkSeries();b.dataEventsToUnbind=[];if(!b.linkedParent)return m("Series "+b.options.linkedTo+" not found! Check `linkedTo`.",
!1,a);b.dataEventsToUnbind.push(g(b.bindTo.series?b.linkedParent:b.linkedParent.xAxis,b.bindTo.eventName,c));if("init"===b.calculateOn)c();else var e=g(b.chart,b.calculateOn,function(){c();e()});return b},getName:function(){var a=this.name,d=[];a||((this.nameComponents||[]).forEach(function(a,b){d.push(this.options.params[a]+r(this.nameSuffixes[b],""))},this),a=(this.nameBase||this.type.toUpperCase())+(this.nameComponents?" ("+d.join(", ")+")":""));return a},getValues:function(a,d){var c=d.period,
b=a.xData;a=a.yData;var e=a.length,f=0,g=0,m=[],h=[],l=[],k=-1;if(!(b.length<c)){for(p(a[0])&&(k=d.index?d.index:0);f<c-1;)g+=0>k?a[f]:a[f][k],f++;for(d=f;d<e;d++){g+=0>k?a[d]:a[d][k];var n=[b[d],g/c];m.push(n);h.push(n[0]);l.push(n[1]);g-=0>k?a[d-f]:a[d-f][k]}return{values:m,xData:h,yData:l}}},destroy:function(){this.dataEventsToUnbind.forEach(function(a){a()});q.prototype.destroy.apply(this,arguments)}});""});h(a,"Stock/Indicators/MomentumIndicator.js",[a["Core/Series/Series.js"],a["Core/Utilities.js"]],
function(a,h){function l(a,e,m,h,l){m=m[h-1][3]-m[h-l-1][3];e=e[h-1];a.shift();return[e,m]}var e=h.isArray;a.seriesType("momentum","sma",{params:{period:14}},{nameBase:"Momentum",getValues:function(a,g){g=g.period;var f=a.xData,h=(a=a.yData)?a.length:0,p=f[0],r=[],t=[],q=[];if(!(f.length<=g)&&e(a[0])){var k=a[0][3];k=[[p,k]];for(p=g+1;p<h;p++){var n=l(k,f,a,p,g,void 0);r.push(n);t.push(n[0]);q.push(n[1])}n=l(k,f,a,p,g,void 0);r.push(n);t.push(n[0]);q.push(n[1]);return{values:r,xData:t,yData:q}}}});
""});h(a,"masters/indicators/momentum.src.js",[],function(){})});
//# sourceMappingURL=momentum.js.map