/*
 Highstock JS v8.2.0 (2020-10-07)

 Indicator series type for Highstock

 (c) 2010-2019 Pawe Fus

 License: www.highcharts.com/license
*/
(function(c){"object"===typeof module&&module.exports?(c["default"]=c,module.exports=c):"function"===typeof define&&define.amd?define("highcharts/indicators/pivot-points",["highcharts","highcharts/modules/stock"],function(g){c(g);c.Highcharts=g;return c}):c("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(c){function g(c,m,w,h){c.hasOwnProperty(m)||(c[m]=h.apply(null,w))}c=c?c._modules:{};g(c,"Mixins/IndicatorRequired.js",[c["Core/Utilities.js"]],function(c){var m=c.error;return{isParentLoaded:function(c,
h,g,l,a){if(c)return l?l(c):!0;m(a||this.generateMessage(g,h));return!1},generateMessage:function(c,h){return'Error: "'+c+'" indicator type requires "'+h+'" indicator loaded before. Please read docs: https://api.highcharts.com/highstock/plotOptions.'+c}}});g(c,"Stock/Indicators/SMAIndicator.js",[c["Core/Series/Series.js"],c["Core/Globals.js"],c["Mixins/IndicatorRequired.js"],c["Core/Utilities.js"]],function(c,m,g,h){var u=c.seriesTypes,l=h.addEvent,a=h.error,b=h.extend,n=h.isArray,e=h.pick,r=h.splat,
p=m.Series,q=u.ohlc.prototype,k=g.generateMessage;l(m.Series,"init",function(a){a=a.options;a.useOhlcData&&"highcharts-navigator-series"!==a.id&&b(this,{pointValKey:q.pointValKey,keys:q.keys,pointArrayMap:q.pointArrayMap,toYData:q.toYData})});l(p,"afterSetOptions",function(a){a=a.options;var b=a.dataGrouping;b&&a.useOhlcData&&"highcharts-navigator-series"!==a.id&&(b.approximation="ohlc")});c.seriesType("sma","line",{name:void 0,tooltip:{valueDecimals:4},linkedTo:void 0,compareToMain:!1,params:{index:0,
period:14}},{processData:function(){var a=this.options.compareToMain,b=this.linkedParent;p.prototype.processData.apply(this,arguments);b&&b.compareValue&&a&&(this.compareValue=b.compareValue)},bindTo:{series:!0,eventName:"updatedData"},hasDerivedData:!0,useCommonDataGrouping:!0,nameComponents:["period"],nameSuffixes:[],calculateOn:"init",requiredIndicators:[],requireIndicators:function(){var a={allLoaded:!0};this.requiredIndicators.forEach(function(b){u[b]?u[b].prototype.requireIndicators():(a.allLoaded=
!1,a.needed=b)});return a},init:function(b,c){function f(){var a=d.points||[],b=(d.xData||[]).length,c=d.getValues(d.linkedParent,d.options.params)||{values:[],xData:[],yData:[]},f=[],n=!0;if(b&&!d.hasGroupedData&&d.visible&&d.points)if(d.cropped){if(d.xAxis){var e=d.xAxis.min;var x=d.xAxis.max}b=d.cropData(c.xData,c.yData,e,x);for(e=0;e<b.xData.length;e++)f.push([b.xData[e]].concat(r(b.yData[e])));b=c.xData.indexOf(d.xData[0]);e=c.xData.indexOf(d.xData[d.xData.length-1]);-1===b&&e===c.xData.length-
2&&f[0][0]===a[0].x&&f.shift();d.updateData(f)}else c.xData.length!==b-1&&c.xData.length!==b+1&&(n=!1,d.updateData(c.values));n&&(d.xData=c.xData,d.yData=c.yData,d.options.data=c.values);!1===d.bindTo.series&&(delete d.processedXData,d.isDirty=!0,d.redraw());d.isDirtyData=!1}var d=this,n=d.requireIndicators();if(!n.allLoaded)return a(k(d.type,n.needed));p.prototype.init.call(d,b,c);b.linkSeries();d.dataEventsToUnbind=[];if(!d.linkedParent)return a("Series "+d.options.linkedTo+" not found! Check `linkedTo`.",
!1,b);d.dataEventsToUnbind.push(l(d.bindTo.series?d.linkedParent:d.linkedParent.xAxis,d.bindTo.eventName,f));if("init"===d.calculateOn)f();else var e=l(d.chart,d.calculateOn,function(){f();e()});return d},getName:function(){var a=this.name,b=[];a||((this.nameComponents||[]).forEach(function(a,c){b.push(this.options.params[a]+e(this.nameSuffixes[c],""))},this),a=(this.nameBase||this.type.toUpperCase())+(this.nameComponents?" ("+b.join(", ")+")":""));return a},getValues:function(a,b){var c=b.period,
d=a.xData;a=a.yData;var e=a.length,f=0,h=0,q=[],r=[],p=[],k=-1;if(!(d.length<c)){for(n(a[0])&&(k=b.index?b.index:0);f<c-1;)h+=0>k?a[f]:a[f][k],f++;for(b=f;b<e;b++){h+=0>k?a[b]:a[b][k];var l=[d[b],h/c];q.push(l);r.push(l[0]);p.push(l[1]);h-=0>k?a[b-f]:a[b-f][k]}return{values:q,xData:r,yData:p}}},destroy:function(){this.dataEventsToUnbind.forEach(function(a){a()});p.prototype.destroy.apply(this,arguments)}});""});g(c,"Stock/Indicators/PivotPointsIndicator.js",[c["Core/Series/Series.js"],c["Core/Utilities.js"]],
function(c,g){function m(a,b){var c=a.series.pointArrayMap,e=c.length;for(l.prototype.pointClass.prototype[b].call(a);e--;)b="dataLabel"+c[e],a[b]&&a[b].element&&a[b].destroy(),a[b]=null}var h=g.defined,u=g.isArray,l=c.seriesTypes.sma;c.seriesType("pivotpoints","sma",{params:{period:28,algorithm:"standard"},marker:{enabled:!1},enableMouseTracking:!1,dataLabels:{enabled:!0,format:"{point.pivotLine}"},dataGrouping:{approximation:"averages"}},{nameBase:"Pivot Points",pointArrayMap:"R4 R3 R2 R1 P S1 S2 S3 S4".split(" "),
pointValKey:"P",toYData:function(a){return[a.P]},translate:function(){var a=this;l.prototype.translate.apply(a);a.points.forEach(function(b){a.pointArrayMap.forEach(function(c){h(b[c])&&(b["plot"+c]=a.yAxis.toPixels(b[c],!0))})});a.plotEndPoint=a.xAxis.toPixels(a.endPoint,!0)},getGraphPath:function(a){for(var b=this,c=a.length,e=[[],[],[],[],[],[],[],[],[]],r=[],p=b.plotEndPoint,q=b.pointArrayMap.length,k,f,g;c--;){f=a[c];for(g=0;g<q;g++)k=b.pointArrayMap[g],h(f[k])&&e[g].push({plotX:f.plotX,plotY:f["plot"+
k],isNull:!1},{plotX:p,plotY:f["plot"+k],isNull:!1},{plotX:p,plotY:null,isNull:!0});p=f.plotX}e.forEach(function(a){r=r.concat(l.prototype.getGraphPath.call(b,a))});return r},drawDataLabels:function(){var a=this,b=a.pointArrayMap,c,e,g;if(a.options.dataLabels.enabled){var h=a.points.length;b.concat([!1]).forEach(function(n,k){for(g=h;g--;)e=a.points[g],n?(e.y=e[n],e.pivotLine=n,e.plotY=e["plot"+n],c=e["dataLabel"+n],k&&(e["dataLabel"+b[k-1]]=e.dataLabel),e.dataLabels||(e.dataLabels=[]),e.dataLabels[0]=
e.dataLabel=c=c&&c.element?c:null):e["dataLabel"+b[k-1]]=e.dataLabel;l.prototype.drawDataLabels.apply(a,arguments)})}},getValues:function(a,b){var c=b.period,e=a.xData,g=(a=a.yData)?a.length:0;b=this[b.algorithm+"Placement"];var h=[],l=[],k=[],f;if(!(e.length<c)&&u(a[0])&&4===a[0].length){for(f=c+1;f<=g+c;f+=c){var m=e.slice(f-c-1,f);var t=a.slice(f-c-1,f);var d=m.length;var v=m[d-1];t=this.getPivotAndHLC(t);t=b(t);t=h.push([v].concat(t));l.push(v);k.push(h[t-1].slice(1))}this.endPoint=m[0]+(v-m[0])/
d*c;return{values:h,xData:l,yData:k}}},getPivotAndHLC:function(a){var b=-Infinity,c=Infinity,e=a[a.length-1][3];a.forEach(function(a){b=Math.max(b,a[1]);c=Math.min(c,a[2])});return[(b+c+e)/3,b,c,e]},standardPlacement:function(a){var b=a[1]-a[2];return[null,null,a[0]+b,2*a[0]-a[2],a[0],2*a[0]-a[1],a[0]-b,null,null]},camarillaPlacement:function(a){var b=a[1]-a[2];return[a[3]+1.5*b,a[3]+1.25*b,a[3]+1.1666*b,a[3]+1.0833*b,a[0],a[3]-1.0833*b,a[3]-1.1666*b,a[3]-1.25*b,a[3]-1.5*b]},fibonacciPlacement:function(a){var b=
a[1]-a[2];return[null,a[0]+b,a[0]+.618*b,a[0]+.382*b,a[0],a[0]-.382*b,a[0]-.618*b,a[0]-b,null]}},{destroyElements:function(){m(this,"destroyElements")},destroy:function(){m(this,"destroyElements")}});""});g(c,"masters/indicators/pivot-points.src.js",[],function(){})});
//# sourceMappingURL=pivot-points.js.map