/*
 Highstock JS v8.2.0 (2020-10-07)

 Indicator series type for Highstock

 (c) 2010-2019 Daniel Studencki

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/indicators/price-channel",["highcharts","highcharts/modules/stock"],function(g){a(g);a.Highcharts=g;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function g(a,e,m,b){a.hasOwnProperty(e)||(a[e]=b.apply(null,m))}a=a?a._modules:{};g(a,"Mixins/MultipleLines.js",[a["Core/Globals.js"],a["Core/Utilities.js"]],function(a,e){var m=
e.defined,b=e.error,u=e.merge,f=a.seriesTypes.sma;return{pointArrayMap:["top","bottom"],pointValKey:"top",linesApiNames:["bottomLine"],getTranslatedLinesNames:function(h){var a=[];(this.pointArrayMap||[]).forEach(function(b){b!==h&&a.push("plot"+b.charAt(0).toUpperCase()+b.slice(1))});return a},toYData:function(h){var a=[];(this.pointArrayMap||[]).forEach(function(b){a.push(h[b])});return a},translate:function(){var a=this,b=a.pointArrayMap,e=[],m;e=a.getTranslatedLinesNames();f.prototype.translate.apply(a,
arguments);a.points.forEach(function(h){b.forEach(function(b,f){m=h[b];null!==m&&(h[e[f]]=a.yAxis.toPixels(m,!0))})})},drawGraph:function(){var a=this,e=a.linesApiNames,l=a.points,g=l.length,q=a.options,r=a.graph,k={options:{gapSize:q.gapSize}},p=[],c;a.getTranslatedLinesNames(a.pointValKey).forEach(function(a,b){for(p[b]=[];g--;)c=l[g],p[b].push({x:c.x,plotX:c.plotX,plotY:c[a],isNull:!m(c[a])});g=l.length});e.forEach(function(c,e){p[e]?(a.points=p[e],q[c]?a.options=u(q[c].styles,k):b('Error: "There is no '+
c+' in DOCS options declared. Check if linesApiNames are consistent with your DOCS line names." at mixin/multiple-line.js:34'),a.graph=a["graph"+c],f.prototype.drawGraph.call(a),a["graph"+c]=a.graph):b('Error: "'+c+" doesn't have equivalent in pointArrayMap. To many elements in linesApiNames relative to pointArrayMap.\"")});a.points=l;a.options=q;a.graph=r;f.prototype.drawGraph.call(a)}}});g(a,"Mixins/ReduceArray.js",[],function(){return{minInArray:function(a,e){return a.reduce(function(a,b){return Math.min(a,
b[e])},Number.MAX_VALUE)},maxInArray:function(a,e){return a.reduce(function(a,b){return Math.max(a,b[e])},-Number.MAX_VALUE)},getArrayExtremes:function(a,e,m){return a.reduce(function(a,l){return[Math.min(a[0],l[e]),Math.max(a[1],l[m])]},[Number.MAX_VALUE,-Number.MAX_VALUE])}}});g(a,"Mixins/IndicatorRequired.js",[a["Core/Utilities.js"]],function(a){var e=a.error;return{isParentLoaded:function(a,b,l,f,h){if(a)return f?f(a):!0;e(h||this.generateMessage(l,b));return!1},generateMessage:function(a,b){return'Error: "'+
a+'" indicator type requires "'+b+'" indicator loaded before. Please read docs: https://api.highcharts.com/highstock/plotOptions.'+a}}});g(a,"Stock/Indicators/SMAIndicator.js",[a["Core/Series/Series.js"],a["Core/Globals.js"],a["Mixins/IndicatorRequired.js"],a["Core/Utilities.js"]],function(a,e,g,b){var l=a.seriesTypes,f=b.addEvent,h=b.error,m=b.extend,v=b.isArray,w=b.pick,q=b.splat,r=e.Series,k=l.ohlc.prototype,p=g.generateMessage;f(e.Series,"init",function(a){a=a.options;a.useOhlcData&&"highcharts-navigator-series"!==
a.id&&m(this,{pointValKey:k.pointValKey,keys:k.keys,pointArrayMap:k.pointArrayMap,toYData:k.toYData})});f(r,"afterSetOptions",function(a){a=a.options;var c=a.dataGrouping;c&&a.useOhlcData&&"highcharts-navigator-series"!==a.id&&(c.approximation="ohlc")});a.seriesType("sma","line",{name:void 0,tooltip:{valueDecimals:4},linkedTo:void 0,compareToMain:!1,params:{index:0,period:14}},{processData:function(){var a=this.options.compareToMain,b=this.linkedParent;r.prototype.processData.apply(this,arguments);
b&&b.compareValue&&a&&(this.compareValue=b.compareValue)},bindTo:{series:!0,eventName:"updatedData"},hasDerivedData:!0,useCommonDataGrouping:!0,nameComponents:["period"],nameSuffixes:[],calculateOn:"init",requiredIndicators:[],requireIndicators:function(){var a={allLoaded:!0};this.requiredIndicators.forEach(function(c){l[c]?l[c].prototype.requireIndicators():(a.allLoaded=!1,a.needed=c)});return a},init:function(a,b){function c(){var a=d.points||[],c=(d.xData||[]).length,b=d.getValues(d.linkedParent,
d.options.params)||{values:[],xData:[],yData:[]},e=[],n=!0;if(c&&!d.hasGroupedData&&d.visible&&d.points)if(d.cropped){if(d.xAxis){var f=d.xAxis.min;var h=d.xAxis.max}c=d.cropData(b.xData,b.yData,f,h);for(f=0;f<c.xData.length;f++)e.push([c.xData[f]].concat(q(c.yData[f])));c=b.xData.indexOf(d.xData[0]);f=b.xData.indexOf(d.xData[d.xData.length-1]);-1===c&&f===b.xData.length-2&&e[0][0]===a[0].x&&e.shift();d.updateData(e)}else b.xData.length!==c-1&&b.xData.length!==c+1&&(n=!1,d.updateData(b.values));n&&
(d.xData=b.xData,d.yData=b.yData,d.options.data=b.values);!1===d.bindTo.series&&(delete d.processedXData,d.isDirty=!0,d.redraw());d.isDirtyData=!1}var d=this,e=d.requireIndicators();if(!e.allLoaded)return h(p(d.type,e.needed));r.prototype.init.call(d,a,b);a.linkSeries();d.dataEventsToUnbind=[];if(!d.linkedParent)return h("Series "+d.options.linkedTo+" not found! Check `linkedTo`.",!1,a);d.dataEventsToUnbind.push(f(d.bindTo.series?d.linkedParent:d.linkedParent.xAxis,d.bindTo.eventName,c));if("init"===
d.calculateOn)c();else var n=f(d.chart,d.calculateOn,function(){c();n()});return d},getName:function(){var a=this.name,b=[];a||((this.nameComponents||[]).forEach(function(a,c){b.push(this.options.params[a]+w(this.nameSuffixes[c],""))},this),a=(this.nameBase||this.type.toUpperCase())+(this.nameComponents?" ("+b.join(", ")+")":""));return a},getValues:function(a,b){var c=b.period,d=a.xData;a=a.yData;var e=a.length,f=0,h=0,g=[],l=[],m=[],k=-1;if(!(d.length<c)){for(v(a[0])&&(k=b.index?b.index:0);f<c-
1;)h+=0>k?a[f]:a[f][k],f++;for(b=f;b<e;b++){h+=0>k?a[b]:a[b][k];var n=[d[b],h/c];g.push(n);l.push(n[0]);m.push(n[1]);h-=0>k?a[b-f]:a[b-f][k]}return{values:g,xData:l,yData:m}}},destroy:function(){this.dataEventsToUnbind.forEach(function(a){a()});r.prototype.destroy.apply(this,arguments)}});""});g(a,"Stock/Indicators/PCIndicator.js",[a["Core/Series/Series.js"],a["Mixins/MultipleLines.js"],a["Mixins/ReduceArray.js"],a["Core/Utilities.js"]],function(a,e,g,b){b=b.merge;var l=g.getArrayExtremes;a.seriesType("pc",
"sma",{params:{period:20},lineWidth:1,topLine:{styles:{lineColor:"#90ed7d",lineWidth:1}},bottomLine:{styles:{lineColor:"#f45b5b",lineWidth:1}},dataGrouping:{approximation:"averages"}},b(e,{pointArrayMap:["top","middle","bottom"],pointValKey:"middle",nameBase:"Price Channel",nameComponents:["period"],linesApiNames:["topLine","bottomLine"],getValues:function(a,b){b=b.period;var e=a.xData,f=(a=a.yData)?a.length:0,g=[],h=[],m=[],k;if(!(f<b)){for(k=b;k<=f;k++){var p=e[k-1];var c=a.slice(k-b,k);var n=l(c,
2,1);c=n[1];var t=n[0];n=(c+t)/2;g.push([p,c,n,t]);h.push(p);m.push([c,n,t])}return{values:g,xData:h,yData:m}}}}));""});g(a,"masters/indicators/price-channel.src.js",[],function(){})});
//# sourceMappingURL=price-channel.js.map