/*
 Highstock JS v8.2.0 (2020-10-07)

 Parabolic SAR Indicator for Highstock

 (c) 2010-2019 Grzegorz Blachliski

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/indicators/psar",["highcharts","highcharts/modules/stock"],function(k){a(k);a.Highcharts=k;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function k(a,g,f,n){a.hasOwnProperty(g)||(a[g]=n.apply(null,f))}a=a?a._modules:{};k(a,"Mixins/IndicatorRequired.js",[a["Core/Utilities.js"]],function(a){var g=a.error;return{isParentLoaded:function(a,
n,d,B,k){if(a)return B?B(a):!0;g(k||this.generateMessage(d,n));return!1},generateMessage:function(a,g){return'Error: "'+a+'" indicator type requires "'+g+'" indicator loaded before. Please read docs: https://api.highcharts.com/highstock/plotOptions.'+a}}});k(a,"Stock/Indicators/SMAIndicator.js",[a["Core/Series/Series.js"],a["Core/Globals.js"],a["Mixins/IndicatorRequired.js"],a["Core/Utilities.js"]],function(a,g,f,n){var d=a.seriesTypes,k=n.addEvent,y=n.error,z=n.extend,h=n.isArray,u=n.pick,l=n.splat,
m=g.Series,p=d.ohlc.prototype,w=f.generateMessage;k(g.Series,"init",function(e){e=e.options;e.useOhlcData&&"highcharts-navigator-series"!==e.id&&z(this,{pointValKey:p.pointValKey,keys:p.keys,pointArrayMap:p.pointArrayMap,toYData:p.toYData})});k(m,"afterSetOptions",function(e){e=e.options;var b=e.dataGrouping;b&&e.useOhlcData&&"highcharts-navigator-series"!==e.id&&(b.approximation="ohlc")});a.seriesType("sma","line",{name:void 0,tooltip:{valueDecimals:4},linkedTo:void 0,compareToMain:!1,params:{index:0,
period:14}},{processData:function(){var e=this.options.compareToMain,b=this.linkedParent;m.prototype.processData.apply(this,arguments);b&&b.compareValue&&e&&(this.compareValue=b.compareValue)},bindTo:{series:!0,eventName:"updatedData"},hasDerivedData:!0,useCommonDataGrouping:!0,nameComponents:["period"],nameSuffixes:[],calculateOn:"init",requiredIndicators:[],requireIndicators:function(){var e={allLoaded:!0};this.requiredIndicators.forEach(function(b){d[b]?d[b].prototype.requireIndicators():(e.allLoaded=
!1,e.needed=b)});return e},init:function(e,b){function a(){var e=c.points||[],b=(c.xData||[]).length,a=c.getValues(c.linkedParent,c.options.params)||{values:[],xData:[],yData:[]},g=[],f=!0;if(b&&!c.hasGroupedData&&c.visible&&c.points)if(c.cropped){if(c.xAxis){var d=c.xAxis.min;var h=c.xAxis.max}b=c.cropData(a.xData,a.yData,d,h);for(d=0;d<b.xData.length;d++)g.push([b.xData[d]].concat(l(b.yData[d])));b=a.xData.indexOf(c.xData[0]);d=a.xData.indexOf(c.xData[c.xData.length-1]);-1===b&&d===a.xData.length-
2&&g[0][0]===e[0].x&&g.shift();c.updateData(g)}else a.xData.length!==b-1&&a.xData.length!==b+1&&(f=!1,c.updateData(a.values));f&&(c.xData=a.xData,c.yData=a.yData,c.options.data=a.values);!1===c.bindTo.series&&(delete c.processedXData,c.isDirty=!0,c.redraw());c.isDirtyData=!1}var c=this,g=c.requireIndicators();if(!g.allLoaded)return y(w(c.type,g.needed));m.prototype.init.call(c,e,b);e.linkSeries();c.dataEventsToUnbind=[];if(!c.linkedParent)return y("Series "+c.options.linkedTo+" not found! Check `linkedTo`.",
!1,e);c.dataEventsToUnbind.push(k(c.bindTo.series?c.linkedParent:c.linkedParent.xAxis,c.bindTo.eventName,a));if("init"===c.calculateOn)a();else var f=k(c.chart,c.calculateOn,function(){a();f()});return c},getName:function(){var a=this.name,b=[];a||((this.nameComponents||[]).forEach(function(a,c){b.push(this.options.params[a]+u(this.nameSuffixes[c],""))},this),a=(this.nameBase||this.type.toUpperCase())+(this.nameComponents?" ("+b.join(", ")+")":""));return a},getValues:function(a,b){var g=b.period,
c=a.xData;a=a.yData;var e=a.length,d=0,f=0,n=[],l=[],k=[],m=-1;if(!(c.length<g)){for(h(a[0])&&(m=b.index?b.index:0);d<g-1;)f+=0>m?a[d]:a[d][m],d++;for(b=d;b<e;b++){f+=0>m?a[b]:a[b][m];var p=[c[b],f/g];n.push(p);l.push(p[0]);k.push(p[1]);f-=0>m?a[b-d]:a[b-d][m]}return{values:n,xData:l,yData:k}}},destroy:function(){this.dataEventsToUnbind.forEach(function(a){a()});m.prototype.destroy.apply(this,arguments)}});""});k(a,"Stock/Indicators/PSARIndicator.js",[a["Core/Series/Series.js"]],function(a){a.seriesType("psar",
"sma",{lineWidth:0,marker:{enabled:!0},states:{hover:{lineWidthPlus:0}},params:{initialAccelerationFactor:.02,maxAccelerationFactor:.2,increment:.02,index:2,decimals:4}},{nameComponents:!1,getValues:function(a,f){var g=a.xData;a=a.yData;var d=a[0][1],k=f.maxAccelerationFactor,y=f.increment,z=f.initialAccelerationFactor,h=a[0][2],u=f.decimals,l=f.index,m=[],p=[],w=[],e=1,b;if(!(l>=a.length)){for(b=0;b<l;b++)d=Math.max(a[b][1],d),h=Math.min(a[b][2],parseFloat(h.toFixed(u)));var v=a[b][1]>h?1:-1;f=f.initialAccelerationFactor;
var c=f*(d-h);m.push([g[l],h]);p.push(g[l]);w.push(parseFloat(h.toFixed(u)));for(b=l+1;b<a.length;b++){l=a[b-1][2];var q=a[b-2][2];var x=a[b-1][1];var A=a[b-2][1];var r=a[b][1];var t=a[b][2];null!==q&&null!==A&&null!==l&&null!==x&&null!==r&&null!==t&&(h=v===e?1===v?h+c<Math.min(q,l)?h+c:Math.min(q,l):h+c>Math.max(A,x)?h+c:Math.max(A,x):d,l=1===v?r>d?r:d:t<d?t:d,r=1===e&&t>h||-1===e&&r>h?1:-1,e=r,c=l,t=y,q=k,x=z,f=e===v?1===e&&c>d?f===q?q:parseFloat((f+t).toFixed(2)):-1===e&&c<d?f===q?q:parseFloat((f+
t).toFixed(2)):f:x,d=l-h,c=f*d,m.push([g[b],parseFloat(h.toFixed(u))]),p.push(g[b]),w.push(parseFloat(h.toFixed(u))),e=v,v=r,d=l)}return{values:m,xData:p,yData:w}}}});""});k(a,"masters/indicators/psar.src.js",[],function(){})});
//# sourceMappingURL=psar.js.map