/*
 Highstock JS v8.2.0 (2020-10-07)

 Indicator series type for Highstock

 (c) 2010-2019 Kamil Kulig

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/indicators/regressions",["highcharts","highcharts/modules/stock"],function(h){a(h);a.Highcharts=h;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function h(a,q,u,b){a.hasOwnProperty(q)||(a[q]=b.apply(null,u))}a=a?a._modules:{};h(a,"Mixins/IndicatorRequired.js",[a["Core/Utilities.js"]],function(a){var q=a.error;return{isParentLoaded:function(a,
b,e,f,g){if(a)return f?f(a):!0;q(g||this.generateMessage(e,b));return!1},generateMessage:function(a,b){return'Error: "'+a+'" indicator type requires "'+b+'" indicator loaded before. Please read docs: https://api.highcharts.com/highstock/plotOptions.'+a}}});h(a,"Stock/Indicators/SMAIndicator.js",[a["Core/Series/Series.js"],a["Core/Globals.js"],a["Mixins/IndicatorRequired.js"],a["Core/Utilities.js"]],function(a,q,h,b){var e=a.seriesTypes,f=b.addEvent,g=b.error,v=b.extend,r=b.isArray,n=b.pick,k=b.splat,
l=q.Series,m=e.ohlc.prototype,t=h.generateMessage;f(q.Series,"init",function(d){d=d.options;d.useOhlcData&&"highcharts-navigator-series"!==d.id&&v(this,{pointValKey:m.pointValKey,keys:m.keys,pointArrayMap:m.pointArrayMap,toYData:m.toYData})});f(l,"afterSetOptions",function(d){d=d.options;var b=d.dataGrouping;b&&d.useOhlcData&&"highcharts-navigator-series"!==d.id&&(b.approximation="ohlc")});a.seriesType("sma","line",{name:void 0,tooltip:{valueDecimals:4},linkedTo:void 0,compareToMain:!1,params:{index:0,
period:14}},{processData:function(){var b=this.options.compareToMain,a=this.linkedParent;l.prototype.processData.apply(this,arguments);a&&a.compareValue&&b&&(this.compareValue=a.compareValue)},bindTo:{series:!0,eventName:"updatedData"},hasDerivedData:!0,useCommonDataGrouping:!0,nameComponents:["period"],nameSuffixes:[],calculateOn:"init",requiredIndicators:[],requireIndicators:function(){var b={allLoaded:!0};this.requiredIndicators.forEach(function(a){e[a]?e[a].prototype.requireIndicators():(b.allLoaded=
!1,b.needed=a)});return b},init:function(b,a){function d(){var b=c.points||[],a=(c.xData||[]).length,d=c.getValues(c.linkedParent,c.options.params)||{values:[],xData:[],yData:[]},e=[],f=!0;if(a&&!c.hasGroupedData&&c.visible&&c.points)if(c.cropped){if(c.xAxis){var p=c.xAxis.min;var g=c.xAxis.max}a=c.cropData(d.xData,d.yData,p,g);for(p=0;p<a.xData.length;p++)e.push([a.xData[p]].concat(k(a.yData[p])));a=d.xData.indexOf(c.xData[0]);p=d.xData.indexOf(c.xData[c.xData.length-1]);-1===a&&p===d.xData.length-
2&&e[0][0]===b[0].x&&e.shift();c.updateData(e)}else d.xData.length!==a-1&&d.xData.length!==a+1&&(f=!1,c.updateData(d.values));f&&(c.xData=d.xData,c.yData=d.yData,c.options.data=d.values);!1===c.bindTo.series&&(delete c.processedXData,c.isDirty=!0,c.redraw());c.isDirtyData=!1}var c=this,e=c.requireIndicators();if(!e.allLoaded)return g(t(c.type,e.needed));l.prototype.init.call(c,b,a);b.linkSeries();c.dataEventsToUnbind=[];if(!c.linkedParent)return g("Series "+c.options.linkedTo+" not found! Check `linkedTo`.",
!1,b);c.dataEventsToUnbind.push(f(c.bindTo.series?c.linkedParent:c.linkedParent.xAxis,c.bindTo.eventName,d));if("init"===c.calculateOn)d();else var p=f(c.chart,c.calculateOn,function(){d();p()});return c},getName:function(){var b=this.name,a=[];b||((this.nameComponents||[]).forEach(function(b,d){a.push(this.options.params[b]+n(this.nameSuffixes[d],""))},this),b=(this.nameBase||this.type.toUpperCase())+(this.nameComponents?" ("+a.join(", ")+")":""));return b},getValues:function(b,a){var d=a.period,
c=b.xData;b=b.yData;var e=b.length,f=0,g=0,p=[],l=[],n=[],k=-1;if(!(c.length<d)){for(r(b[0])&&(k=a.index?a.index:0);f<d-1;)g+=0>k?b[f]:b[f][k],f++;for(a=f;a<e;a++){g+=0>k?b[a]:b[a][k];var m=[c[a],g/d];p.push(m);l.push(m[0]);n.push(m[1]);g-=0>k?b[a-f]:b[a-f][k]}return{values:p,xData:l,yData:n}}},destroy:function(){this.dataEventsToUnbind.forEach(function(b){b()});l.prototype.destroy.apply(this,arguments)}});""});h(a,"Stock/Indicators/RegressionIndicators.js",[a["Core/Series/Series.js"],a["Core/Utilities.js"]],
function(a,h){var q=h.isArray;a.seriesType("linearRegression","sma",{params:{xAxisUnit:void 0},tooltip:{valueDecimals:4}},{nameBase:"Linear Regression Indicator",getRegressionLineParameters:function(b,a){var f=this.options.params.index,e=function(a,b){return q(a)?a[b]:a},h=b.reduce(function(a,b){return b+a},0),r=a.reduce(function(a,b){return e(b,f)+a},0);h/=b.length;r/=a.length;var n=0,k=0,l;for(l=0;l<b.length;l++){var m=b[l]-h;var t=e(a[l],f)-r;n+=m*t;k+=Math.pow(m,2)}b=k?n/k:0;return{slope:b,intercept:r-
b*h}},getEndPointY:function(a,e){return a.slope*e+a.intercept},transformXData:function(a,e){var b=a[0];return a.map(function(a){return(a-b)/e})},findClosestDistance:function(a){var b,f;for(f=1;f<a.length-1;f++){var g=a[f]-a[f-1];0<g&&("undefined"===typeof b||g<b)&&(b=g)}return b},getValues:function(a,e){var b=a.xData;a=a.yData;e=e.period;var g,h={xData:[],yData:[],values:[]},q=this.options.params.xAxisUnit||this.findClosestDistance(b);for(g=e-1;g<=b.length-1;g++){var n=g-e+1;var k=g+1;var l=b[g];
var m=b.slice(n,k);n=a.slice(n,k);k=this.transformXData(m,q);m=this.getRegressionLineParameters(k,n);n=this.getEndPointY(m,k[k.length-1]);h.values.push({regressionLineParameters:m,x:l,y:n});h.xData.push(l);h.yData.push(n)}return h}});a.seriesType("linearRegressionSlope","linearRegression",{},{nameBase:"Linear Regression Slope Indicator",getEndPointY:function(a){return a.slope}});a.seriesType("linearRegressionIntercept","linearRegression",{},{nameBase:"Linear Regression Intercept Indicator",getEndPointY:function(a){return a.intercept}});
a.seriesType("linearRegressionAngle","linearRegression",{tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span>{series.name}: <b>{point.y}\u00b0</b><br/>'}},{nameBase:"Linear Regression Angle Indicator",slopeToAngle:function(a){return 180/Math.PI*Math.atan(a)},getEndPointY:function(a){return this.slopeToAngle(a.slope)}});""});h(a,"masters/indicators/regressions.src.js",[],function(){})});
//# sourceMappingURL=regressions.js.map