/*
 Highstock JS v8.2.0 (2020-10-07)

 Indicator series type for Highstock

 (c) 2010-2019 Pawe Fus

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/indicators/rsi",["highcharts","highcharts/modules/stock"],function(k){a(k);a.Highcharts=k;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function k(a,m,v,b){a.hasOwnProperty(m)||(a[m]=b.apply(null,v))}a=a?a._modules:{};k(a,"Mixins/IndicatorRequired.js",[a["Core/Utilities.js"]],function(a){var m=a.error;return{isParentLoaded:function(a,
b,e,g,l){if(a)return g?g(a):!0;m(l||this.generateMessage(e,b));return!1},generateMessage:function(a,b){return'Error: "'+a+'" indicator type requires "'+b+'" indicator loaded before. Please read docs: https://api.highcharts.com/highstock/plotOptions.'+a}}});k(a,"Stock/Indicators/SMAIndicator.js",[a["Core/Series/Series.js"],a["Core/Globals.js"],a["Mixins/IndicatorRequired.js"],a["Core/Utilities.js"]],function(a,m,k,b){var e=a.seriesTypes,g=b.addEvent,l=b.error,v=b.extend,n=b.isArray,r=b.pick,t=b.splat,
p=m.Series,f=e.ohlc.prototype,q=k.generateMessage;g(m.Series,"init",function(c){c=c.options;c.useOhlcData&&"highcharts-navigator-series"!==c.id&&v(this,{pointValKey:f.pointValKey,keys:f.keys,pointArrayMap:f.pointArrayMap,toYData:f.toYData})});g(p,"afterSetOptions",function(c){c=c.options;var a=c.dataGrouping;a&&c.useOhlcData&&"highcharts-navigator-series"!==c.id&&(a.approximation="ohlc")});a.seriesType("sma","line",{name:void 0,tooltip:{valueDecimals:4},linkedTo:void 0,compareToMain:!1,params:{index:0,
period:14}},{processData:function(){var c=this.options.compareToMain,a=this.linkedParent;p.prototype.processData.apply(this,arguments);a&&a.compareValue&&c&&(this.compareValue=a.compareValue)},bindTo:{series:!0,eventName:"updatedData"},hasDerivedData:!0,useCommonDataGrouping:!0,nameComponents:["period"],nameSuffixes:[],calculateOn:"init",requiredIndicators:[],requireIndicators:function(){var c={allLoaded:!0};this.requiredIndicators.forEach(function(a){e[a]?e[a].prototype.requireIndicators():(c.allLoaded=
!1,c.needed=a)});return c},init:function(a,h){function c(){var a=d.points||[],c=(d.xData||[]).length,b=d.getValues(d.linkedParent,d.options.params)||{values:[],xData:[],yData:[]},h=[],e=!0;if(c&&!d.hasGroupedData&&d.visible&&d.points)if(d.cropped){if(d.xAxis){var g=d.xAxis.min;var f=d.xAxis.max}c=d.cropData(b.xData,b.yData,g,f);for(g=0;g<c.xData.length;g++)h.push([c.xData[g]].concat(t(c.yData[g])));c=b.xData.indexOf(d.xData[0]);g=b.xData.indexOf(d.xData[d.xData.length-1]);-1===c&&g===b.xData.length-
2&&h[0][0]===a[0].x&&h.shift();d.updateData(h)}else b.xData.length!==c-1&&b.xData.length!==c+1&&(e=!1,d.updateData(b.values));e&&(d.xData=b.xData,d.yData=b.yData,d.options.data=b.values);!1===d.bindTo.series&&(delete d.processedXData,d.isDirty=!0,d.redraw());d.isDirtyData=!1}var d=this,b=d.requireIndicators();if(!b.allLoaded)return l(q(d.type,b.needed));p.prototype.init.call(d,a,h);a.linkSeries();d.dataEventsToUnbind=[];if(!d.linkedParent)return l("Series "+d.options.linkedTo+" not found! Check `linkedTo`.",
!1,a);d.dataEventsToUnbind.push(g(d.bindTo.series?d.linkedParent:d.linkedParent.xAxis,d.bindTo.eventName,c));if("init"===d.calculateOn)c();else var e=g(d.chart,d.calculateOn,function(){c();e()});return d},getName:function(){var c=this.name,a=[];c||((this.nameComponents||[]).forEach(function(c,d){a.push(this.options.params[c]+r(this.nameSuffixes[d],""))},this),c=(this.nameBase||this.type.toUpperCase())+(this.nameComponents?" ("+a.join(", ")+")":""));return c},getValues:function(a,b){var c=b.period,
d=a.xData;a=a.yData;var g=a.length,e=0,f=0,h=[],k=[],m=[],l=-1;if(!(d.length<c)){for(n(a[0])&&(l=b.index?b.index:0);e<c-1;)f+=0>l?a[e]:a[e][l],e++;for(b=e;b<g;b++){f+=0>l?a[b]:a[b][l];var p=[d[b],f/c];h.push(p);k.push(p[0]);m.push(p[1]);f-=0>l?a[b-e]:a[b-e][l]}return{values:h,xData:k,yData:m}}},destroy:function(){this.dataEventsToUnbind.forEach(function(a){a()});p.prototype.destroy.apply(this,arguments)}});""});k(a,"Stock/Indicators/RSIIndicator.js",[a["Core/Series/Series.js"],a["Core/Utilities.js"]],
function(a,k){var m=k.isArray;a.seriesType("rsi","sma",{params:{period:14,decimals:4}},{getValues:function(a,e){var b=e.period,l=a.xData,k=(a=a.yData)?a.length:0;e=e.decimals;var n=1,r=[],t=[],p=[],f=0,q=0,c;if(!(l.length<b)&&m(a[0])&&4===a[0].length){for(;n<b;){var h=parseFloat((a[n][3]-a[n-1][3]).toFixed(e));0<h?f+=h:q+=Math.abs(h);n++}var u=parseFloat((f/(b-1)).toFixed(e));for(c=parseFloat((q/(b-1)).toFixed(e));n<k;n++)h=parseFloat((a[n][3]-a[n-1][3]).toFixed(e)),0<h?(f=h,q=0):(f=0,q=Math.abs(h)),
u=parseFloat(((u*(b-1)+f)/b).toFixed(e)),c=parseFloat(((c*(b-1)+q)/b).toFixed(e)),f=0===c?100:0===u?0:parseFloat((100-100/(1+u/c)).toFixed(e)),r.push([l[n],f]),t.push(l[n]),p.push(f);return{values:r,xData:t,yData:p}}}});""});k(a,"masters/indicators/rsi.src.js",[],function(){})});
//# sourceMappingURL=rsi.js.map