/*
 Highstock JS v8.2.0 (2020-10-07)

 Indicator series type for Highstock

 (c) 2010-2019 Wojciech Chmiel

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/indicators/supertrend",["highcharts","highcharts/modules/stock"],function(m){a(m);a.Highcharts=m;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function m(a,n,B,r){a.hasOwnProperty(n)||(a[n]=r.apply(null,B))}a=a?a._modules:{};m(a,"Mixins/IndicatorRequired.js",[a["Core/Utilities.js"]],function(a){var n=a.error;return{isParentLoaded:function(a,
r,k,p,A){if(a)return p?p(a):!0;n(A||this.generateMessage(k,r));return!1},generateMessage:function(a,r){return'Error: "'+a+'" indicator type requires "'+r+'" indicator loaded before. Please read docs: https://api.highcharts.com/highstock/plotOptions.'+a}}});m(a,"Stock/Indicators/SMAIndicator.js",[a["Core/Series/Series.js"],a["Core/Globals.js"],a["Mixins/IndicatorRequired.js"],a["Core/Utilities.js"]],function(a,n,B,r){var k=a.seriesTypes,p=r.addEvent,A=r.error,m=r.extend,D=r.isArray,z=r.pick,v=r.splat,
b=n.Series,f=k.ohlc.prototype,C=B.generateMessage;p(n.Series,"init",function(e){e=e.options;e.useOhlcData&&"highcharts-navigator-series"!==e.id&&m(this,{pointValKey:f.pointValKey,keys:f.keys,pointArrayMap:f.pointArrayMap,toYData:f.toYData})});p(b,"afterSetOptions",function(e){e=e.options;var b=e.dataGrouping;b&&e.useOhlcData&&"highcharts-navigator-series"!==e.id&&(b.approximation="ohlc")});a.seriesType("sma","line",{name:void 0,tooltip:{valueDecimals:4},linkedTo:void 0,compareToMain:!1,params:{index:0,
period:14}},{processData:function(){var e=this.options.compareToMain,a=this.linkedParent;b.prototype.processData.apply(this,arguments);a&&a.compareValue&&e&&(this.compareValue=a.compareValue)},bindTo:{series:!0,eventName:"updatedData"},hasDerivedData:!0,useCommonDataGrouping:!0,nameComponents:["period"],nameSuffixes:[],calculateOn:"init",requiredIndicators:[],requireIndicators:function(){var e={allLoaded:!0};this.requiredIndicators.forEach(function(b){k[b]?k[b].prototype.requireIndicators():(e.allLoaded=
!1,e.needed=b)});return e},init:function(e,a){function f(){var e=c.points||[],d=(c.xData||[]).length,b=c.getValues(c.linkedParent,c.options.params)||{values:[],xData:[],yData:[]},a=[],f=!0;if(d&&!c.hasGroupedData&&c.visible&&c.points)if(c.cropped){if(c.xAxis){var g=c.xAxis.min;var k=c.xAxis.max}d=c.cropData(b.xData,b.yData,g,k);for(g=0;g<d.xData.length;g++)a.push([d.xData[g]].concat(v(d.yData[g])));d=b.xData.indexOf(c.xData[0]);g=b.xData.indexOf(c.xData[c.xData.length-1]);-1===d&&g===b.xData.length-
2&&a[0][0]===e[0].x&&a.shift();c.updateData(a)}else b.xData.length!==d-1&&b.xData.length!==d+1&&(f=!1,c.updateData(b.values));f&&(c.xData=b.xData,c.yData=b.yData,c.options.data=b.values);!1===c.bindTo.series&&(delete c.processedXData,c.isDirty=!0,c.redraw());c.isDirtyData=!1}var c=this,k=c.requireIndicators();if(!k.allLoaded)return A(C(c.type,k.needed));b.prototype.init.call(c,e,a);e.linkSeries();c.dataEventsToUnbind=[];if(!c.linkedParent)return A("Series "+c.options.linkedTo+" not found! Check `linkedTo`.",
!1,e);c.dataEventsToUnbind.push(p(c.bindTo.series?c.linkedParent:c.linkedParent.xAxis,c.bindTo.eventName,f));if("init"===c.calculateOn)f();else var t=p(c.chart,c.calculateOn,function(){f();t()});return c},getName:function(){var b=this.name,a=[];b||((this.nameComponents||[]).forEach(function(b,e){a.push(this.options.params[b]+z(this.nameSuffixes[e],""))},this),b=(this.nameBase||this.type.toUpperCase())+(this.nameComponents?" ("+a.join(", ")+")":""));return b},getValues:function(b,a){var e=a.period,
c=b.xData;b=b.yData;var f=b.length,v=0,k=0,d=[],q=[],l=[],h=-1;if(!(c.length<e)){for(D(b[0])&&(h=a.index?a.index:0);v<e-1;)k+=0>h?b[v]:b[v][h],v++;for(a=v;a<f;a++){k+=0>h?b[a]:b[a][h];var g=[c[a],k/e];d.push(g);q.push(g[0]);l.push(g[1]);k-=0>h?b[a-v]:b[a-v][h]}return{values:d,xData:q,yData:l}}},destroy:function(){this.dataEventsToUnbind.forEach(function(b){b()});b.prototype.destroy.apply(this,arguments)}});""});m(a,"Stock/Indicators/ATRIndicator.js",[a["Core/Series/Series.js"],a["Core/Utilities.js"]],
function(a,n){function B(a,p){return Math.max(a[1]-a[2],"undefined"===typeof p?0:Math.abs(a[1]-p[3]),"undefined"===typeof p?0:Math.abs(a[2]-p[3]))}var r=n.isArray;a.seriesType("atr","sma",{params:{period:14}},{getValues:function(a,p){p=p.period;var k=a.xData,n=(a=a.yData)?a.length:0,m=1,z=0,v=0,b=[],f=[],C=[],e;var F=[[k[0],a[0]]];if(!(k.length<=p)&&r(a[0])&&4===a[0].length){for(e=1;e<=n;e++)if(F.push([k[e],a[e]]),p<m){var u=p;var c=k[e-1],G=B(a[e-1],a[e-2]);u=[c,(z*(u-1)+G)/u];z=u[1];b.push(u);f.push(u[0]);
C.push(u[1])}else p===m?(z=v/(e-1),b.push([k[e-1],z]),f.push(k[e-1]),C.push(z)):v+=B(a[e-1],a[e-2]),m++;return{values:b,xData:f,yData:C}}}});""});m(a,"Stock/Indicators/SupertrendIndicator.js",[a["Core/Series/Series.js"],a["Core/Utilities.js"]],function(a,n){function m(a,b,f){return{index:b,close:a.yData[b][f],x:a.xData[b]}}var r=a.seriesTypes,k=n.correctFloat,p=n.isArray,A=n.merge,E=n.objectEach,D=r.atr,z=r.sma;a.seriesType("supertrend","sma",{params:{multiplier:3,period:10},risingTrendColor:"#06B535",
fallingTrendColor:"#F21313",changeTrendLine:{styles:{lineWidth:1,lineColor:"#333333",dashStyle:"LongDash"}}},{nameBase:"Supertrend",nameComponents:["multiplier","period"],requiredIndicators:["atr"],init:function(){z.prototype.init.apply(this,arguments);var a=this.options;a.cropThreshold=this.linkedParent.options.cropThreshold-(a.params.period-1)},drawGraph:function(){var a=this,b=a.options,f=a.linkedParent,k=f?f.points:[],e=a.points,p=a.graph,u=e.length,c=k.length-u;c=0<c?c:0;for(var r={options:{gapSize:b.gapSize}},
t={top:[],bottom:[],intersect:[]},n={top:{styles:{lineWidth:b.lineWidth,lineColor:b.fallingTrendColor||b.color,dashStyle:b.dashStyle}},bottom:{styles:{lineWidth:b.lineWidth,lineColor:b.risingTrendColor||b.color,dashStyle:b.dashStyle}},intersect:b.changeTrendLine},d,q,l,h,g,w,x,y;u--;)d=e[u],q=e[u-1],l=k[u-1+c],h=k[u-2+c],g=k[u+c],w=k[u+c+1],x=d.options.color,y={x:d.x,plotX:d.plotX,plotY:d.plotY,isNull:!1},!h&&l&&f.yData[l.index-1]&&(h=m(f,l.index-1,3)),!w&&g&&f.yData[g.index+1]&&(w=m(f,g.index+1,
3)),!l&&h&&f.yData[h.index+1]?l=m(f,h.index+1,3):!l&&g&&f.yData[g.index-1]&&(l=m(f,g.index-1,3)),d&&l&&g&&h&&d.x!==l.x&&(d.x===g.x?(h=l,l=g):d.x===h.x?(l=h,h={close:f.yData[l.index-1][3],x:f.xData[l.index-1]}):w&&d.x===w.x&&(l=w,h=g)),q&&h&&l?(g={x:q.x,plotX:q.plotX,plotY:q.plotY,isNull:!1},d.y>=l.close&&q.y>=h.close?(d.color=x||b.fallingTrendColor||b.color,t.top.push(y)):d.y<l.close&&q.y<h.close?(d.color=x||b.risingTrendColor||b.color,t.bottom.push(y)):(t.intersect.push(y),t.intersect.push(g),t.intersect.push(A(g,
{isNull:!0})),d.y>=l.close&&q.y<h.close?(d.color=x||b.fallingTrendColor||b.color,q.color=x||b.risingTrendColor||b.color,t.top.push(y),t.top.push(A(g,{isNull:!0}))):d.y<l.close&&q.y>=h.close&&(d.color=x||b.risingTrendColor||b.color,q.color=x||b.fallingTrendColor||b.color,t.bottom.push(y),t.bottom.push(A(g,{isNull:!0}))))):l&&(d.y>=l.close?(d.color=x||b.fallingTrendColor||b.color,t.top.push(y)):(d.color=x||b.risingTrendColor||b.color,t.bottom.push(y)));E(t,function(b,c){a.points=b;a.options=A(n[c].styles,
r);a.graph=a["graph"+c+"Line"];z.prototype.drawGraph.call(a);a["graph"+c+"Line"]=a.graph});a.points=e;a.options=b;a.graph=p},getValues:function(a,b){var f=b.period;b=b.multiplier;var m=a.xData,e=a.yData,r=[],u=[],c=[],n=0===f?0:f-1,t=[],v=[],d;if(!(m.length<=f||!p(e[0])||4!==e[0].length||0>f)){a=D.prototype.getValues.call(this,a,{period:f}).yData;for(d=0;d<a.length;d++){var q=e[n+d];var l=e[n+d-1]||[];var h=t[d-1];var g=v[d-1];var w=c[d-1];0===d&&(h=g=w=0);f=k((q[1]+q[2])/2+b*a[d]);var x=k((q[1]+
q[2])/2-b*a[d]);t[d]=f<h||l[3]>h?f:h;v[d]=x>g||l[3]<g?x:g;if(w===h&&q[3]<t[d]||w===g&&q[3]<v[d])var y=t[d];else if(w===h&&q[3]>t[d]||w===g&&q[3]>v[d])y=v[d];r.push([m[n+d],y]);u.push(m[n+d]);c.push(y)}return{values:r,xData:u,yData:c}}}});""});m(a,"masters/indicators/supertrend.src.js",[],function(){})});
//# sourceMappingURL=supertrend.js.map