/*
 Highstock JS v8.2.0 (2020-10-07)

 Indicator series type for Highstock

 (c) 2010-2019 Rafal Sebestjanski

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/indicators/tema",["highcharts","highcharts/modules/stock"],function(g){a(g);a.Highcharts=g;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function g(a,e,u,m){a.hasOwnProperty(e)||(a[e]=m.apply(null,u))}a=a?a._modules:{};g(a,"Mixins/IndicatorRequired.js",[a["Core/Utilities.js"]],function(a){var e=a.error;return{isParentLoaded:function(a,
m,l,d,h){if(a)return d?d(a):!0;e(h||this.generateMessage(l,m));return!1},generateMessage:function(a,e){return'Error: "'+a+'" indicator type requires "'+e+'" indicator loaded before. Please read docs: https://api.highcharts.com/highstock/plotOptions.'+a}}});g(a,"Stock/Indicators/EMAIndicator.js",[a["Core/Series/Series.js"],a["Core/Utilities.js"]],function(a,e){var g=e.correctFloat,m=e.isArray;a.seriesType("ema","sma",{params:{index:3,period:9}},{accumulatePeriodPoints:function(a,d,h){for(var c=0,b=
0,l;b<a;)l=0>d?h[b]:h[b][d],c+=l,b++;return c},calculateEma:function(a,d,h,c,b,w,e){a=a[h-1];d=0>w?d[h-1]:d[h-1][w];c="undefined"===typeof b?e:g(d*c+b*(1-c));return[a,c]},getValues:function(a,d){var h=d.period,c=a.xData,b=(a=a.yData)?a.length:0,e=2/(h+1),g=[],l=[],p=[],q=-1;if(!(b<h)){m(a[0])&&(q=d.index?d.index:0);d=this.accumulatePeriodPoints(h,q,a);for(d/=h;h<b+1;h++){var n=this.calculateEma(c,a,h,e,n,q,d);g.push(n);l.push(n[0]);p.push(n[1]);n=n[1]}return{values:g,xData:l,yData:p}}}});""});g(a,
"Stock/Indicators/TEMAIndicator.js",[a["Core/Series/Series.js"],a["Mixins/IndicatorRequired.js"],a["Core/Utilities.js"]],function(a,e,g){var m=g.correctFloat,l=g.isArray,d=a.seriesTypes.ema;a.seriesType("tema","ema",{},{init:function(){var a=arguments,c=this;e.isParentLoaded(d,"ema",c.type,function(h){h.prototype.init.apply(c,a)})},getEMA:function(a,c,b,g,e,l){return d.prototype.calculateEma(l||[],a,"undefined"===typeof e?1:e,this.chart.series[0].EMApercent,c,"undefined"===typeof g?-1:g,b)},getTemaPoint:function(a,
c,b,d){return[a[d-3],m(3*b.level1-3*b.level2+b.level3)]},getValues:function(a,c){var b=c.period,g=2*b,e=3*b,h=a.xData,p=a.yData,q=p?p.length:0,n=-1,m=[],x=[],y=[],r=[],v=[],k,t,f={};a.EMApercent=2/(b+1);if(!(q<3*b-2)){l(p[0])&&(n=c.index?c.index:0);a=d.prototype.accumulatePeriodPoints(b,n,p);c=a/b;a=0;for(k=b;k<q+3;k++){k<q+1&&(f.level1=this.getEMA(p,u,c,n,k)[1],r.push(f.level1));var u=f.level1;if(k<g)a+=f.level1;else{k===g&&(c=a/b,a=0);f.level1=r[k-b-1];f.level2=this.getEMA([f.level1],z,c)[1];v.push(f.level2);
var z=f.level2;if(k<e)a+=f.level2;else{k===e&&(c=a/b);k===q+1&&(f.level1=r[k-b-1],f.level2=this.getEMA([f.level1],z,c)[1],v.push(f.level2));f.level1=r[k-b-2];f.level2=v[k-2*b-1];f.level3=this.getEMA([f.level2],f.prevLevel3,c)[1];if(t=this.getTemaPoint(h,e,f,k))m.push(t),x.push(t[0]),y.push(t[1]);f.prevLevel3=f.level3}}}return{values:m,xData:x,yData:y}}}});""});g(a,"masters/indicators/tema.src.js",[],function(){})});
//# sourceMappingURL=tema.js.map