/*
 Highstock JS v8.2.0 (2020-10-07)

 Indicator series type for Highstock

 (c) 2010-2019 Sebastian Bochan

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/indicators/trendline",["highcharts","highcharts/modules/stock"],function(h){a(h);a.Highcharts=h;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function h(a,l,v,f){a.hasOwnProperty(l)||(a[l]=f.apply(null,v))}a=a?a._modules:{};h(a,"Mixins/IndicatorRequired.js",[a["Core/Utilities.js"]],function(a){var l=a.error;return{isParentLoaded:function(a,
f,e,m,g){if(a)return m?m(a):!0;l(g||this.generateMessage(e,f));return!1},generateMessage:function(a,f){return'Error: "'+a+'" indicator type requires "'+f+'" indicator loaded before. Please read docs: https://api.highcharts.com/highstock/plotOptions.'+a}}});h(a,"Stock/Indicators/SMAIndicator.js",[a["Core/Series/Series.js"],a["Core/Globals.js"],a["Mixins/IndicatorRequired.js"],a["Core/Utilities.js"]],function(a,l,h,f){var e=a.seriesTypes,m=f.addEvent,g=f.error,w=f.extend,u=f.isArray,k=f.pick,r=f.splat,
n=l.Series,p=e.ohlc.prototype,q=h.generateMessage;m(l.Series,"init",function(c){c=c.options;c.useOhlcData&&"highcharts-navigator-series"!==c.id&&w(this,{pointValKey:p.pointValKey,keys:p.keys,pointArrayMap:p.pointArrayMap,toYData:p.toYData})});m(n,"afterSetOptions",function(c){c=c.options;var a=c.dataGrouping;a&&c.useOhlcData&&"highcharts-navigator-series"!==c.id&&(a.approximation="ohlc")});a.seriesType("sma","line",{name:void 0,tooltip:{valueDecimals:4},linkedTo:void 0,compareToMain:!1,params:{index:0,
period:14}},{processData:function(){var c=this.options.compareToMain,a=this.linkedParent;n.prototype.processData.apply(this,arguments);a&&a.compareValue&&c&&(this.compareValue=a.compareValue)},bindTo:{series:!0,eventName:"updatedData"},hasDerivedData:!0,useCommonDataGrouping:!0,nameComponents:["period"],nameSuffixes:[],calculateOn:"init",requiredIndicators:[],requireIndicators:function(){var a={allLoaded:!0};this.requiredIndicators.forEach(function(c){e[c]?e[c].prototype.requireIndicators():(a.allLoaded=
!1,a.needed=c)});return a},init:function(a,d){function c(){var a=b.points||[],c=(b.xData||[]).length,d=b.getValues(b.linkedParent,b.options.params)||{values:[],xData:[],yData:[]},e=[],f=!0;if(c&&!b.hasGroupedData&&b.visible&&b.points)if(b.cropped){if(b.xAxis){var g=b.xAxis.min;var m=b.xAxis.max}c=b.cropData(d.xData,d.yData,g,m);for(g=0;g<c.xData.length;g++)e.push([c.xData[g]].concat(r(c.yData[g])));c=d.xData.indexOf(b.xData[0]);g=d.xData.indexOf(b.xData[b.xData.length-1]);-1===c&&g===d.xData.length-
2&&e[0][0]===a[0].x&&e.shift();b.updateData(e)}else d.xData.length!==c-1&&d.xData.length!==c+1&&(f=!1,b.updateData(d.values));f&&(b.xData=d.xData,b.yData=d.yData,b.options.data=d.values);!1===b.bindTo.series&&(delete b.processedXData,b.isDirty=!0,b.redraw());b.isDirtyData=!1}var b=this,e=b.requireIndicators();if(!e.allLoaded)return g(q(b.type,e.needed));n.prototype.init.call(b,a,d);a.linkSeries();b.dataEventsToUnbind=[];if(!b.linkedParent)return g("Series "+b.options.linkedTo+" not found! Check `linkedTo`.",
!1,a);b.dataEventsToUnbind.push(m(b.bindTo.series?b.linkedParent:b.linkedParent.xAxis,b.bindTo.eventName,c));if("init"===b.calculateOn)c();else var f=m(b.chart,b.calculateOn,function(){c();f()});return b},getName:function(){var a=this.name,d=[];a||((this.nameComponents||[]).forEach(function(a,c){d.push(this.options.params[a]+k(this.nameSuffixes[c],""))},this),a=(this.nameBase||this.type.toUpperCase())+(this.nameComponents?" ("+d.join(", ")+")":""));return a},getValues:function(a,d){var c=d.period,
b=a.xData;a=a.yData;var e=a.length,f=0,g=0,m=[],h=[],l=[],k=-1;if(!(b.length<c)){for(u(a[0])&&(k=d.index?d.index:0);f<c-1;)g+=0>k?a[f]:a[f][k],f++;for(d=f;d<e;d++){g+=0>k?a[d]:a[d][k];var n=[b[d],g/c];m.push(n);h.push(n[0]);l.push(n[1]);g-=0>k?a[d-f]:a[d-f][k]}return{values:m,xData:h,yData:l}}},destroy:function(){this.dataEventsToUnbind.forEach(function(a){a()});n.prototype.destroy.apply(this,arguments)}});""});h(a,"Stock/Indicators/TrendLineIndicator.js",[a["Core/Series/Series.js"],a["Core/Utilities.js"]],
function(a,h){var l=h.isArray;a.seriesType("trendline","sma",{params:{index:3}},{nameBase:"Trendline",nameComponents:!1,getValues:function(a,e){var f=a.xData,g=a.yData;a=[];var h=[],u=[],k=0,r=0,n=0,p=0,q=f.length,c=e.index;for(e=0;e<q;e++){var d=f[e];var t=l(g[e])?g[e][c]:g[e];k+=d;r+=t;n+=d*t;p+=d*d}g=(q*n-k*r)/(q*p-k*k);isNaN(g)&&(g=0);k=(r-g*k)/q;for(e=0;e<q;e++)d=f[e],t=g*d+k,a[e]=[d,t],h[e]=d,u[e]=t;return{xData:h,yData:u,values:a}}});""});h(a,"masters/indicators/trendline.src.js",[],function(){})});
//# sourceMappingURL=trendline.js.map