/*
 Highstock JS v8.2.0 (2020-10-07)

 Indicator series type for Highstock

 (c) 2010-2019 Rafal Sebestjanski

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/indicators/trix",["highcharts","highcharts/modules/stock"],function(f){a(f);a.Highcharts=f;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function f(a,d,q,k){a.hasOwnProperty(d)||(a[d]=k.apply(null,q))}a=a?a._modules:{};f(a,"Mixins/IndicatorRequired.js",[a["Core/Utilities.js"]],function(a){var d=a.error;return{isParentLoaded:function(a,
k,m,g,e){if(a)return g?g(a):!0;d(e||this.generateMessage(m,k));return!1},generateMessage:function(a,d){return'Error: "'+a+'" indicator type requires "'+d+'" indicator loaded before. Please read docs: https://api.highcharts.com/highstock/plotOptions.'+a}}});f(a,"Stock/Indicators/EMAIndicator.js",[a["Core/Series/Series.js"],a["Core/Utilities.js"]],function(a,d){var f=d.correctFloat,k=d.isArray;a.seriesType("ema","sma",{params:{index:3,period:9}},{accumulatePeriodPoints:function(a,g,e){for(var b=0,c=
0,m;c<a;)m=0>g?e[c]:e[c][g],b+=m,c++;return b},calculateEma:function(a,g,e,b,c,w,d){a=a[e-1];g=0>w?g[e-1]:g[e-1][w];b="undefined"===typeof c?d:f(g*b+c*(1-b));return[a,b]},getValues:function(a,g){var e=g.period,b=a.xData,c=(a=a.yData)?a.length:0,d=2/(e+1),f=[],m=[],x=[],p=-1;if(!(c<e)){k(a[0])&&(p=g.index?g.index:0);g=this.accumulatePeriodPoints(e,p,a);for(g/=e;e<c+1;e++){var n=this.calculateEma(b,a,e,d,n,p,g);f.push(n);m.push(n[0]);x.push(n[1]);n=n[1]}return{values:f,xData:m,yData:x}}}});""});f(a,
"Stock/Indicators/TEMAIndicator.js",[a["Core/Series/Series.js"],a["Mixins/IndicatorRequired.js"],a["Core/Utilities.js"]],function(a,d,f){var k=f.correctFloat,m=f.isArray,g=a.seriesTypes.ema;a.seriesType("tema","ema",{},{init:function(){var a=arguments,b=this;d.isParentLoaded(g,"ema",b.type,function(e){e.prototype.init.apply(b,a)})},getEMA:function(a,b,c,d,f,m){return g.prototype.calculateEma(m||[],a,"undefined"===typeof f?1:f,this.chart.series[0].EMApercent,b,"undefined"===typeof d?-1:d,c)},getTemaPoint:function(a,
b,c,g){return[a[g-3],k(3*c.level1-3*c.level2+c.level3)]},getValues:function(a,b){var c=b.period,e=2*c,d=3*c,f=a.xData,k=a.yData,p=k?k.length:0,n=-1,q=[],v=[],y=[],r=[],u=[],l,t,h={};a.EMApercent=2/(c+1);if(!(p<3*c-2)){m(k[0])&&(n=b.index?b.index:0);a=g.prototype.accumulatePeriodPoints(c,n,k);b=a/c;a=0;for(l=c;l<p+3;l++){l<p+1&&(h.level1=this.getEMA(k,A,b,n,l)[1],r.push(h.level1));var A=h.level1;if(l<e)a+=h.level1;else{l===e&&(b=a/c,a=0);h.level1=r[l-c-1];h.level2=this.getEMA([h.level1],z,b)[1];u.push(h.level2);
var z=h.level2;if(l<d)a+=h.level2;else{l===d&&(b=a/c);l===p+1&&(h.level1=r[l-c-1],h.level2=this.getEMA([h.level1],z,b)[1],u.push(h.level2));h.level1=r[l-c-2];h.level2=u[l-2*c-1];h.level3=this.getEMA([h.level2],h.prevLevel3,b)[1];if(t=this.getTemaPoint(f,d,h,l))q.push(t),v.push(t[0]),y.push(t[1]);h.prevLevel3=h.level3}}}return{values:q,xData:v,yData:y}}}});""});f(a,"Stock/Indicators/TRIXIndicator.js",[a["Core/Series/Series.js"],a["Mixins/IndicatorRequired.js"],a["Core/Utilities.js"]],function(a,d,
f){var k=f.correctFloat,m=a.seriesTypes.tema;a.seriesType("trix","tema",{},{init:function(){var a=arguments,e=this;d.isParentLoaded(m,"tema",e.type,function(b){b.prototype.init.apply(e,a)})},getTemaPoint:function(a,e,b,c){if(c>e)var d=[a[c-3],0!==b.prevLevel3?k(b.level3-b.prevLevel3)/b.prevLevel3*100:null];return d}});""});f(a,"masters/indicators/trix.src.js",[],function(){})});
//# sourceMappingURL=trix.js.map