/*
 Highstock JS v8.2.0 (2020-10-07)

 Indicator series type for Highstock

 (c) 2010-2019 Pawe Dalek

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/indicators/vwap",["highcharts","highcharts/modules/stock"],function(f){a(f);a.Highcharts=f;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function f(a,k,w,e){a.hasOwnProperty(k)||(a[k]=e.apply(null,w))}a=a?a._modules:{};f(a,"Mixins/IndicatorRequired.js",[a["Core/Utilities.js"]],function(a){var k=a.error;return{isParentLoaded:function(a,
e,g,h,m){if(a)return h?h(a):!0;k(m||this.generateMessage(g,e));return!1},generateMessage:function(a,e){return'Error: "'+a+'" indicator type requires "'+e+'" indicator loaded before. Please read docs: https://api.highcharts.com/highstock/plotOptions.'+a}}});f(a,"Stock/Indicators/SMAIndicator.js",[a["Core/Series/Series.js"],a["Core/Globals.js"],a["Mixins/IndicatorRequired.js"],a["Core/Utilities.js"]],function(a,k,f,e){var g=a.seriesTypes,h=e.addEvent,m=e.error,n=e.extend,q=e.isArray,r=e.pick,t=e.splat,
c=k.Series,u=g.ohlc.prototype,x=f.generateMessage;h(k.Series,"init",function(d){d=d.options;d.useOhlcData&&"highcharts-navigator-series"!==d.id&&n(this,{pointValKey:u.pointValKey,keys:u.keys,pointArrayMap:u.pointArrayMap,toYData:u.toYData})});h(c,"afterSetOptions",function(d){d=d.options;var a=d.dataGrouping;a&&d.useOhlcData&&"highcharts-navigator-series"!==d.id&&(a.approximation="ohlc")});a.seriesType("sma","line",{name:void 0,tooltip:{valueDecimals:4},linkedTo:void 0,compareToMain:!1,params:{index:0,
period:14}},{processData:function(){var d=this.options.compareToMain,a=this.linkedParent;c.prototype.processData.apply(this,arguments);a&&a.compareValue&&d&&(this.compareValue=a.compareValue)},bindTo:{series:!0,eventName:"updatedData"},hasDerivedData:!0,useCommonDataGrouping:!0,nameComponents:["period"],nameSuffixes:[],calculateOn:"init",requiredIndicators:[],requireIndicators:function(){var a={allLoaded:!0};this.requiredIndicators.forEach(function(d){g[d]?g[d].prototype.requireIndicators():(a.allLoaded=
!1,a.needed=d)});return a},init:function(a,l){function d(){var a=b.points||[],d=(b.xData||[]).length,c=b.getValues(b.linkedParent,b.options.params)||{values:[],xData:[],yData:[]},l=[],e=!0;if(d&&!b.hasGroupedData&&b.visible&&b.points)if(b.cropped){if(b.xAxis){var g=b.xAxis.min;var h=b.xAxis.max}d=b.cropData(c.xData,c.yData,g,h);for(g=0;g<d.xData.length;g++)l.push([d.xData[g]].concat(t(d.yData[g])));d=c.xData.indexOf(b.xData[0]);g=c.xData.indexOf(b.xData[b.xData.length-1]);-1===d&&g===c.xData.length-
2&&l[0][0]===a[0].x&&l.shift();b.updateData(l)}else c.xData.length!==d-1&&c.xData.length!==d+1&&(e=!1,b.updateData(c.values));e&&(b.xData=c.xData,b.yData=c.yData,b.options.data=c.values);!1===b.bindTo.series&&(delete b.processedXData,b.isDirty=!0,b.redraw());b.isDirtyData=!1}var b=this,e=b.requireIndicators();if(!e.allLoaded)return m(x(b.type,e.needed));c.prototype.init.call(b,a,l);a.linkSeries();b.dataEventsToUnbind=[];if(!b.linkedParent)return m("Series "+b.options.linkedTo+" not found! Check `linkedTo`.",
!1,a);b.dataEventsToUnbind.push(h(b.bindTo.series?b.linkedParent:b.linkedParent.xAxis,b.bindTo.eventName,d));if("init"===b.calculateOn)d();else var g=h(b.chart,b.calculateOn,function(){d();g()});return b},getName:function(){var a=this.name,c=[];a||((this.nameComponents||[]).forEach(function(a,b){c.push(this.options.params[a]+r(this.nameSuffixes[b],""))},this),a=(this.nameBase||this.type.toUpperCase())+(this.nameComponents?" ("+c.join(", ")+")":""));return a},getValues:function(a,c){var d=c.period,
b=a.xData;a=a.yData;var g=a.length,e=0,h=0,m=[],l=[],k=[],f=-1;if(!(b.length<d)){for(q(a[0])&&(f=c.index?c.index:0);e<d-1;)h+=0>f?a[e]:a[e][f],e++;for(c=e;c<g;c++){h+=0>f?a[c]:a[c][f];var n=[b[c],h/d];m.push(n);l.push(n[0]);k.push(n[1]);h-=0>f?a[c-e]:a[c-e][f]}return{values:m,xData:l,yData:k}}},destroy:function(){this.dataEventsToUnbind.forEach(function(a){a()});c.prototype.destroy.apply(this,arguments)}});""});f(a,"Stock/Indicators/VWAPIndicator.js",[a["Core/Series/Series.js"],a["Core/Utilities.js"]],
function(a,f){var k=f.error,e=f.isArray;a.seriesType("vwap","sma",{params:{period:30,volumeSeriesID:"volume"}},{getValues:function(a,h){var f=a.chart,g=a.xData;a=a.yData;var q=h.period,r=!0,t;if(t=f.get(h.volumeSeriesID))return e(a[0])||(r=!1),this.calculateVWAPValues(r,g,a,t,q);k("Series "+h.volumeSeriesID+" not found! Check `volumeSeriesID`.",!0,f)},calculateVWAPValues:function(a,e,f,k,q){var g=k.yData,h=k.xData.length,c=e.length;k=[];var m=[],n=[],d=[],l=[],p;h=c<=h?c:h;for(p=c=0;c<h;c++){var b=
a?(f[c][1]+f[c][2]+f[c][3])/3:f[c];b*=g[c];b=p?k[c-1]+b:b;var v=p?m[c-1]+g[c]:g[c];k.push(b);m.push(v);l.push([e[c],b/v]);n.push(l[c][0]);d.push(l[c][1]);p++;p===q&&(p=0)}return{values:l,xData:n,yData:d}}});""});f(a,"masters/indicators/vwap.src.js",[],function(){})});
//# sourceMappingURL=vwap.js.map