/*
 Highstock JS v8.2.0 (2020-10-07)

 Indicator series type for Highstock

 (c) 2010-2019 Kacper Madej

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/indicators/wma",["highcharts","highcharts/modules/stock"],function(h){a(h);a.Highcharts=h;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function h(a,g,t,f){a.hasOwnProperty(g)||(a[g]=f.apply(null,t))}a=a?a._modules:{};h(a,"Mixins/IndicatorRequired.js",[a["Core/Utilities.js"]],function(a){var g=a.error;return{isParentLoaded:function(a,
f,h,b,e){if(a)return b?b(a):!0;g(e||this.generateMessage(h,f));return!1},generateMessage:function(a,f){return'Error: "'+a+'" indicator type requires "'+f+'" indicator loaded before. Please read docs: https://api.highcharts.com/highstock/plotOptions.'+a}}});h(a,"Stock/Indicators/SMAIndicator.js",[a["Core/Series/Series.js"],a["Core/Globals.js"],a["Mixins/IndicatorRequired.js"],a["Core/Utilities.js"]],function(a,h,t,f){var g=a.seriesTypes,b=f.addEvent,e=f.error,l=f.extend,v=f.isArray,w=f.pick,k=f.splat,
p=h.Series,n=g.ohlc.prototype,r=t.generateMessage;b(h.Series,"init",function(d){d=d.options;d.useOhlcData&&"highcharts-navigator-series"!==d.id&&l(this,{pointValKey:n.pointValKey,keys:n.keys,pointArrayMap:n.pointArrayMap,toYData:n.toYData})});b(p,"afterSetOptions",function(d){d=d.options;var a=d.dataGrouping;a&&d.useOhlcData&&"highcharts-navigator-series"!==d.id&&(a.approximation="ohlc")});a.seriesType("sma","line",{name:void 0,tooltip:{valueDecimals:4},linkedTo:void 0,compareToMain:!1,params:{index:0,
period:14}},{processData:function(){var d=this.options.compareToMain,a=this.linkedParent;p.prototype.processData.apply(this,arguments);a&&a.compareValue&&d&&(this.compareValue=a.compareValue)},bindTo:{series:!0,eventName:"updatedData"},hasDerivedData:!0,useCommonDataGrouping:!0,nameComponents:["period"],nameSuffixes:[],calculateOn:"init",requiredIndicators:[],requireIndicators:function(){var a={allLoaded:!0};this.requiredIndicators.forEach(function(d){g[d]?g[d].prototype.requireIndicators():(a.allLoaded=
!1,a.needed=d)});return a},init:function(a,m){function d(){var a=c.points||[],d=(c.xData||[]).length,b=c.getValues(c.linkedParent,c.options.params)||{values:[],xData:[],yData:[]},e=[],l=!0;if(d&&!c.hasGroupedData&&c.visible&&c.points)if(c.cropped){if(c.xAxis){var m=c.xAxis.min;var f=c.xAxis.max}d=c.cropData(b.xData,b.yData,m,f);for(m=0;m<d.xData.length;m++)e.push([d.xData[m]].concat(k(d.yData[m])));d=b.xData.indexOf(c.xData[0]);m=b.xData.indexOf(c.xData[c.xData.length-1]);-1===d&&m===b.xData.length-
2&&e[0][0]===a[0].x&&e.shift();c.updateData(e)}else b.xData.length!==d-1&&b.xData.length!==d+1&&(l=!1,c.updateData(b.values));l&&(c.xData=b.xData,c.yData=b.yData,c.options.data=b.values);!1===c.bindTo.series&&(delete c.processedXData,c.isDirty=!0,c.redraw());c.isDirtyData=!1}var c=this,l=c.requireIndicators();if(!l.allLoaded)return e(r(c.type,l.needed));p.prototype.init.call(c,a,m);a.linkSeries();c.dataEventsToUnbind=[];if(!c.linkedParent)return e("Series "+c.options.linkedTo+" not found! Check `linkedTo`.",
!1,a);c.dataEventsToUnbind.push(b(c.bindTo.series?c.linkedParent:c.linkedParent.xAxis,c.bindTo.eventName,d));if("init"===c.calculateOn)d();else var f=b(c.chart,c.calculateOn,function(){d();f()});return c},getName:function(){var a=this.name,b=[];a||((this.nameComponents||[]).forEach(function(a,d){b.push(this.options.params[a]+w(this.nameSuffixes[d],""))},this),a=(this.nameBase||this.type.toUpperCase())+(this.nameComponents?" ("+b.join(", ")+")":""));return a},getValues:function(a,b){var d=b.period,
c=a.xData;a=a.yData;var e=a.length,l=0,f=0,k=[],m=[],h=[],g=-1;if(!(c.length<d)){for(v(a[0])&&(g=b.index?b.index:0);l<d-1;)f+=0>g?a[l]:a[l][g],l++;for(b=l;b<e;b++){f+=0>g?a[b]:a[b][g];var n=[c[b],f/d];k.push(n);m.push(n[0]);h.push(n[1]);f-=0>g?a[b-l]:a[b-l][g]}return{values:k,xData:m,yData:h}}},destroy:function(){this.dataEventsToUnbind.forEach(function(a){a()});p.prototype.destroy.apply(this,arguments)}});""});h(a,"Stock/Indicators/WMAIndicator.js",[a["Core/Series/Series.js"],a["Core/Utilities.js"]],
function(a,g){function h(a,e){e*=(e+1)/2;return a.reduce(function(a,b,e){return[null,a[1]+b[1]*(e+1)]})[1]/e}function f(a,e,l,f){l=h(a,a.length);e=e[f-1];a.shift();return[e,l]}var u=g.isArray;a.seriesType("wma","sma",{params:{index:3,period:9}},{getValues:function(a,e){var b=e.period,g=a.xData,h=(a=a.yData)?a.length:0,k=1,p=g[0],n=a[0],r=[],d=[],m=[],q=-1;if(!(g.length<b)){u(a[0])&&(q=e.index,n=a[0][q]);for(e=[[p,n]];k!==b;)e.push([g[k],0>q?a[k]:a[k][q]]),k++;for(b=k;b<h;b++)k=f(e,g,a,b),r.push(k),
d.push(k[0]),m.push(k[1]),e.push([g[b],0>q?a[b]:a[b][q]]);k=f(e,g,a,b);r.push(k);d.push(k[0]);m.push(k[1]);return{values:r,xData:d,yData:m}}}});""});h(a,"masters/indicators/wma.src.js",[],function(){})});
//# sourceMappingURL=wma.js.map