/*
 Highstock JS v8.2.0 (2020-10-07)

 Indicator series type for Highstock

 (c) 2010-2019 Kacper Madej

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/indicators/zigzag",["highcharts","highcharts/modules/stock"],function(h){a(h);a.Highcharts=h;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function h(a,m,k,f){a.hasOwnProperty(m)||(a[m]=f.apply(null,k))}a=a?a._modules:{};h(a,"Mixins/IndicatorRequired.js",[a["Core/Utilities.js"]],function(a){var m=a.error;return{isParentLoaded:function(a,
f,l,e,h){if(a)return e?e(a):!0;m(h||this.generateMessage(l,f));return!1},generateMessage:function(a,f){return'Error: "'+a+'" indicator type requires "'+f+'" indicator loaded before. Please read docs: https://api.highcharts.com/highstock/plotOptions.'+a}}});h(a,"Stock/Indicators/SMAIndicator.js",[a["Core/Series/Series.js"],a["Core/Globals.js"],a["Mixins/IndicatorRequired.js"],a["Core/Utilities.js"]],function(a,m,k,f){var l=a.seriesTypes,e=f.addEvent,h=f.error,g=f.extend,p=f.isArray,v=f.pick,q=f.splat,
d=m.Series,n=l.ohlc.prototype,t=k.generateMessage;e(m.Series,"init",function(c){c=c.options;c.useOhlcData&&"highcharts-navigator-series"!==c.id&&g(this,{pointValKey:n.pointValKey,keys:n.keys,pointArrayMap:n.pointArrayMap,toYData:n.toYData})});e(d,"afterSetOptions",function(c){c=c.options;var a=c.dataGrouping;a&&c.useOhlcData&&"highcharts-navigator-series"!==c.id&&(a.approximation="ohlc")});a.seriesType("sma","line",{name:void 0,tooltip:{valueDecimals:4},linkedTo:void 0,compareToMain:!1,params:{index:0,
period:14}},{processData:function(){var c=this.options.compareToMain,a=this.linkedParent;d.prototype.processData.apply(this,arguments);a&&a.compareValue&&c&&(this.compareValue=a.compareValue)},bindTo:{series:!0,eventName:"updatedData"},hasDerivedData:!0,useCommonDataGrouping:!0,nameComponents:["period"],nameSuffixes:[],calculateOn:"init",requiredIndicators:[],requireIndicators:function(){var c={allLoaded:!0};this.requiredIndicators.forEach(function(a){l[a]?l[a].prototype.requireIndicators():(c.allLoaded=
!1,c.needed=a)});return c},init:function(a,f){function c(){var a=b.points||[],c=(b.xData||[]).length,d=b.getValues(b.linkedParent,b.options.params)||{values:[],xData:[],yData:[]},f=[],g=!0;if(c&&!b.hasGroupedData&&b.visible&&b.points)if(b.cropped){if(b.xAxis){var e=b.xAxis.min;var r=b.xAxis.max}c=b.cropData(d.xData,d.yData,e,r);for(e=0;e<c.xData.length;e++)f.push([c.xData[e]].concat(q(c.yData[e])));c=d.xData.indexOf(b.xData[0]);e=d.xData.indexOf(b.xData[b.xData.length-1]);-1===c&&e===d.xData.length-
2&&f[0][0]===a[0].x&&f.shift();b.updateData(f)}else d.xData.length!==c-1&&d.xData.length!==c+1&&(g=!1,b.updateData(d.values));g&&(b.xData=d.xData,b.yData=d.yData,b.options.data=d.values);!1===b.bindTo.series&&(delete b.processedXData,b.isDirty=!0,b.redraw());b.isDirtyData=!1}var b=this,g=b.requireIndicators();if(!g.allLoaded)return h(t(b.type,g.needed));d.prototype.init.call(b,a,f);a.linkSeries();b.dataEventsToUnbind=[];if(!b.linkedParent)return h("Series "+b.options.linkedTo+" not found! Check `linkedTo`.",
!1,a);b.dataEventsToUnbind.push(e(b.bindTo.series?b.linkedParent:b.linkedParent.xAxis,b.bindTo.eventName,c));if("init"===b.calculateOn)c();else var r=e(b.chart,b.calculateOn,function(){c();r()});return b},getName:function(){var c=this.name,a=[];c||((this.nameComponents||[]).forEach(function(c,b){a.push(this.options.params[c]+v(this.nameSuffixes[b],""))},this),c=(this.nameBase||this.type.toUpperCase())+(this.nameComponents?" ("+a.join(", ")+")":""));return c},getValues:function(c,a){var d=a.period,
b=c.xData;c=c.yData;var f=c.length,e=0,g=0,m=[],l=[],h=[],k=-1;if(!(b.length<d)){for(p(c[0])&&(k=a.index?a.index:0);e<d-1;)g+=0>k?c[e]:c[e][k],e++;for(a=e;a<f;a++){g+=0>k?c[a]:c[a][k];var n=[b[a],g/d];m.push(n);l.push(n[0]);h.push(n[1]);g-=0>k?c[a-e]:c[a-e][k]}return{values:m,xData:l,yData:h}}},destroy:function(){this.dataEventsToUnbind.forEach(function(a){a()});d.prototype.destroy.apply(this,arguments)}});""});h(a,"Stock/Indicators/ZigzagIndicator.js",[a["Core/Series/Series.js"]],function(a){a.seriesType("zigzag",
"sma",{params:{lowIndex:2,highIndex:1,deviation:1}},{nameComponents:["deviation"],nameSuffixes:["%"],nameBase:"Zig Zag",getValues:function(a,k){var f=k.lowIndex,l=k.highIndex,e=k.deviation/100;k=1+e;var h=1-e;e=a.xData;var g=a.yData;a=g?g.length:0;var p=[],m=[],q=[],d,n,t=!1,c=!1;if(!(!e||1>=e.length||a&&("undefined"===typeof g[0][f]||"undefined"===typeof g[0][l]))){var r=g[0][f];var u=g[0][l];for(d=1;d<a;d++){if(g[d][f]<=u*h){p.push([e[0],u]);var b=[e[d],g[d][f]];t=n=!0}else g[d][l]>=r*k&&(p.push([e[0],
r]),b=[e[d],g[d][l]],n=!1,t=!0);if(t){m.push(p[0][0]);q.push(p[0][1]);var w=d++;d=a}}for(d=w;d<a;d++)n?(g[d][f]<=b[1]&&(b=[e[d],g[d][f]]),g[d][l]>=b[1]*k&&(c=l)):(g[d][l]>=b[1]&&(b=[e[d],g[d][l]]),g[d][f]<=b[1]*h&&(c=f)),!1!==c&&(p.push(b),m.push(b[0]),q.push(b[1]),b=[e[d],g[d][c]],n=!n,c=!1);f=p.length;0!==f&&p[f-1][0]<e[a-1]&&(p.push(b),m.push(b[0]),q.push(b[1]));return{values:p,xData:m,yData:q}}}});""});h(a,"masters/indicators/zigzag.src.js",[],function(){})});
//# sourceMappingURL=zigzag.js.map